.rubocop.yml, app/channels/application_cable/channel.rb, app/channels/application_cable/connection.rb, app/controllers/application_controller.rb, app/controllers/claims_controller.rb, app/helpers/application_helper.rb, app/helpers/steps_helper.rb, app/services/decisions/simple_decision_tree.rb, app/views/claims/index.html.erb, app/views/steps/firm_details/edit.html.erb, gems/laa_multi_step_forms/app/controllers/laa_multi_step_forms/application_controller.rb, gems/laa_multi_step_forms/app/helpers/laa_multi_step_forms/application_helper.rb, spec/controllers/claims_controller_spec.rb, spec/controllers/providers/session_controller_spec.rb, spec/decisions/simple_decision_tree_spec.rb, spec/helpers/application_helper_spec.rb, spec/helpers/steps_helper_spec.rb, spec/models/claim_spec.rb, spec/models/provider_spec.rb, spec/spec_helper.rb, spec/steps/claim_type/form_spec.rb, spec/steps/firm_details/controller_spec.rb, spec/steps/firm_details/form_spec.rb, spec/support/authentication_helpers.rb, spec/support/steps/a_generic_step_controller.rb, spec/support/steps/a_step_that_can_be_drafted.rb
Get testing on the main app up to 100%
=> Testing percentage on main app back to desired level

app/controllers/steps/firm_details_controller.rb, app/forms/steps/firm_details/solicitor_form.rb, app/forms/steps/firm_details_form.rb, app/views/steps/firm_details/edit.html.erb, config/locales/en/helpers.yml, config/locales/en/steps.yml, spec/steps/firm_details/form_spec.rb, spec/steps/firm_details/forms/solicitor_spec.rb, spec/steps/firm_details/integration_spec.rb
Update firm details design
https://trello.com/c/DIsryY6H/307-update-firm-details-design
=> update firm details design

app/controllers/steps/hearing_details_controller.rb, app/forms/steps/hearing_details_form.rb, app/models/matter_type.rb, app/models/outcome_code.rb, app/presenters/tasks/firm_details.rb, app/presenters/tasks/hearing_details.rb, app/services/decisions/simple_decision_tree.rb, app/views/steps/hearing_details/edit.html.erb, config/locales/en/helpers.yml, config/locales/en/steps.yml, config/routes.rb, db/migrate/20230512153017_add_hearing_details.rb, db/schema.rb, gems/laa_multi_step_forms/app/models/laa_multi_step_forms/court.rb, gems/laa_multi_step_forms/spec/models/court_spec.rb, spec/decisions/simple_decision_tree_spec.rb, spec/steps/firm_details/presenter_spec.rb, spec/steps/hearing_details/controller_spec.rb, spec/steps/hearing_details/form_spec.rb, spec/steps/hearing_details/integration_spec.rb, spec/steps/hearing_details/matter_type_spec.rb, spec/steps/hearing_details/outcome_code_spec.rb, spec/steps/hearing_details/presenter_spec.rb
Add hearing details step to system
https://trello.com/c/vnkmhyDb/308-hearingdetails-step
=> Q1 s2/hearing details

app/controllers/steps/defendant_details_controller.rb, app/forms/steps/case_details_form.rb, app/forms/steps/defendant_details_form.rb, app/forms/steps/defendants_details_form.rb, app/models/claim.rb, app/models/defendant.rb, app/presenters/tasks/defendant_details.rb, app/services/decisions/simple_decision_tree.rb, app/views/steps/defendant_details/edit.html.erb, config/locales/en/errors.yml, config/locales/en/helpers.yml, config/locales/en/steps.yml, config/routes.rb, db/migrate/20230519131318_create_defendants.rb, db/schema.rb, gems/laa_multi_step_forms/app/assets/stylesheets/laa_multi_step_forms/local/moj.scss, gems/laa_multi_step_forms/app/validators/nested_validator.rb, gems/laa_multi_step_forms/spec/validators/nested_validator_spec.rb, spec/decisions/simple_decision_tree_spec.rb, spec/steps/case_details/form_spec.rb, spec/steps/case_details/integration_spec.rb, spec/steps/defendant_details/controller_spec.rb, spec/steps/defendant_details/defendant_form_spec.rb, spec/steps/defendant_details/form_spec.rb, spec/steps/defendant_details/integration_spec.rb, spec/steps/defendant_details/presenter_spec.rb
Add defendant details step
https://trello.com/c/ewwv7cR4/318-defendantdetails-step
NOTE: Issue with alignment on remove button - This has been flagged to @imtiazAhmd for review
=> Q1 s2/defendant details

config/locales/en.yml, gems/laa_multi_step_forms/app/views/layouts/_phase_banner.html.erb
Update Phase banner to say development
https://dsdmoj.atlassian.net/browse/CRM457-97
=> Update Phase Banner to say development

.sonarcloud.properties, app/services/decisions/simple_decision_tree.rb, spec/decisions/simple_decision_tree_spec.rb
Bug in sonar cloud config
https://dsdmoj.atlassian.net/browse/CRM457-107
=> [CRM457-107] Fix sonarcloud config

Dockerfile, README.md, app/controllers/claims_controller.rb, app/presenters/start_page.rb, app/presenters/tasks/claim_type.rb, app/presenters/tasks/firm_details.rb, app/views/steps/claim_type/edit.html.erb, config/locales/en.yml, config/locales/en/helpers.yml, config/locales/en/steps.yml, config/locales/en/tasklist.yml, gems/laa_multi_step_forms/spec/dummy/config/locales/en.yml, gems/laa_multi_step_forms/spec/helpers/application_helper_spec.rb, spec/controllers/claims_controller_spec.rb, spec/steps/claim_type/integration_spec.rb, spec/steps/claim_type/presenter_spec.rb, spec/steps/start_page/integration_spec.rb
Fix bugs
Rename to be `Claim a non-standard magistrates' court payment` thoughout
Fix Claim Type link and status on Start page
https://dsdmoj.atlassian.net/browse/CRM457-55
https://dsdmoj.atlassian.net/browse/CRM457-101
https://dsdmoj.atlassian.net/browse/CRM457-52
only some of the issues raised in https://dsdmoj.atlassian.net/browse/CRM457-101 where fixed as the remained have requested design confirmation.
=> [bugfixes] First round of bugfixes for the app 

app/forms/steps/letters_calls_form.rb, app/javascript/application.js, app/javascript/controllers/letters_calls_form_controller.js, app/views/steps/letters_calls/edit.html.erb, babel.config.js, jest.config.js, package.json, spec/steps/letters_calls/letters_calls_form_controller.spec.js, test/javascript/letters_calls_form_controller.test.js, yarn.lock
This will add the feature to update total as user fills up the form
[FE: Letters and calls](https://dsdmoj.atlassian.net/browse/CRM457-75)
As user types the letters and calls, total for the items should reflect as per the design.
- As a user, when I type in the number of letters (and the number of calls) in their respective input boxes and then tab out of the box, the total cost will automatically update.
- If a user changes any fields (letters or calls) after the initial update, it will trigger the update of the total cost.
- When a user adds a number into the percentage box and then tabs out of the box, the total cost will update based on the uplift percentage.
- If the user unticks the uplift box, the percentage box will be emptied, the reveal field will be removed, and the total cost …
=> [CRM457-75] FE: Letters and calls

kubectl_deploy/deployment.tpl
Ensure we display the correct name in the Dev environment
https://dsdmoj.atlassian.net/browse/CRM457-97
=> Set ENV and RAILS_ENV in settings

kubectl_deploy/deployment.tpl
https://github.com/ministryofjustice/analytical-platform-uploader/blob/c8f3b01c7f8f4a3362b57ecb04be5f0dfe786ddf/kubectl_deploy_dev/deployment.tpl#L35
https://dsdmoj.atlassian.net/browse/CRM457-97
=> don't quote enclose options

kubectl_deploy/deployment.tpl
Bin the last set of changes that I believe caused the error to get the env back up and running 
https://dsdmoj.atlassian.net/browse/CRM457-97
=> [CRM457-97] revert ENV changes

app/forms/steps/work_item_form.rb, app/presenters/tasks/work_items.rb, app/views/steps/letters_calls/edit.html.erb, db/schema.rb, spec/steps/work_items/add/form_spec.rb, spec/steps/work_items/presenter_spec.rb
Fix incorrect value showing for Letter and Calls total costs
Fix `can start` check on Working Item
Fix Work Item cost calculation to include uplift
https://dsdmoj.atlassian.net/browse/CRM457-131
=> Crm457 131/incorrect calculation

.github/CODEOWNERS
Update code owners
https://dsdmoj.atlassian.net/browse/CRM457-135
=> update code owners to include @ministryofjustice/crm7team

app/assets/stylesheets/application.scss, app/assets/stylesheets/custom/govuk-date-legend.scss, app/controllers/claims_controller.rb, app/forms/steps/claim_type_form.rb, app/views/steps/case_details/edit.html.erb, app/views/steps/case_disposal/edit.html.erb, app/views/steps/claim_type/edit.html.erb, app/views/steps/hearing_details/edit.html.erb, app/views/steps/reason_for_claim/edit.html.erb, app/views/steps/work_item/edit.html.erb, config/locales/en/helpers.yml, spec/controllers/claims_controller_spec.rb, spec/steps/claim_type/form_spec.rb
Fix the following bugs:
https://dsdmoj.atlassian.net/browse/CRM457-56
Format for date field legend to be non-bold in reveal;
https://dsdmoj.atlassian.net/browse/CRM457-58
Content changes for your details
https://dsdmoj.atlassian.net/browse/CRM457-130
Bug on Start screen after something else was selected
=> Bugs fixes 2

app/controllers/home_controller.rb
Removes test code in Controllers::HomeController for Sentry to trigger an error
[Add Error Monitoring to Application](https://dsdmoj.atlassian.net/browse/CRM457-158)
Addition of Sentry is already merged and tested in main and deployed
=> remove sentry test code

.gitignore, app/controllers/steps/disbursement_cost_controller.rb, app/forms/steps/disbursement_cost_form.rb, app/forms/steps/disbursement_type_form.rb, app/forms/steps/letters_calls_form.rb, app/forms/steps/work_item_form.rb, app/lib/pricing.rb, app/presenters/tasks/disbursements.rb, app/services/decisions/simple_decision_tree.rb, app/views/steps/disbursement_cost/edit.html.erb, config/locales/en/helpers.yml, config/locales/en/steps.yml, config/pricing.yml, config/routes.rb, db/migrate/20230623103721_add_vat_amount.rb, db/schema.rb, gems/laa_multi_step_forms/app/controllers/steps/base_step_controller.rb, gems/laa_multi_step_forms/app/helpers/laa_multi_step_forms/form_builder_helper.rb, gems/laa_multi_step_forms/config/locales/en/helpers.yml, gems/laa_multi_step_forms/spec/controllers/steps/base_step_controller_spec.rb, gems/laa_multi_step_forms/spec/helpers/form_builder_helper_spec.rb, spec/lib/pricing_spec.rb, spec/steps/disbursements/cost/controller_spec.rb, spec/steps/disbursements/cost/form_spec.rb, spec/steps/disbursements/integration_spec.rb, spec/steps/disbursements/presenter_spec.rb
Add Disbursement costs screen to the system
https://dsdmoj.atlassian.net/browse/CRM457-62
This does not include JS updates of the field - will be a separate PR
=> Crm457 62/disbursement costs

.rubocop.yml, app/controllers/steps/defendant_delete_controller.rb, app/controllers/steps/defendant_details_controller.rb, app/controllers/steps/disbursement_type_controller.rb, app/controllers/steps/work_item_controller.rb, app/presenters/start_page.rb, app/presenters/tasks/defendants.rb, app/presenters/tasks/disbursements.rb, app/presenters/tasks/letters_calls.rb, app/presenters/tasks/work_items.rb, app/services/decisions/simple_decision_tree.rb, app/views/steps/defendant_details/edit.html.erb, app/views/steps/work_items/edit.html.erb, config/routes.rb, db/schema.rb, spec/controllers/claims_controller_spec.rb, spec/decisions/simple_decision_tree_spec.rb, spec/steps/defendants/add/controller_spec.rb, spec/steps/defendants/delete/controller_spec.rb, spec/steps/defendants/integration_spec.rb, spec/steps/defendants/presenter_spec.rb, spec/steps/disbursements/presenter_spec.rb, spec/steps/disbursements/type/controller_spec.rb, spec/steps/letters_calls/presenter_spec.rb, spec/steps/work_items/add/controller_spec.rb, spec/steps/work_items/delete/controller_spec.rb, spec/steps/work_items/integration_spec.rb, spec/steps/work_items/presenter_spec.rb, spec/support/steps/a_decision_with_nested_object.rb, spec/support/steps/a_generic_decision.rb
Use restful routes for defendants and work items
https://dsdmoj.atlassian.net/browse/CRM457-198
=> Crm457 198/fix routing

app/controllers/steps/disbursement_type_controller.rb, app/controllers/steps/hearing_details_controller.rb, app/forms/steps/disbursement_type_form.rb, app/forms/steps/hearing_details_form.rb, app/helpers/application_helper.rb, app/javascript/application.js, app/views/steps/disbursement_type/edit.html.erb, app/views/steps/disbursements/edit.html.erb, app/views/steps/hearing_details/edit.html.erb, gems/laa_multi_step_forms/.rubocop.yml, gems/laa_multi_step_forms/app/forms/steps/base_form_object.rb, gems/laa_multi_step_forms/app/helpers/laa_multi_step_forms/application_helper.rb, gems/laa_multi_step_forms/app/models/laa_multi_step_forms/court.rb, gems/laa_multi_step_forms/docs/Suggestion.md, gems/laa_multi_step_forms/spec/controllers/error_handling_spec.rb, gems/laa_multi_step_forms/spec/forms/steps/base_form_object_spec.rb, gems/laa_multi_step_forms/spec/helpers/application_helper_spec.rb, gems/laa_multi_step_forms/spec/models/court_spec.rb, spec/steps/disbursements/type/form_spec.rb, spec/steps/hearing_details/form_spec.rb
Make autocomplete work as a suggestion box
https://dsdmoj.atlassian.net/browse/CRM457-215
Read the Doc file first as this will hopefully explain how it works
This would ideally have automated testing, but that requires integration test to use JS - which is outside the scope of this PR.
=> Crm457 215/suggestion box

app/presenters/start_page.rb, app/presenters/tasks/case_disposal.rb, app/presenters/tasks/hearing_details.rb, app/presenters/tasks/reason_for_claim.rb, app/services/decisions/simple_decision_tree.rb, spec/decisions/simple_decision_tree_spec.rb, spec/steps/case_disposal/presenter_spec.rb, spec/steps/hearing_details/presenter_spec.rb, spec/steps/reason_for_claim/presenter_spec.rb
Update page order as per the ticket
https://dsdmoj.atlassian.net/browse/CRM457-203
=> Update page ordering

.github/workflows/test-build-deploy.yml, config/routes.rb
- Update gitaction to use pull_request_target to access env vars for dependabot
- Add catchall route for errors
=> Minor Repo Changes

.github/workflows/test-build-deploy.yml
- Fixes the reference that the action checks for whether to push to prod or not
=> Fix broken build

.github/workflows/test-build-deploy-main.yml, .github/workflows/test-build-deploy-pr.yml, .github/workflows/test-build-deploy.yml
- Update the gitactions to fix some missing items
=> Update prod conditional

.github/workflows/test-build-deploy-pr.yml
=> Update helm deploy sha

helm_deploy/values-dev.yaml, helm_deploy/values-prod.yaml, helm_deploy/values-uat.yaml, helm_deploy/values.yaml
- Updates the modsec anomaly rule so that we can reduce the false positive hits
- [CRM457-246](https://dsdmoj.atlassian.net/browse/CRM457-246)
https://github.com/ministryofjustice/laa-court-data-ui/pull/761 did this work initially when we hit this
[CRM457-246]: https://dsdmoj.atlassian.net/browse/CRM457-246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRM457-246 - Update modsec rules

.github/workflows/test-build-deploy-main.yml, .github/workflows/test-build-deploy-pr.yml
Allow my other PR to pass https://github.com/ministryofjustice/laa-claim-non-standard-magistrate-fee-backend/pull/137
N/A
=> add PassWithNoTests flag to JS tests

app/forms/steps/work_item_form.rb, app/models/defendant.rb, app/models/disbursement.rb, app/models/work_item.rb, app/views/steps/work_item/edit.html.erb, db/migrate/20230713091036_fix_bad_data.rb, db/schema.rb, spec/steps/work_items/add/form_spec.rb
Fix the issues identiifed when testing https://github.com/ministryofjustice/laa-claim-non-standard-magistrate-fee-backend/pull/137
https://ministryofjustice.sentry.io/issues/4310429767/?project=4505369863651328&query=&referrer=project-issue-stream
https://dsdmoj.atlassian.net/browse/CRM457-261
=> Crm457 261/fix broken flow

app/controllers/steps/equality_controller.rb, app/forms/steps/answer_equality_form.rb, app/services/decisions/simple_decision_tree.rb, app/views/steps/equality/edit.html.erb, config/locales/en/helpers.yml, config/locales/en/steps.yml, config/routes.rb, spec/decisions/simple_decision_tree_spec.rb, spec/steps/equality/controller_spec.rb, spec/steps/equality/form_spec.rb, spec/steps/equality/integration_spec.rb
Add the first equality page
https://dsdmoj.atlassian.net/browse/CRM457-211
=> Crm457 211/equality page 1

helm_deploy/values-uat.yaml
Increase server memory from 125Mi to 250Mi
N/A
=> increase server memory in UAT

app/views/steps/claim_type/edit.html.erb, config/locales/en/claims.yml, config/locales/en/errors.yml, config/locales/en/helpers.yml, config/locales/en/steps.yml, config/locales/en/tasklist.yml, spec/steps/case_details/integration_spec.rb, spec/steps/hearing_details/integration_spec.rb
Just a heap of content related bugs and typos
https://dsdmoj.atlassian.net/browse/CRM457-317 - typo in claim type
https://dsdmoj.atlassian.net/browse/CRM457-313 - typo in hearing details
https://dsdmoj.atlassian.net/browse/CRM457-298 - typo in case details
https://dsdmoj.atlassian.net/browse/CRM457-297 - fix defendant summary table headers
https://dsdmoj.atlassian.net/browse/CRM457-294 - update tasklist titles
https://dsdmoj.atlassian.net/browse/CRM457-292 - remove ? from page title/heading
https://dsdmoj.atlassian.net/browse/CRM457-299 - fix hint text location
https://dsdmoj.atlassian.net/browse/CRM457-291 - bold field names
https://dsdmoj.atlassian.net/browse/CRM457-290 - Start a new claim
=> Content bugs

app/presenters/check_answers/case_details_card.rb, app/presenters/check_answers/case_disposal_card.rb, config/locales/en/check_answers.yml, db/schema.rb, spec/factories/claims.rb, spec/presenters/check_answers/case_disposal_card_spec.rb, spec/steps/check_answers/controller_spec.rb, spec/steps/other_info/integration_spec.rb, spec/support/steps/a_show_steps_controller.rb
=> [CRM457-210]  Check your answers step - Case disposal

app/presenters/check_answers/disbursement_costs_card.rb, app/presenters/cost_summary/base.rb, app/presenters/cost_summary/disbursements.rb, app/presenters/cost_summary/letters_calls.rb, app/presenters/cost_summary/work_items.rb, config/locales/en/helpers.yml, spec/factories/claims.rb, spec/presenters/check_answers/disbursement_cost_card_spec.rb, spec/support/steps/a_show_steps_controller.rb
=> [CRM457-210] Check your answers step - Disbursements

app/views/steps/case_details/edit.html.erb, app/views/steps/equality/edit.html.erb, app/views/steps/firm_details/edit.html.erb, app/views/steps/other_info/edit.html.erb, app/views/steps/work_item/edit.html.erb, config/locales/en/helpers.yml
Fix the small content bugs in one go
https://dsdmoj.atlassian.net/browse/CRM457-330 - fix translations and label sizing
https://dsdmoj.atlassian.net/browse/CRM457-328 - fix copy
https://dsdmoj.atlassian.net/browse/CRM457-327 - Fix remittal date formatting
=> Fix bug aug 1

.github/workflows/test-build-deploy-main.yml, .github/workflows/test-build-deploy-pr.yml
- Updates build scripts to log in using short lived credentials
- Updates pushing build after using this new method
[CRM457-345](https://dsdmoj.atlassian.net/browse/CRM457-345)
Due to the setup of our scripts, this wont use the new actions until within main. 
[CRM457-345]: https://dsdmoj.atlassian.net/browse/CRM457-345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRM457-345 - Update build scripts

.github/workflows/test-build-deploy-main.yml
- Update UAT and PROD pushes to use the new tag name
[CRM457-345](https://dsdmoj.atlassian.net/browse/CRM457-345)
[CRM457-345]: https://dsdmoj.atlassian.net/browse/CRM457-345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRM457-345 - Fix UAT and PROD deploys

app/forms/steps/firm_details/solicitor_form.rb, app/forms/steps/solicitor_declaration_form.rb, config/locales/en/errors.yml, spec/steps/solicitor_declaration/form_spec.rb
Add name validation throughout the application
https://dsdmoj.atlassian.net/browse/CRM457-331
=> CRM457-331/Add name validation throughout the application

app/presenters/tasks/solicitor_declaration.rb, spec/steps/solicitor_declaration/presenter_spec.rb
Stop task list from showing a link to the declaration page (must be accessed via the confirm page
https://dsdmoj.atlassian.net/browse/CRM457-338
=> Crm457 338/declaration link

app/presenters/check_answers/base.rb, app/presenters/check_answers/case_details_card.rb, app/presenters/check_answers/case_disposal_card.rb, app/presenters/check_answers/claim_details_card.rb, app/presenters/check_answers/claim_justification_card.rb, app/presenters/check_answers/hearing_details_card.rb, app/value_objects/plea_options.rb, config/locales/en/check_answers.yml, spec/factories/claims.rb, spec/presenters/check_answers/case_details_card_spec.rb, spec/presenters/check_answers/case_disposal_card_spec.rb, spec/presenters/check_answers/claim_justification_card_spec.rb, spec/presenters/check_answers/hearing_details_card_spec.rb
Add missing data tags to the check answers page
https://dsdmoj.atlassian.net/browse/CRM457-337
=> Crm457 337/no data on check answers 2

config/application.rb, config/locales/en/claims.yml, db/migrate/20230816151707_change_pending_to_draft.rb, db/schema.rb, spec/steps/claim_confirmation/integration_spec.rb
Change default claim status from pending to draft
https://dsdmoj.atlassian.net/browse/CRM457-401
=> Chnage in progress to draft for claim status

Gemfile, Gemfile.lock, config/initializers/sidekiq.rb, helm_deploy/templates/deployment.yaml
- Adds env vars and initial config for sidekiq
[CRM457-414](https://dsdmoj.atlassian.net/browse/CRM457-414)
[CRM457-414]: https://dsdmoj.atlassian.net/browse/CRM457-414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRM457-414 - Add sidekiq to repo

.github/workflows/test-build-deploy-main.yml, config/initializers/sidekiq.rb
Add redis to CI so that tests will pass in https://github.com/ministryofjustice/laa-claim-non-standard-magistrate-fee-backend/pull/223
N/A
=> Add redis to CI pipeline

package.json, yarn.lock
Updates multiple JS dependencies from Dependabot PRs
=> Update multiple JS dependencies

app/views/claims/index.html.erb
Updates the button to match the figma designs
Has been approved by design
=> Update layout for button

app/services/notify_app_store/message_builder.rb, spec/services/notify_app_store/message_builder_spec.rb
- Adds application_type to send to App Store
N/A
=> Add application_type

helm_deploy/values-prod.yaml
Add helm values for production to mock auth
=> Add production config to mock authentication

helm_deploy/values-prod.yaml
Update production helm deploy values and add metadata for production SAML auth
https://dsdmoj.atlassian.net/jira/software/c/projects/CRM457/boards/1192?selectedIssue=CRM457-618
=> Update prod values to use portal auth

config/laa_portal/metadata/prod.xml, helm_deploy/values-prod.yaml
Use correct metadata from: https://portal.legalservices.gov.uk/oamfed/idp/metadata 
for production
https://dsdmoj.atlassian.net/jira/software/c/projects/CRM457/boards/1192?selectedIssue=CRM457-618
=> Crm457 prod auth

app/forms/steps/hearing_details_form.rb, app/presenters/check_answers/hearing_details_card.rb, app/views/steps/hearing_details/edit.html.erb, config/locales/en/check_answers.yml, config/locales/en/errors.yml, config/locales/en/helpers.yml, db/migrate/20231026134409_update_youth_court_name.rb, db/schema.rb, spec/factories/claims.rb, spec/presenters/check_answers/hearing_details_card_spec.rb, spec/services/notify_app_store/message_builder_spec.rb, spec/steps/hearing_details/form_spec.rb, spec/steps/hearing_details/integration_spec.rb
- Renames youth_count to youth_court
=> CRM457-645 - Rename youth count to youth court

app/models/claim.rb, spec/services/notify_app_store/message_builder_spec.rb
- Translate Hearing outcome
- Update test
=> CRM457-645 - Translate hearing_outcome

app/controllers/about_controller.rb, app/views/about/contact.en.html.erb, config/application.rb, spec/controllers/about_controller_spec.rb
- Add controller for contact page
- Add content for contact page
- Add test
N/A
=> Add contact us

config/locales/en/errors.yml
set missing error messages for withdrawn date
https://dsdmoj.atlassian.net/browse/CRM457-541
=> Set missing withdrawn date errors

Gemfile, Gemfile.lock, helm_deploy/templates/deployment-worker.yaml, helm_deploy/values-dev.yaml, helm_deploy/values-prod.yaml, helm_deploy/values-uat.yaml
- Adds sidekiq worker into K8s to process email sending
=> CRM457-645 - Add Sidekiq worker

helm_deploy/templates/deployment-worker.yaml, helm_deploy/templates/deployment.yaml
- Adds env var for tracking id
=> CRM457-645 - Add tracking id env var

Dockerfile, helm_deploy/templates/deployment.yaml, helm_deploy/values-dev.yaml, helm_deploy/values-prod.yaml, helm_deploy/values-uat.yaml
- Updates endpoints to utilise values files
- Uses HTTPS endpoints
- Uses the right environments
=> Update app store endpoints

app/assets/stylesheets/custom/govuk-table__nowrap.scss, app/views/steps/defendant_summary/edit.html.erb, app/views/steps/disbursements/edit.html.erb, app/views/steps/work_items/edit.html.erb, config/locales/en/steps.yml
- Updates columns for Work Items
- Updates columns for Defendants
- Updates columns for Disbursements
[Add columns in the change and delete columns to disbursements](https://dsdmoj.atlassian.net/browse/CRM457-692)
[Add column for both "Change" and "delete" in defendant pages](https://dsdmoj.atlassian.net/browse/CRM457-696)
[Add columns in the change, duplicate and delete columns for work items](https://dsdmoj.atlassian.net/browse/CRM457-684)
Weighting done by eyeing figma file and trying to best guess.
=> Crm457 684/add change columns

app/models/claim.rb, spec/services/notify_app_store/message_builder_spec.rb
- Add translations for Equality Answers
- Update tests
[CRM457-708](https://dsdmoj.atlassian.net/browse/CRM457-708)
[CRM457-708]: https://dsdmoj.atlassian.net/browse/CRM457-708?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRM457-708 - Add translations for equality questions

app/models/claim.rb, app/models/matter_type.rb, app/models/outcome_code.rb, spec/services/notify_app_store/message_builder_spec.rb
- FIxes translations from strings to translation objects
- Update tests
- Adds helper method to valueobjects to help get name by id
[Provider App: Add Translations to Application Version Payload](https://dsdmoj.atlassian.net/browse/CRM457-546)
=> CRM457-546 - Fix bad translations

app/models/claim.rb, app/models/matter_type.rb, app/models/outcome_code.rb, spec/services/notify_app_store/message_builder_spec.rb
- Use description instead of full name
- Use correct query language
=> CRM457-546 - Use description rather than wrong function

app/models/claim.rb, config/locales/en/claims.yml, spec/factories/claims.rb, spec/presenters/check_answers/application_status_card_spec.rb
- Add further_info and provider_requested states
- replicate review states for now
=> Update states to split further and provider reviews

app/controllers/steps/office/confirm_controller.rb, app/controllers/steps/office/select_controller.rb, app/forms/steps/office/confirm_form.rb, app/forms/steps/office/select_form.rb, app/helpers/application_helper.rb, app/lib/laa_portal/saml_strategy.rb, app/models/provider.rb, app/services/decisions/office_decision_tree.rb, app/services/providers/active_office_checker.rb, app/services/providers/office_router.rb, app/views/home/index.en.html.erb, app/views/steps/office/confirm/edit.html.erb, app/views/steps/office/select/edit.html.erb, config/application.rb, config/gatekeeper.yml, config/inactive_offices.yml, config/locales/en/helpers.yml, config/locales/en/steps.yml, config/routes.rb, spec/decisions/office_decision_tree_spec.rb, spec/helpers/application_helper_spec.rb, spec/models/provider_spec.rb, spec/services/providers/office_router_spec.rb, spec/steps/office/provider/confirm_controller_spec.rb, spec/steps/office/provider/confirm_form_spec.rb, spec/steps/office/provider/select_controller_spec.rb, spec/steps/office/provider/select_form_spec.rb
Copy office selection code from crime apply
https://dsdmoj.atlassian.net/browse/CRM457-349
Still needs design input as this is just what was on crime apply
Currently the only time the office can be changed is during login.
=> Crm457 349/multiple offices

config/inactive_offices.yml
- Inactive office codes staging changed to uat
=> CRM457-349 - Change env name

db/migrate/20231206105140_add_total_cost_columns.rb, db/schema.rb, spec/services/notify_app_store/message_builder_spec.rb
- Adds total/adjusted cost columns
- Updates tests
[CRM457-780](https://dsdmoj.atlassian.net/browse/CRM457-780)
Total costs are not being saved just yet - refer to ticket
[CRM457-780]: https://dsdmoj.atlassian.net/browse/CRM457-780?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRM457-780 - Add total cost columns

app/forms/steps/claim_details_form.rb, config/locales/en/errors.yml
1. Allow a value of minimum 0 for prosecution/defence evidence and witnesses
2. Update error messages in line with ticket
[Error message on claim details on provider app
](https://dsdmoj.atlassian.net/browse/CRM457-773)
=> Crm457-773 -  Error message on claim details on provider app

config/locales/en/errors.yml
Change error messages for solicitor name and contact name
[Error message when adding just one name is incomplete](https://dsdmoj.atlassian.net/browse/CRM457-776)
=> Update errors relating to full name

Gemfile.lock
Bump bundler to latest version
=> Bump bundler 2.4.10 --> 2.4.22

README.md, config/database.yml, config/environments/development.rb
Minor changes coming from my getting set up
- Add expected database names to database config
- Add loopback address to allowed hosts for local development
- Document typical database env file change
=> Tweaks from onboarding

.gitignore, Brewfile
Add Brewfile and .gitignore some files
The README contains instruction to brew bundle
but no Brewfile exists. This adds what appears to
be a minimal requirement of services to install
for this app.
=> Add Brewfile and .gitignore some files

config/locales/en/errors.yml
Fix: correct translation
noticed this while testing form builder bump.
=> Fix: correct translation

app/services/notify_app_store/message_builder.rb, spec/services/notify_app_store/message_builder_spec.rb
Add VAT rate to main message body to allow processing on CW side
https://dsdmoj.atlassian.net/browse/CRM457-786
=> Add VAT rate to main JSON message

app/forms/steps/solicitor_declaration_form.rb, app/lib/cost_calculator.rb, spec/factories/claims.rb, spec/factories/disbursements.rb, spec/lib/cost_calculator_spec.rb
- Added to CostCalculator calculation for disbursement totals
- Added to cost_totals object in application to include disbursements=
[Provider: Submit Disbursement Total Data to App Store
](https://dsdmoj.atlassian.net/browse/CRM457-841)
=> Crm457 841 disbursment totals 

helm_deploy/values-dev-crm4.yaml
CRM457-854: Point dev-crm4 env to equivalent appstore
[link to story](https://dsdmoj.atlassian.net/browse/CRM457-854)
=> CRM457-854: Point dev-crm4 env to equivalent appstore

spec/steps/firm_details/form_spec.rb
Remove temporary skipped/unimplemented spec example
If this is needed I would ticket it. Its been here 8/9
months so far.
=> Remove temporary skipped/unimplemented spec example

.github/dependabot.yml
Amend dependabot config
- add reviewer
- reduce max open PRs allowed
- group a few dependencies
=> Amend dependabot config

app/views/nsm/steps/work_items/edit.html.erb, config/importmap.rb
Somehow I didn't notice I broke the importmap for MOJ 2.0.
Also while testing I came across some corrupt I18n keys that, in all likelihood, I also broke when re-namespacing
=> BUG: MOJ frontend js fail

app/assets/stylesheets/custom/task_list.scss, app/controllers/prior_authority/steps/start_page_controller.rb, app/views/prior_authority/applications/index.html.erb, app/views/prior_authority/steps/ufn/edit.html.erb, config/locales/en/errors.yml, config/locales/en/prior_authority.yml, gems/laa_multi_step_forms/app/views/laa_multi_step_forms/task_list/show.html.erb, spec/forms/prior_authority/steps/ufn_form_spec.rb, spec/system/prior_authority/authority_value_spec.rb, spec/system/prior_authority/create_application_spec.rb, spec/system/support/prior_authority/step_helpers.rb
Update wording of validation messages as per the error spreadsheet
Update UI of new application button as per the prototype
https://dsdmoj.atlassian.net/browse/CRM457-973
=> CRM457-973: Update button text and wording validation

.github/pull_request_template.md
Amend PR template
Add ticket link boiler plate for simplicities sake
=> Amend PR template

app/views/prior_authority/applications/confirm_delete.html.erb
Tweak the 'confirm delete' screen to match the prototype
https://dsdmoj.atlassian.net/browse/CRM457-1014
=> CRM457-1014: Tweak confirm deletion UI

spec/system/prior_authority/reason_why_spec.rb
We had a TODO because the file upload mechanism was really hard to test using our old capybara driver. Now we've switched to Selenium we can actually do the test, so here's an attempt at it.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-988)
I had a go at setting up Clamby both locally and on CI and got nowhere, so I've let myself off the hook and just bypassed it for this test. More than happy to commit to getting it running in test env in future but I think that may need to be a separate ticket.
=> CRM457-988 addendum: Test file upload

app/services/decisions/back_decision_tree.rb, app/services/decisions/decision_tree.rb, spec/system/prior_authority/client_detail_spec.rb, spec/system/prior_authority/next_hearing_spec.rb, spec/system/support/prior_authority/step_helpers.rb
Client details now leads back to application progress as per QA comment
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-981)
=> CRM457-981: Client details onwards navigation

app/controllers/prior_authority/applications_controller.rb, app/helpers/sortable_table_helper.rb, app/views/prior_authority/applications/assessed.html.erb, app/views/prior_authority/applications/draft.html.erb, app/views/prior_authority/applications/frame_contents/_assessed.html.erb, app/views/prior_authority/applications/frame_contents/_draft.html.erb, app/views/prior_authority/applications/frame_contents/_submitted.html.erb, app/views/prior_authority/applications/submitted.html.erb, spec/system/prior_authority/application_lists_spec.rb
Put most recently created applications at the top of the list.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1110)
=> CRM457-1110: Default to sorting by most recent

app/forms/prior_authority/steps/reason_why_form.rb, config/locales/en/errors.yml, spec/forms/prior_authority/steps/reason_why_form_spec.rb
Add missing error condition as identifed during QA
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-988)
=> [CRM457-988] QA-feedback: Add missing error condition

app/controllers/prior_authority/steps/travel_detail_controller.rb, app/forms/prior_authority/quote_cost_validations.rb, app/forms/prior_authority/steps/additional_costs/detail_form.rb, app/views/prior_authority/steps/travel_detail/edit.html.erb, config/locales/en/errors.yml, config/locales/en/prior_authority/alternative_quotes.yml, gems/laa_multi_step_forms/app/validators/time_period_validator.rb, gems/laa_multi_step_forms/spec/validators/time_period_validator_spec.rb, spec/system/prior_authority/travel_detail_spec.rb
Fix bugs identified in QA
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1016)
=> [Crm457-1016] bugs

config/locales/en/prior_authority.yml, spec/system/prior_authority/authority_value_spec.rb, spec/system/prior_authority/create_application_spec.rb, spec/system/support/prior_authority/step_helpers.rb
[CRM4 Provider - Copy change to 'New application' button](https://dsdmoj.atlassian.net/browse/CRM457-1139)
=> CRM457-1139 CRM4 Provider - Copy change to 'New application' button

.github/CODEOWNERS
amend codeowners following team name change
=> amend codeowners

app/forms/prior_authority/steps/additional_costs/detail_form.rb, app/forms/prior_authority/steps/alternative_quotes/detail_form.rb, app/forms/prior_authority/steps/primary_quote_form.rb, app/forms/prior_authority/steps/quote_cost_form.rb, app/forms/prior_authority/steps/service_cost_form.rb, app/forms/prior_authority/steps/travel_detail_form.rb, app/lib/prior_authority/service_type_rule.rb, app/value_objects/prior_authority/quote_services.rb, app/views/prior_authority/steps/alternative_quote_details/edit.html.erb, app/views/prior_authority/steps/primary_quote_summary/_travel_cost_card.html.erb, app/views/prior_authority/steps/travel_detail/edit.html.erb, config/locales/en/errors.yml, config/locales/en/helpers.yml, config/locales/en/prior_authority/alternative_quotes.yml, config/locales/en/prior_authority/steps.yml, spec/forms/prior_authority/steps/alternative_quotes/detail_form_spec.rb, spec/forms/prior_authority/steps/primary_quote_form_spec.rb, spec/system/prior_authority/service_cost_spec.rb, spec/system/support/prior_authority/step_helpers.rb
Following first round of QA, add some missed error messages, and ensure gbp values are formatted to 2 decimal places.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-983)
=> CRM457-983: Add more validations and formatting

Procfile.dev
Correct Procfile.dev 
Fix erroneous append of js command
=> Fix erroneous append of js command in `Procfile.dev`

app/views/nsm/claims/index.html.erb, app/views/nsm/steps/case_details/edit.html.erb, app/views/nsm/steps/supporting_evidence/edit.html.erb, app/views/prior_authority/steps/reason_why/edit.html.erb, config/initializers/content_security_policy.rb, gems/laa_multi_step_forms/app/views/layouts/_header_navigation.html.erb, gems/laa_multi_step_forms/app/views/layouts/govuk_template.html.erb
- Switch on a CSP
- Add nonces where necessary
- Document how to add SHA-identified exceptions
- Don't report policy violations (because browser extensions etc mean you drown in not-very-helpful false positives)
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1092)
=> CRM457-1092: Add nonces and CSP

.env.development, Procfile.dev, README.md, docs/development-e2e-setup.md
Document setup for e2e development
[Comes out of ticket](https://dsdmoj.atlassian.net/browse/CRM457-992)
=> Setup for local e2e development

app/jobs/pull_updates.rb, db/migrate/20240307165611_add_app_store_updated_at_to_prior_authority_application.rb, db/schema.rb, spec/jobs/pull_updates_spec.rb
Process updates to state of PA applications reported by the app store
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1101)
This is for a caseworker ticket, that has an AC saying when a PA application is granted etc, it should move into the appropriate tab on the provider app
=> CRM457-1101: Pull PA updates

.env.development, app/models/prior_authority_application.rb, app/presenters/nsm/check_answers/application_status_card.rb, config/locales/en/nsm/check_answers.yml, config/locales/en/prior_authority.yml
Allow auto_grant status to be returned from CW
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-984)
=> [CRM457-984] Allow auto_grant status

app/jobs/pull_updates.rb, app/services/http_puller.rb, spec/jobs/pull_updates_spec.rb, spec/services/http_puller_spec.rb
Fix bug in branches when polling not working
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1240)
=> [CRM457-1240] Process all pages when polling

helm_deploy/templates/deployment-worker.yaml, helm_deploy/templates/deployment.yaml
[Provider Application Failing to Deploy to UAT/Prod](https://dsdmoj.atlassian.net/browse/CRM457-1248)
=> change liveness and readiness probe is "ping"

app/models/prior_authority_application.rb
Add PROVIDER_UPDATED, EXPIRED, SENT_BACK to status enum
[Request Further Information: Update states allowed for applications and claims](https://dsdmoj.atlassian.net/browse/CRM457-1150)
=> Request Further Information: Update states allowed for applications and claims

app/views/prior_authority/applications/frame_contents/_reviewed.html.erb, app/views/prior_authority/applications/response_summaries/_sent_back.html.erb, app/views/prior_authority/applications/show.html.erb, app/views/prior_authority/applications/state_summaries/_expired.html.erb, app/views/prior_authority/applications/state_summaries/_granted.html.erb, app/views/prior_authority/applications/state_summaries/_part_grant.html.erb, app/views/prior_authority/applications/state_summaries/_rejected.html.erb, app/views/prior_authority/applications/state_summaries/_sent_back.html.erb, config/locales/en/prior_authority.yml, spec/system/prior_authority/view_assessed_applications_spec.rb
* Tweak application details back for "Update needed" applications
* Refactor partials to reduce duplication
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1194)
=> CRM457-1194: Application details for sent_back state

app/services/prior_authority/assessment_syncer.rb, app/views/prior_authority/applications/response_summaries/_sent_back.html.erb, db/migrate/20240322135218_add_table_further_information.rb, db/migrate/20240325121503_add_columns_to_further_information.rb, db/migrate/20240326115712_add_incorrect_info_to_pa.rb, db/migrate/20240326132108_drop_further_information_explanation_from_prior_authority_application.rb, db/schema.rb, spec/services/prior_authority/assessment_syncer_spec.rb
Fixes and refactors
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1192)
=> CRM457-1192: Fix and refactor

app/controllers/prior_authority/steps/further_information_controller.rb, app/presenters/prior_authority/check_answers/further_information_card.rb, app/presenters/prior_authority/check_answers/report.rb, app/services/prior_authority/last_update_finder.rb, app/views/prior_authority/applications/response_summaries/_sent_back.html.erb, config/locales/en/prior_authority.yml, config/locales/en/prior_authority/check_answers.yml, spec/factories/further_informations.rb, spec/factories/prior_authority_application.rb, spec/forms/prior_authority/steps/check_answers_form_spec.rb, spec/presenters/prior_authority/check_answers/further_information_card_spec.rb, spec/presenters/prior_authority/check_answers/report_spec.rb, spec/services/prior_authority/last_update_finder_spec.rb, spec/system/prior_authority/check_your_answers/sent_back_for_correct_info_spec.rb, spec/system/prior_authority/check_your_answers/sent_back_for_further_info_spec.rb
Add further information request card to check your answers
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1226)
This could be merged into the branch for 1192 now
=> CRM457-1226: Add RFI card to CYA page

app/services/prior_authority/assessment_syncer.rb, app/services/submit_to_app_store/prior_authority/event_builder.rb, spec/jobs/pull_updates_spec.rb, spec/services/prior_authority/assessment_syncer_spec.rb, spec/services/submit_to_app_store/prior_authority/event_builder_spec.rb
Sister PR to https://github.com/ministryofjustice/laa-assess-crime-forms/pull/392
=> Stop referring to event class names in payload

config/environments/production.rb, helm_deploy/templates/deployment.yaml
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1285)
To prevent DNS rebinding and host header attacks
=> CRM457-1285: Specify which hosts are allowed

.circleci/config.yml
try swapping the deploy step for a run step as deploy is deprecated
=> replace deploy with a run step

app/services/prior_authority/assessment_syncer.rb, spec/jobs/pull_updates_spec.rb
=> Fix assessment syncer error handling

spec/services/submit_to_app_store/nsm_payload_builder_spec.rb
Fix bug caused by random data
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1281)
=> CRM457-1281 - Fix bug caused by random data

app/controllers/sync_controller.rb, app/jobs/pull_updates.rb, app/services/app_store_client.rb, app/services/app_store_subscriber.rb, app/services/app_store_token_authenticator.rb, app/services/app_store_update_processor.rb, app/services/prior_authority/assessment_syncer.rb, config/application.rb, config/routes.rb, config/schedule.yml, helm_deploy/values-dev.yaml, spec/jobs/pull_updates_spec.rb, spec/requests/sync_spec.rb, spec/services/app_store_subscriber_spec.rb, spec/services/app_store_update_processor_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1327)
=> CRM457-1327: Sub/Pub instead of cron

config/feature_flags.yml
Reverting to normal after tests concluded
=> Turn On Auth Test Mode in Dev

app/controllers/nsm/steps/supporting_evidence_controller.rb, app/forms/nsm/steps/supporting_evidence_form.rb, app/presenters/nsm/check_answers/evidence_uploads_card.rb, app/views/nsm/steps/supporting_evidence/_content.html.erb, app/views/nsm/steps/supporting_evidence/edit.html.erb, app/views/shared/_multifile_upload.html.erb, config/feature_flags.yml, config/locales/en/errors.yml, config/locales/en/nsm/steps.yml, spec/forms/nsm/steps/supporting_evidence_form_spec.rb, spec/presenters/nsm/check_answers/evidence_upload_card_spec.rb, spec/system/nsm/supporting_evidence_spec.rb
Feature flag postal evidence references, and tweak copy around digital evidence upload
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1308)
=> CRM457-1308: Postal evidence

app/presenters/prior_authority/check_answers/alternative_quotes_card.rb, app/presenters/prior_authority/check_answers/hearing_detail_card.rb, app/views/prior_authority/steps/additional_costs/_cost_summary.html.erb, app/views/prior_authority/steps/alternative_quotes/_quote_summary.html.erb, app/views/prior_authority/steps/check_answers/_primary_quote_details.html.erb, app/views/prior_authority/steps/primary_quote_summary/_travel_cost_card.html.erb, config/locales/en/prior_authority/check_answers.yml, spec/presenters/prior_authority/check_answers/alternative_quotes_card_spec.rb, spec/presenters/prior_authority/check_answers/hearing_detail_card_spec.rb, spec/system/prior_authority/check_your_answers/no_prison_law_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1172)
=> CRM457-1172: Add line breaks to multi-line display text

config/feature_flags.yml
=> Enabled omniauth test mode in UAT

app/presenters/nsm/check_answers/base.rb, app/presenters/nsm/check_answers/claim_type_card.rb, app/presenters/nsm/check_answers/cost_summary_card.rb, app/presenters/nsm/check_answers/report.rb, app/views/nsm/steps/check_answers/show.html.erb, app/views/nsm/steps/cost_summary/_summary_table.html.erb, config/locales/en/nsm/check_answers.yml, spec/presenters/nsm/check_answers/claim_type_card_spec.rb, spec/presenters/nsm/check_answers/report_spec.rb, spec/system/nsm/check_answers_spec.rb
- Use the new cost summary table on CYA page
- Change width logic of other cards
- Add LAA reference to top card
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1295)
=> CRM457-1295: NSM CYA new cost summary card and layout tweaks

app/jobs/submit_to_app_store.rb, helm_deploy/templates/deployment-worker.yaml, helm_deploy/templates/deployment.yaml, spec/jobs/submit_to_app_store_spec.rb
- Copy the pattern that caseworker uses
- This should get the new E2E tests running
=> Add an env var for sending emails

helm_deploy/values-dev.yaml
=> Update app store url

app/forms/nsm/steps/defendant_details_form.rb, app/forms/prior_authority/steps/case_detail/defendant_form.rb, app/forms/prior_authority/steps/case_detail_form.rb, app/views/prior_authority/steps/additional_costs/edit.html.erb, app/views/prior_authority/steps/case_detail/edit.html.erb, app/views/prior_authority/steps/reason_why/edit.html.erb, config/locales/en/errors.yml, config/locales/en/prior_authority/steps.yml, spec/forms/prior_authority/steps/case_detail/defendant_form_spec.rb
- Content tweaks
- Validation ordering
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1300)
=> CRM457-1300: Content updates

app/javascript/file-upload.js, app/views/prior_authority/steps/further_information/edit.html.erb, app/views/prior_authority/steps/reason_why/edit.html.erb, app/views/shared/_multifile_upload.html.erb, config/locales/en/prior_authority/steps.yml
Use same env var for all max file sizes
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1352)
=> CRM457-1352: Standardise max file size

app/views/prior_authority/applications/response_summaries/_assessed.html.erb, config/locales/en/prior_authority.yml, spec/system/prior_authority/view_applications_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-970)
=> CRM457-970: Add appeal instructions

helm_deploy/values-prod.yaml, helm_deploy/values-uat.yaml
Amend autoscaler config to use boolean
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1455)
inline with other apps. not sure how use of "enabled" string sneaked
in.
=> CRM457-1455: Amend autoscaler config to use boolean

.circleci/config.yml, app/views/home/dev_login.html.erb, config/gatekeeper.yml, config/inactive_offices.yml
Add and amend tests users
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1386)
So a wider range of provider/user, office code and roles is available
for testing to access and privileges.
see [e2e test fixes inline with changes](https://github.com/ministryofjustice/nsm-e2e-test/pull/73)
=> CRM457-1386: improve test users

.circleci/config.yml
Revert commit 12f89343
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1386)
Merged by accident
=> Revert commit  12f89343

app/views/about/privacy.en.html.erb
Content tweaks for privacy policy
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1069)
From content designer
=> CRM457-1069: Content tweaks for privacy policy

app/views/nsm/claims/index.html.erb
Simplify NSM start button
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1449)
=> CRM457-1449: Start button

app/controllers/nsm/steps/start_page_controller.rb, app/controllers/prior_authority/steps/start_page_controller.rb, gems/laa_multi_step_forms/app/views/laa_multi_step_forms/task_list/show.html.erb
Remove task list back button
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1450)
=> CRM457-1450: Back button

config/feature_flags.yml
Switch on portal for dev 
For some testing
=> switch on portal for dev

helm_deploy/templates/ingress.yaml
=> Modsec change to allow big data chunck

config/gatekeeper.yml
Add offices for test providers
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1414)
For testing portal login on dev hosted env
=> CRM457-1414: Add offices for test providers

app/forms/nsm/steps/reason_for_claim_form.rb, spec/forms/nsm/steps/reason_for_claim_form_spec.rb
Remove any uplifts if uplifts no longer relevant
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1503)
=> CRM457-1503: Uplift wrongly applied

config/inactive_offices.yml
Revert inactive listing for portal DEV test user
=> Revert inactive listing for portal DEV test user

config/locales/en/errors.yml
Amend wasted costs presence error message
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1464)
Inline with acceptance criteria
=> crm457-1464: Amend wasted costs presence error message

helm_deploy/values-dev.yaml, helm_deploy/values-uat.yaml
=> Increase Dev HPA limits

helm_deploy/templates/deployment-worker.yaml, helm_deploy/templates/deployment.yaml
[crm457-1508](https://dsdmoj.atlassian.net/browse/CRM457-1508)
[Trying to differentiate between deployments for hpa to work properly](https://github.com/kubernetes/kubernetes/issues/120875#issuecomment-1736021400)
=> CRM457-1508 add extra labels for worker deployment

db/migrate/20240517152519_update_wasted_costs_on_claims.rb, db/schema.rb
Backfill wasted costs to be 'no'
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1464)
prevent errors on UAT and dev
=> CRM457-1464: Backfill wasted costs to be 'no'

config/locales/en/helpers.yml, config/locales/en/nsm/summary.yml, spec/models/disbursement_spec.rb, spec/system/nsm/cost_summary_spec.rb, spec/system/nsm/view_claim_spec.rb
[CRN457-1383 - CRM7 Provider/ Caseworker - mileage disbursements content tweak](https://dsdmoj.atlassian.net/browse/CRM457-1383)
=> Add mileage to disbursement content

app/forms/nsm/steps/disbursement_cost_form.rb, app/forms/nsm/steps/disbursements_form.rb, app/models/concerns/disbursement_costs.rb, app/models/disbursement.rb, app/value_objects/other_disbursement_types.rb, app/views/nsm/steps/disbursements/edit.html.erb, config/environments/test.rb, config/locales/en/errors.yml, config/locales/en/nsm/steps.yml, spec/factories/prior_authority_application.rb, spec/forms/nsm/steps/disbursements_type_form_spec.rb, spec/system/nsm/disbursements_spec.rb, spec/system/nsm/work_items_spec.rb, spec/system/prior_authority/check_your_answers/no_prison_law_spec.rb
Better messaging when there are incomplete disbursements
Also fix a bug trying to translate custom 'other' disbursement types
To add tests for that bug I needed to make the test environment raise translation errors
Which meant fixing some tests that were causing translation errors 
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1493)
=> CRM457-1493: Incomplete disbursements

config/locales/en/errors.yml, gems/laa_multi_step_forms/app/views/laa_multi_step_forms/errors/not_enrolled.html.erb
Add content for not enrolled page
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1495)
From content designer
=> CRM457-1495: Add content for not enrolled page

app/controllers/nsm/steps/view_claim_controller.rb, app/models/concerns/letters_and_calls_costs.rb, app/views/nsm/steps/view_claim/_adjustments.html.erb, app/views/nsm/steps/view_claim/allowed_letters_and_calls.html.erb, app/views/nsm/steps/view_claim/disbursements.html.erb, app/views/nsm/steps/view_claim/show.html.erb, config/locales/en/nsm/view_claim.yml, spec/factories/claims.rb, spec/system/nsm/view_claim_spec.rb
Add letters and calls adjustments page
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1459)
=> Crm457 1459/adjustments calculations 3

app/services/nsm/assessment_syncer.rb, app/services/submit_to_app_store/nsm_payload_builder.rb, app/views/nsm/steps/view_claim/disbursement.html.erb, app/views/nsm/steps/view_claim/show.html.erb, config/locales/en/nsm/view_claim.yml, db/schema.rb, spec/services/nsm/assessment_syncer_spec.rb, spec/system/nsm/view_claim_spec.rb, yarn.lock
Sync remaining disbursement values and then update the view screen display
NOTE: This is still missing `miles` from the view screen
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1459)
=> Crm457 1459/adjustments calculations 5

helm_deploy/templates/service.yaml
[[MVP] - MONITORING - Exporting metrics for Redis Queues and Sidekiq](https://dsdmoj.atlassian.net/browse/CRM457-1360)
Add app label to service so that the service monitor can link to it
=> CRM457-1360 Metrics (Pt. 2)

config/gatekeeper.yml
Add UAT portal offices to UAT
For UAT portal login testing on UAT
=> Add UAT portal offices to UAT

config/locales/en/prior_authority.yml
Amend appeal content for part-granted/rejected applications
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1542)
In line with content design changes
=> CRM457-1542: Amend appeal content for part-granted/rejected applications

config/inactive_offices.yml
Add inactive office_code to UAT
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1505)
To Test ERR_TOO_MANY_REDIRECTS
=> CMR457-1505: Add inactive office_code to UAT

config/locales/en/prior_authority.yml
Amend appeal content further
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1542)
Add changes from content designer
=> CRM457-1542: Amend appeal content further

config/locales/en/prior_authority.yml
Add full stop at end
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1542)
Missed off in rush
=> add full stop to end of appeal content

config/gatekeeper.yml
CRM457-1514: Onboard first Prior authority (CRM4) tranche
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1514)
Dummy user also onboarded for sanity testing
=> CRM457-1514: Onboard first Prior authority (CRM4) tranche

app/models/supported_file_types.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1575)
=> [CRM457-1575] Updates file types

Gemfile, Gemfile.lock, app/views/nsm/claims/index.html.erb, config/locales/en/nsm/claims.yml
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1545)
=> [CRM457-1545] CRM7 Provider: no postal evidence banner

app/presenters/nsm/check_answers/application_status_card.rb, app/views/nsm/steps/view_claim/_appeal.html.erb, config/locales/en/nsm/check_answers.yml, config/locales/en/nsm/view_claim.yml, spec/presenters/nsm/check_answers/application_status_card_spec.rb
New content for appealing
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1559)
=> CRM457-1559: Appeal info

app/views/prior_authority/applications/response_summaries/_assessed.html.erb, app/views/prior_authority/steps/check_answers/_primary_quote_details.html.erb
[CRM457-1562](https://dsdmoj.atlassian.net/browse/CRM457-1562)
[CRM457-1562]: https://dsdmoj.atlassian.net/browse/CRM457-1562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRM457-1562: Allow for multi line text on assessment comment

helm_deploy/values-dev.yaml
=> disable servicemonitoring to get dev main working

Gemfile.lock
Bump ruby version in gemfile.lock
=> Bump ruby version in gemfile.lock

app/mailers/nsm/submission_mailer.rb, spec/mailers/nsm/submission_mailer_spec.rb
Use specified contact details if provided
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1618)
=> CRM457-1618: Send to correct email

config/locales/en/nsm/steps.yml
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1580)
=> CRM457-1580: Fix case

.github/pull_request_template.md
Remove unnecessary space from PR template
=> Remove unnecessary space from PR template

app/controllers/about/cookies_controller.rb, app/controllers/about_controller.rb
[Submit a crime form provider, CRM4 provider and CRM7 provider links in footer](https://dsdmoj.atlassian.net/browse/CRM457-1631)
=> Use correct layout for footer pages

lib/tasks/submit_dummy_data.rake, spec/lib/tasks/submit_dummy_data_spec.rb
Amend dummy data generator to take args and prompt for confirmation
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1621)
=> CRM457-1621: Amend dummy data generator task

helm_deploy/templates/deployment-worker.yaml, helm_deploy/templates/deployment.yaml, helm_deploy/values-dev.yaml, helm_deploy/values-prod.yaml, helm_deploy/values-uat.yaml
Separate worker and app pod replica config
We do not need the same number of workers as app pods.
=> Separate worker and app pod replica config

.github/actions/delete-dev-release/action.yml
Delete redis pvc on merge into main
Currently have 260 of these sitting around. This should
help future tidy up
```sh
kubectl get pvc | grep redis | wc -l
```
=> Delete redis pvc on merge into main

app/views/about/contact.en.html.erb, config/application.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1661)
=> CRM457-1661: Update contact page content

app/forms/nsm/steps/firm_details/solicitor_form.rb, app/forms/prior_authority/steps/case_contact/solicitor_form.rb, spec/forms/nsm/steps/firm_details/solicitor_form_spec.rb, spec/forms/prior_authority/steps/case_contact/solicitor_form_spec.rb
[Provider: Incorrect Client Email Validation](https://dsdmoj.atlassian.net/browse/CRM457-1682)
=> CRM457-1682 - Provider: Incorrect Client Email Validation

app/views/prior_authority/steps/submission_confirmation/show.html.erb, config/locales/en/prior_authority/steps.yml, gems/laa_multi_step_forms/config/locales/en/helpers.yml
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1663)
e2e is failing due to content change. A [PR](https://github.com/ministryofjustice/nsm-e2e-test/pull/100) for e2e has been created to fix it.
=> CRM457-1663: CRM4 Provider confirmation content change

app/views/nsm/steps/claim_confirmation/show.html.erb, config/locales/en/nsm/steps.yml, gems/laa_multi_step_forms/config/locales/en/helpers.yml, spec/system/nsm/claim_confirmation_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1666)
=> CRM457-1666: CRM7 Provider confirmation content change

.circleci/config.yml
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1579)
(I have added a new context `laa-non-standard-crime-claims-alerting` that contains an access token from our new alerting Slack app
=> CRM457-1579: Alert on deployment failure

app/controllers/prior_authority/downloads_controller.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1691)
=> CRM457-1691: Handle filenames with commas

.circleci/config.yml
Start build-to-ecr immediately
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1658)
=> [CRM457-1658] Start build-to-ecr immediately

app/presenters/nsm/check_answers/application_status_card.rb, app/services/nsm/assessment_syncer.rb, spec/jobs/pull_updates_spec.rb, spec/presenters/nsm/check_answers/application_status_card_spec.rb, spec/services/nsm/assessment_syncer_spec.rb
Show granted assessment comment if it's there
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1677)
I removed the call to `sanitize` because tags are already being escaped in `join_strings`
=> CRM457-1677: Granted claim comments

config/initializers/prometheus.rb, config/initializers/sidekiq.rb
Remove sidekiq/api require and prom client
Not, in fact, needed in these locations
=> CMR457-1360: Remove unrequired lib require and prom client

docs/development-e2e-setup.md
Amend dev e2e local setup instructions
They were out of date.
=> Amend dev e2e local setup instructions

config/locales/en/nsm/claims.yml, spec/presenters/nsm/check_answers/application_status_card_spec.rb
Submitted applications should be light blue
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1693)
=> CRM457-1693: Fix tag colour

app/views/prior_authority/steps/additional_costs/_subtable.html.erb, app/views/prior_authority/steps/alternative_quote_details/edit.html.erb, app/views/prior_authority/steps/delete_travel/edit.html.erb, app/views/prior_authority/steps/primary_quote_summary/_service_cost_subtable.html.erb, app/views/prior_authority/steps/primary_quote_summary/_travel_cost_subtable.html.erb, app/views/prior_authority/steps/service_cost/_items.html.erb, app/views/prior_authority/steps/service_cost/_time.html.erb, config/locales/en/prior_authority/alternative_quotes.yml, config/locales/en/prior_authority/steps.yml, spec/system/prior_authority/service_cost_spec.rb, spec/system/prior_authority/travel_detail_spec.rb, spec/system/support/prior_authority/step_helpers.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1625)
=> [CRM457-1625] CRM4 Provider: Amendments to service tables/ fields

config/gatekeeper_crm5.yml
=> test ALL crm5 onboarding

app/services/providers/gatekeeper.rb, spec/system/sign_in_spec.rb
=> hotfix inactive office code logic

config/gatekeeper_crm4.yml
test inactive code fix on prod with dummy user
=> remove dummy user from crm4

.github/actions/delete-dev-release/action.yml, app/services/app_store_client.rb, app/services/app_store_subscriber.rb, config/application.rb, lib/tasks/app_store.rake, spec/lib/tasks/app_store_unsubscribe_spec.rb, spec/services/app_store_client_spec.rb, spec/services/app_store_subscriber_spec.rb
Same as on caseworker
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1368)
=> CRM457-1368: Unsubscribe on close PR

app/controllers/prior_authority/downloads_controller.rb, spec/system/prior_authority/view_applications_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1744)
=> CRM457-1744: Allow downloading files with weird chars in them

config/gatekeeper_crm4.yml
Onboarding more providers for CRM4
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1762)
=> Onboard additional providers for CRM4 (TRANCHE 8)

app/models/supporting_document.rb, db/migrate/20240725152523_remove_active_storage_tables.rb, db/schema.rb, spec/controllers/nsm/steps/supporting_evidence_controller_spec.rb
Clear out redundant code
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1771)
=> CRM457-1771: Remove all vestigial activestorage stuff

README.md, helm_deploy/templates/_helpers.tpl, helm_deploy/templates/deployment-custom-errors.yaml, helm_deploy/templates/deployment-worker.yaml, helm_deploy/templates/deployment.yaml, helm_deploy/values-dev.yaml, helm_deploy/values-prod.yaml, helm_deploy/values-uat.yaml
[Check securityContext for all services](https://dsdmoj.atlassian.net/browse/CRM457-1547)
- Put Security Context default settings under a re-usable helper template
- Add information about the settings
=> Crm457 1547 security context cleanup

bin/deploy, helm_deploy/templates/deployment-custom-errors.yaml, helm_deploy/templates/deployment-worker.yaml, helm_deploy/templates/deployment.yaml
[Check securityContext for all services](https://dsdmoj.atlassian.net/browse/CRM457-1547)
Fix issues with indentation on deployment
=> Fix Security Context Issues

helm_deploy/templates/deployment-custom-errors.yaml, helm_deploy/templates/deployment-worker.yaml, helm_deploy/templates/deployment.yaml
Use template helper for security context
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1547)
fixed indentation issue
=> CRM457-1547: use template helper for security context

config/locales/en/errors.yml, config/locales/en/prior_authority/check_answers.yml, config/locales/en/prior_authority/steps.yml, spec/forms/nsm/steps/defendant_details_form_spec.rb, spec/forms/prior_authority/steps/case_detail/defendant_form_spec.rb, spec/forms/prior_authority/steps/case_detail_form_spec.rb, spec/system/prior_authority/case_detail_spec.rb, spec/system/prior_authority/check_your_answers/no_prison_law_spec.rb, spec/system/support/prior_authority/step_helpers.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1788)
=> CRM457-1788:  Change maat naming

app/views/nsm/steps/view_claim/_allowed_work_items.html.erb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1851)
=> [CRM457-1851] Don't show adjusted work items summary if no adjustments

config/locales/en/nsm/claims.yml, spec/presenters/nsm/check_answers/application_status_card_spec.rb
Fix capitalisation
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1804)
=> CRM457-1804: Fix case of status label

app/services/decisions/decision_tree.rb, spec/decisions/decision_tree_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1233)
=> CRM457-1233: Properly redirect after deleting a disbursement

app/presenters/nsm/check_answers/application_status_card.rb, spec/presenters/nsm/check_answers/application_status_card_spec.rb
Adjust the email for further information
Will also correspond with a govuk notify template change (see ticket for more info)
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1886)
=> CRM7: Adjust contact email for Further Information

config/locales/en/helpers.yml, spec/system/nsm/hearing_details/suggestion_autocomplete_spec.rb, spec/system/nsm/hearing_details_spec.rb
Change "last" to "first" in NSM hearing court question
Content error spotted by BA.
=> CRM457-1875: Change "last" to "first" in hearing court question

config/gatekeeper_crm7.yml
Also has the potential to enable the testing dummy office code.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1889)
=> CRM457-1889: Onboarding initial providers for CRM7

.rubocop_todo.yml, app/forms/nsm/steps/solicitor_declaration_form.rb, app/models/claim.rb, db/migrate/20240819104601_backfill_work_item_position.rb, db/schema.rb, spec/models/claim_spec.rb, spec/system/nsm/solicitor_declaration_spec.rb
Update work item positions on submission of NSM claim
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1812)
=> CMR457-1812: Update work item positions on submission of NSM claim

config/feature_flags.yml
=> UAT maintenance mode for DB upgrade

config/feature_flags.yml
Reverts ministryofjustice/laa-submit-crime-forms#1086
=> Revert "UAT maintenance mode for DB upgrade"

app/models/concerns/work_item_costs.rb, app/models/work_item.rb, app/presenters/nsm/allowed_work_items/summary_table.rb, app/presenters/nsm/allowed_work_items/table.rb, app/presenters/nsm/check_answers/cost_summary_card.rb, app/services/sorters/work_items_sorter.rb, app/views/nsm/steps/view_claim/_allowed_work_items.html.erb, app/views/nsm/steps/view_claim/_work_items.html.erb, app/views/nsm/steps/view_claim/work_item.html.erb, config/locales/en/nsm/steps/work_items.yml, config/locales/en/nsm/view_claim.yml, spec/presenters/nsm/allowed_work_items/summary_table_spec.rb, spec/presenters/nsm/allowed_work_items/table_spec.rb, spec/presenters/nsm/check_answers/cost_summary_card_spec.rb, spec/system/nsm/view_claim_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1879)
=> CRM457-1879: Adjust UI for work items with changed types

app/assets/stylesheets/custom/govuk-table.scss, app/assets/stylesheets/custom/govuk-width.scss, app/presenters/nsm/allowed_work_items/table.rb, spec/presenters/nsm/allowed_work_items/table_spec.rb
Previously applied a change to all cells that looked quite janky, instead take the opposite approach and only constrain this column for now.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1906)
=> CRM457-1906: Better isolate long-line table fix

app/views/nsm/steps/view_claim/_allowed_disbursements.html.erb, app/views/nsm/steps/view_claim/_disbursements.html.erb
Cost type shouldn't be a numeric column
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1923)
=> CRM457-1923: Fix incorrect numeric column

app/models/prior_authority_application.rb, app/presenters/prior_authority/check_answers/further_information_card.rb, app/presenters/prior_authority/check_answers/incorrect_information_card.rb, app/presenters/prior_authority/check_answers/report.rb, app/views/prior_authority/applications/response_summaries/_sent_back.html.erb, config/locales/en/prior_authority.yml, config/locales/en/prior_authority/check_answers.yml, spec/factories/incorrect_informations.rb, spec/presenters/prior_authority/check_answers/report_spec.rb, spec/services/submit_to_app_store/prior_authority_payload_builder_spec.rb, spec/system/prior_authority/check_your_answers/sent_back_for_further_info_spec.rb, spec/system/prior_authority/view_applications_spec.rb
Show more RFI info on application details page
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1554)
=> CRM457-1554: More FI details

app/controllers/healthcheck_controller.rb, config/environments/production.rb, config/initializers/lograge.rb, config/initializers/sentry.rb, config/routes.rb, helm_deploy/templates/deployment.yaml, spec/controllers/healthcheck_controller_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1864)
=> CRM457-1864: Wait for Clamby in check for readiness

config/notification_banner.yml, spec/lib/notification_banner_spec.rb
Add banner to dev and UAT too
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1910)
Inline with production
=> CRM457-1910: UAT and dev notification banner

config/notification_banner.yml
Correct banner message
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1910)
Using wrong date.
=> CRM457-1910: Correct banner message

config/notification_banner.yml
Tweak banner content inline with content design
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1910)
From content designer
=> CRM457-1910: Tweak banner content

.rubocop.yml, app/presenters/nsm/check_answers/application_status_card.rb, spec/presenters/nsm/check_answers/application_status_card_spec.rb
Also ignore some potentially massive folders that slow rubocop down.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1921)
=> CRM457-1921: Use correct links for adjustment review

spec/system/notification_banner_spec.rb
Add integration test for notification banner
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1910)
=> CRM457-1910: Add integration test for notification banner

config/feature_flags.yml
Enable maintenance mode on **PROD**
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1907)
For database upgrade.
=> CMR457-1907: Enable maintenance mode on production

config/feature_flags.yml
Reverts ministryofjustice/laa-submit-crime-forms#1114
=> Revert "CMR457-1907: Enable maintenance mode on production"

config/feature_flags.yml
=> Enable maintenance mode on UAT

config/feature_flags.yml
Reverts ministryofjustice/laa-submit-crime-forms#1134
=> Revert "Enable maintenance mode on UAT"

config/notification_banner.yml
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1907)
=> Add notification for Production DB Upgrade

config/gatekeeper_crm7.yml
Onboard tranche 3
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1915)
On 03/09/2024
=> CRM457-1915: Onboard tranche 3

app/views/nsm/claims/index.html.erb, app/views/prior_authority/applications/_drafts.html.erb, app/views/prior_authority/applications/index.html.erb, config/locales/en/nsm/claims.yml, config/locales/en/prior_authority.yml
Update tabs to sub-navigation & change the delete link to meet new a11y requirements.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1863)
=> CRM457-1863: Update tabs to sub-navigation

config/feature_flags.yml
Reverts ministryofjustice/laa-submit-crime-forms#1146
=> Revert "CRM457-1907: Enable maintenance mode on prod"

app/services/app_store_subscriber.rb, spec/services/app_store_subscriber_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1873)
=> CRM457-1873: Retry app store subscription

lib/tasks/fixes.rake
[Step 2: Fix Provider Mismatches](https://dsdmoj.atlassian.net/browse/CRM457-1966)
=> CRM457-1966: Fix Mismatched LAA References

app/views/nsm/steps/claim_confirmation/show.html.erb, config/locales/en/nsm/steps.yml
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1990)
=> [CRM457-1990] CRM7 Provider: Addition of print instructions on the Claim complete page

app/views/nsm/steps/claim_confirmation/show.html.erb, config/locales/en/nsm/steps.yml
Reverts ministryofjustice/laa-submit-crime-forms#1167 as Print functionality is not implemented yet.
=> Revert "[CRM457-1990] CRM7 Provider: Addition of print instructions on the Claim complete page"

app/controllers/nsm/steps/view_claim_controller.rb, app/presenters/nsm/check_answers/read_only_report.rb, spec/presenters/nsm/check_answers/read_only_report_spec.rb, spec/system/nsm/view_claim_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1976)
=> CRM457-1976: Remove cost summary from overview on view claim page

app/views/nsm/steps/case_disposal/edit.html.erb, app/views/nsm/steps/claim_type/edit.html.erb, app/views/nsm/steps/defendant_delete/edit.html.erb, app/views/nsm/steps/defendant_details/edit.html.erb, app/views/nsm/steps/defendant_summary/edit.html.erb, app/views/nsm/steps/disbursement_add/edit.html.erb, app/views/nsm/steps/disbursement_cost/edit.html.erb, app/views/nsm/steps/disbursement_delete/edit.html.erb, app/views/nsm/steps/equality/edit.html.erb, app/views/nsm/steps/equality_questions/edit.html.erb, app/views/nsm/steps/firm_details/edit.html.erb, app/views/nsm/steps/hearing_details/edit.html.erb, app/views/nsm/steps/letters_calls/edit.html.erb, app/views/nsm/steps/reason_for_claim/edit.html.erb, app/views/nsm/steps/work_item/edit.html.erb, app/views/nsm/steps/work_item_delete/edit.html.erb, app/views/prior_authority/steps/alternative_quotes/_last_quote_deleted.html.erb, app/views/prior_authority/steps/check_answers/edit.html.erb, app/views/prior_authority/steps/further_information/edit.html.erb
Make consistent on all form pages
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1989)
=> CRM457-1989: Always show error summary at top of page

app/forms/nsm/steps/disbursement_add_form.rb, config/locales/en/errors.yml, spec/system/nsm/disbursements_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2024)
=> CRM457-2024: Validate disbursement add screen

config/application.rb, config/initializers/devise.rb
And move setting to where we keep other hard-coded config
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1817)
=> CRM457-1817: Reduce idle timeout to 1 hour

helm_deploy/templates/ingress.yaml
=> CRM457-2069: Add exceptionAdd exception

config/database.yml, helm_deploy/templates/deployment-worker.yaml, helm_deploy/templates/deployment.yaml
Set full DB verify mode when using RDS.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1759)
=> CRM457-1759: DB SSL mode

app/models/claim.rb, spec/models/claim_spec.rb
If incomplete work item has no work type, do not break
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2100)
=> CRM457-2100: Fix sorting

Gemfile, Gemfile.lock, app/services/submit_to_app_store/prior_authority_payload_builder.rb, lib/tasks/submit_dummy_data.rake, lib/test_data/pa_resubmitter.rb, spec/factories/firm_offices.rb, spec/factories/prior_authority_application.rb, spec/factories/solicitors.rb, spec/lib/test_data/pa_resubmitter_spec.rb, spec/services/submit_to_app_store/prior_authority_payload_builder_spec.rb
And update test data to ensure that it's valid.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2096)
=> CRM457-2096: Validate data before submission

app/presenters/concerns/base_presentable.rb, app/presenters/concerns/further_information_presentable.rb, app/presenters/nsm/check_answers/application_status_card.rb, app/presenters/nsm/check_answers/base.rb, app/presenters/prior_authority/check_answers/base.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2004)
=> CRM457-2004: Include url helpers in presentable concern

app/forms/nsm/steps/solicitor_declaration_form.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2004)
[Slack Thread](https://mojdt.slack.com/archives/C034YPREUSF/p1728293648205059)
=> CRM457-2004: Ensure application is saved when provider is updating

Gemfile, Gemfile.lock, app/services/submit_to_app_store/nsm_payload_builder.rb, spec/factories/claims.rb, spec/factories/work_items.rb, spec/services/submit_to_app_store/nsm_payload_builder_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2129)
=> CRM457-2129: Use NSM schema validation

app/javascript/application.js, app/javascript/scrollable_pane.js, spec/javascript/scrollable_pane.spec.js
Fixes to JS script for scrollable-pane, So it only calls if scrollabe-pane element exists.
Further optimisation to the script and updates jest test
=> Scrollable-Pane- Fixes error when class doesn't exist

config/office_code_overrides.yml
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2178)
=> CRM457-2178 Marks office codes to active

app/assets/stylesheets/application.scss, app/assets/stylesheets/custom/search.scss, app/controllers/concerns/searchable.rb, app/controllers/nsm/claims_controller.rb, app/controllers/prior_authority/applications_controller.rb, app/forms/search_form.rb, app/javascript/application.js, app/javascript/date-picker.js, app/javascript/handle-forms.js, app/jobs/submit_to_app_store.rb, app/services/search_service.rb, app/services/submit_to_app_store/nsm_payload_builder.rb, app/views/layouts/nsm.html.erb, app/views/layouts/nsm/_primary_navigation.html.erb, app/views/nsm/claims/search.html.erb, config/locales/en/errors.yml, config/locales/en/nsm.yml, config/locales/en/nsm/search.yml, db/migrate/20241017140210_add_originally_submitted_at_to_submissions.rb, db/schema.rb, gems/laa_multi_step_forms/app/views/layouts/govuk_template.html.erb, spec/jobs/submit_to_app_store_spec.rb, spec/system/search_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2106)
=> CRM457-2106: NSM search

.github/workflows/update-virus-definitions.yml
Add missing checkout
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2168)
=> CRM457-2168: Fix ClamAV update run

app/forms/search_form.rb, app/views/layouts/prior_authority.html.erb, app/views/layouts/prior_authority/_primary_navigation.html.erb, app/views/nsm/claims/search.html.erb, app/views/prior_authority/applications/search.html.erb, app/views/shared/_search.html.erb, config/locales/en.yml, config/locales/en/nsm.yml, config/locales/en/nsm/search.yml, config/locales/en/prior_authority/search.yml, spec/system/search_spec.rb
Add UX for PA search and filter 
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2103)
no front page links to search as of yet so hit URL `/prior-authority/applications/search`
=> [CRM457-2103] PA Provider: Search and filter

app/helpers/tag_helper.rb, app/views/prior_authority/applications/search.html.erb, spec/system/search_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2239)
=> [CRM457-2239] fix draft pa search link

package.json, yarn.lock
Fixes https://security.snyk.io/vuln/SNYK-JS-CROSSSPAWN-8303230
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2251)
=> CRM457-2251: Resolve Snyk issue

app/views/errors/inactive_offices/index.html.erb, config/locales/en/errors.yml
Make it clearer how to action an inactive office code error.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1751)
=> CRM457-1751: Adjust inactive office code error

app/forms/nsm/steps/youth_court_claim_additional_fee_form.rb, app/views/nsm/steps/youth_court_claim_additional_fee/edit.html.erb, config/locales/en/errors.yml, db/migrate/20241125132952_rename_youth_court_claimed_column_in_claims.rb, db/pii.yml, db/schema.rb, spec/forms/nsm/steps/youth_court_claim_additional_fee_form_spec.rb, spec/services/submit_to_app_store/nsm_payload_builder_spec.rb, spec/system/nsm/youth_court_claim_additional_fee_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2290)
Needed so that we don't break the crime form common gem, [see conversation](https://mojdt.slack.com/archives/C05212WRK5J/p1732537649569579)
=> Crm457 2290: Rename youth court field

app/javascript/multi-file-upload.js
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2315)
=> CRM457-2315: JS can deal with errors that don't have message JSON

app/models/claim.rb, app/presenters/nsm/tasks/case_disposal.rb, spec/presenter/nsm/steps/case_disposal_presenter_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2288)
- Use correct criteria for path (only youth court fee cut off date affects the path to case category form)
- Use correct criteria for completed? (if claim is elligible for youth court fee, then the additional form should be included in whether section is completed or not)
=> CRM457-2288: Provider: Youth Court Fee Flow (Fix Task List Logic)

app/presenters/nsm/check_answers/read_only_report.rb, app/presenters/nsm/check_answers/report.rb
BOI claims don't have a rep_order_date, and checking for it has been
taken care of by other methods.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2288)
=> CRM457-2288: Correctly check for YCF flow directions

app/controllers/nsm/steps/case_outcome_controller.rb, app/forms/nsm/steps/claim_type_form.rb, app/models/claim.rb, app/presenters/nsm/check_answers/read_only_report.rb, app/presenters/nsm/check_answers/report.rb, app/presenters/nsm/tasks/case_disposal.rb, app/services/decisions/back_decision_tree.rb, app/services/decisions/decision_tree.rb, app/views/nsm/steps/case_category/edit.html.erb, app/views/nsm/steps/case_outcome/edit.html.erb, config/locales/en/errors.yml, spec/forms/nsm/steps/claim_type_form_spec.rb
Resolves all the issues locally that appear in the QA ticket.
As this is a QA ticket, there will be some inevitable back and forth as we try and verify the correct behaviours.
=> CRM457-2263: Resolve QA issues

app/models/claim.rb
=> CRM457-2263: Only NSM can claim the fee

app/views/nsm/steps/view_claim/_additional_fees.html.erb, config/locales/en/nsm/view_claim.yml, spec/system/nsm/view_claim_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2271)
[Addresses this comment](https://dsdmoj.atlassian.net/browse/CRM457-2271?focusedCommentId=538565)
=> Crm457 2271: Fix View Claim (Mary Feedback #1)

app/presenters/nsm/tasks/case_disposal.rb
=> CRM457-2263: Only NSM claims that should be able to claim the fee should handle it

config/feature_flags.yml
=> Turn on youth court

.env.test, app/controllers/concerns/claim_creatable.rb, app/controllers/nsm/claims_controller.rb, app/controllers/nsm/imports_controller.rb, app/forms/nsm/import_form.rb, app/presenters/app_store/v1/further_information.rb, app/presenters/app_store/v1/nsm/claim.rb, app/services/nsm/import_service.rb, app/views/nsm/claims/index.html.erb, app/views/nsm/imports/new.html.erb, config/feature_flags.yml, config/locales/en/nsm/claims.yml, config/locales/en/nsm/imports.yml, config/routes.rb, spec/fixtures/files/import_sample.xml, spec/fixtures/files/unreadable_import.xml, spec/system/nsm/import_spec.rb, spec/system/support/nsm/app_store_payload_helper.rb
Add a new form to upload an XML file and that, if the file contains disbursements and work items in the expected format, will create a new claim and import details from the file.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2203)
=> CRM457-2203: XML import

app/views/nsm/steps/solicitor_declaration/edit.html.erb, config/locales/en/nsm/steps.yml
See ticket for more context
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2294)
=> CRM457-2294: Remove incorrect warning

app/views/nsm/steps/view_claim/_adjustments.html.erb, app/views/nsm/steps/view_claim/_allowed_additional_fees.html.erb, app/views/nsm/steps/view_claim/additional_fees.html.erb, config/locales/en/nsm/view_claim.yml, spec/system/nsm/view_claim_spec.rb
- If an additional fee was adjusted, show the comment in the table
- If there were adjustments but not to additional fees, show the tab anyway
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2336)
=> CRM457-2336: Add in missing AC from QA

app/presenters/app_store/v1/supporting_document.rb, spec/system/prior_authority/view_applications_spec.rb
=> Use file_path instead of file_name for supporting documents

app/validators/email_format_validator.rb, spec/validators/email_format_validator_spec.rb
Prevent extra dots around the email and cleanup the test to be simpler
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2347)
=> CRM457-2347: Tighten the email regex

app/views/home/index.html.erb, config/locales/en/submit_a_crime_form.yml, gems/laa_multi_step_forms/config/locales/en/helpers.yml
Remove all textual and error mentions to eforms
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2188)
=> CRM457-2188: Remove previous mentions to eforms

app/views/nsm/steps/work_item_delete/edit.html.erb, config/locales/en/nsm/steps.yml
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2171)
=> [CRM457-2171] align delete work items with LAA design

app/models/firm_office.rb, app/models/prior_authority_application.rb, spec/system/prior_authority/delete_application_spec.rb
Missed as part of https://github.com/ministryofjustice/laa-submit-crime-forms/pull/1372
=> Allow PA applications to be removable again

app/models/solicitor.rb
Resolve production error raised in https://github.com/ministryofjustice/laa-submit-crime-forms/pull/1372
[Link to error](https://mojdt.slack.com/archives/C06UR7V28RZ/p1734949176347379?thread_ts=1734701126.774359&cid=C06UR7V28RZ)
=> Use correct model name for relationship

app/presenters/nsm/cost_summary/disbursements.rb, config/locales/en/nsm/summary.yml, spec/presenters/nsm/cost_summary/disbursements_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2307)
=> CRM457-2307: Add net, vat, total to disbursement cost summary

config/feature_flags.yml
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2262)
[Cleanup of old version code will be handled as a result of this spike](https://dsdmoj.atlassian.net/browse/CRM457-2363)
=> CRM457-2262: Enable new API in production

app/presenters/app_store/v1/prior_authority/quote.rb, spec/presenters/app_store/v1/prior_authority/quote_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2364)
=> CRM457-2364: Address Assessed Costs Not Being Multiplied by Cost Multiplier

app/views/nsm/claims/index.html.erb
add `import claim` button linking to MSForm survey
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2331)
=> [CRM457-2331] import claim form survey

config/application.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2321)
=> Adjust the technical support email

app/presenters/submission_list.rb, spec/presenters/nsm/check_answers/further_information_card_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2429)
=> [CRM457-2429] fix pagination results provider

app/services/nsm/importers/xml/v1/crm7_claim.xsd, app/services/nsm/importers/xml/v1/importer.rb, spec/fixtures/files/import_sample.xml, spec/fixtures/files/import_sample_with_missing_fields.xml, spec/services/nsm/importers/xml/v1/importer_spec.rb
Make relevant adjustments to remove fields deemed no longer needed.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2472)
=> CRM457-2472 XML Schema adjustments

app/controllers/nsm/imports_controller.rb, app/forms/nsm/import_form.rb, app/views/nsm/claims/index.html.erb, app/views/nsm/imports/new.html.erb, config/locales/en/nsm/imports.yml, spec/forms/nsm/import_form_spec.rb, spec/system/nsm/import_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2458)
=> CRM457-2458 Adds error message to Import a claim

app/controllers/nsm/imports_controller.rb, spec/system/nsm/import_spec.rb
Set the default for import_date when importing a claim
[Link to relevant discussion](https://mojdt.slack.com/archives/C034YPREUSF/p1744042231496459)
=> Set the import date for XML Imports

app/services/nsm/importers/xml/v1/crm7_claim.xsd
[Link to relevant discussion](https://mojdt.slack.com/archives/C05212WRK5J/p1746007398578389)
=> Update comments to reflect time_spent is minutes not seconds

Procfile.dev, README.md
Add a little note about setting up debugging and making it easier to turn on/off
[Link to relevant discussion](https://mojdt.slack.com/archives/C05212WRK5J/p1746618129624309)
=> Enable debugging setup

helm_deploy/templates/ingress.yaml
We think this is too high now, so we're going to lower it to something
more realistic.
=> Reduce anomaly threshold

helm_deploy/values-prod.yaml, helm_deploy/values-uat.yaml
[Link to relevant discussion](https://mojdt.slack.com/archives/C7KCVJZSQ/p1747668816365949)
=> Add a permanent redirect to landing page

config/application.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2593)
=> CRM457-2593 update email domain

helm_deploy/templates/_helpers.tpl, helm_deploy/values-uat.yaml
Update the IP whitelist for UAT
=> Update the IP whitelist for UAT

Dockerfile
Use a Wayback mirror of the alpine packages GPG key
=> Use a mirror for the alpine packages key

app/controllers/nsm/imports_controller.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2576)
linked to https://github.com/ministryofjustice/laa-crime-application-store/pull/415
=> CRM457-2576 add error_type to xml import errors

app/forms/nsm/steps/defendant_details_form.rb, app/forms/prior_authority/steps/case_detail/defendant_form.rb, app/validators/maat_validator.rb, spec/forms/nsm/steps/defendant_details_form_spec.rb, spec/forms/prior_authority/steps/case_detail/defendant_form_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2672)
=> Respond to emergency legislation

helm_deploy/templates/deployment-clamav.yaml
Need to get deployments up and running, related ticket can be backlogged.
=> Revert clamav changes

config/feature_flags.yml
UAT should have the correct data in place, and we've been promised Production will too
=> Enable the PDA check in environments that should support it

app/views/layouts/_footer_links.html.erb, config/application.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2292)
=> Add link to join research panel

.circleci/config.yml
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2477)
=> Adjust plan to run deploy steps after tests

db/migrate/20250805120900_remove_laa_reference.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2704)
[Thread](https://mojdt.slack.com/archives/C034YPREUSF/p1755855318680329)
=> CRM457-2704: Force Cascade Deletion on Laa Reference to Remove Virtual Search Columns

bin/deploy
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2374)
=> CRM457-2374: Switch To Bitnami Legacy Image for Redis & Postgres Charts

config/office_code_overrides.yml
=> Remove office code for UAT testing

config/office_code_overrides.yml
=> revert office code addition

app/controllers/application_controller.rb, spec/system/maintenance_mode_spec.rb
Should resolve edge case issues & prevent the need to update for BST later
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2742)
=> Use timezoned time for checking business hours

.github/dependabot.yml
Ignore a package that has a lot of issues until we can resolve it in the linked ticket.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2751)
=> Ignore package until we can upgrade

app/models/provider.rb
Should resolve a [Sentry issue](https://mojdt.slack.com/archives/C06UR7V28RZ/p1759398527819859)
=> Allow from_omniauth to update users
