ministryofjustice/laa-submit-crime-forms

.github/dependabot.yml
Adds dependabot to the repo to ensure dependencies are kept upto date
N/A
This mirrors the config for [Court Data UI](https://github.com/ministryofjustice/laa-court-data-ui/blob/main/.github/dependabot.yml)
N/A
N/A
N/A
This will kick off post merge
=> Add dependabot scanning to repo

.rubocop.yml, app/forms/steps/letters_calls_form.rb, app/forms/steps/work_item_form.rb, app/value_objects/work_types.rb, app/views/steps/letters_calls/edit.html.erb, app/views/steps/work_item/edit.html.erb, spec/rails_helper.rb, spec/steps/letters_calls/form_spec.rb, spec/steps/letters_calls/integration_spec.rb, spec/steps/work_items/add/form_spec.rb, spec/steps/work_items/integration_spec.rb
Add conditional criteria for Work Item types and uplift in the various screens
https://dsdmoj.atlassian.net/browse/CRM457-146
This does not stop data corrupt that can occur as a result of modifying flags after work items have been created.
=> [Crm457 146] hide workflow item type

kubectl_deploy/deployment.tpl
Adds ENV to the deployment file and sets it to Development
[CRM457-97](https://dsdmoj.atlassian.net/browse/CRM457-97)
This has been manually deployed to dev for testing
Banner should be available on navigating to the page
[CRM457-97]: https://dsdmoj.atlassian.net/browse/CRM457-97?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRM457-97 - Update env var for banner

.gitignore, app/views/home/index.en.html.erb, config/locales/en/home.yml
Content changes according to the latest design change.
[START PAGE: Iterate the Claim a non-standard mags payment page](https://dsdmoj.atlassian.net/browse/CRM457-167)
In the dev environment, this page is currently the same as Crime Apply’s start page. This is incorrect, and needs to be changed to the NSM one.
- Build the page as shown in the screenshot
- Comes from clicking “Claim a non-standard mags court payment” link on the LAA online portal AND come from clicking on “back” in the “Your claims” page
- IF user clicks on “Start no” it goes to “Your claims” page
- IF user clicks on “back” button, THEN user lands on LAA online portal landing page
- IF user clicks on “claim for CCCD” THEN user lands on CCCD landing page
- IF user click on “Contracted work and administration” THEN user …
=> [CRM457-167] START PAGE: Iterate the Claim a non-standard mags payment page

.github/workflows/test-build-deploy.yml, Dockerfile, app/controllers/healthcheck_controller.rb, config/initializers/sentry.rb, config/routes.rb, spec/controllers/healthcheck_controller_spec.rb
- Add ping endpoint to application to view app details
[CRM457-242](https://dsdmoj.atlassian.net/browse/CRM457-242)
Implementing to assist with debugging issues
Navigate to /ping on the application
[CRM457-242]: https://dsdmoj.atlassian.net/browse/CRM457-242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRM457-242 - Add ping endpoint to application

.github/workflows/test-build-deploy-main.yml, .github/workflows/test-build-deploy-pr.yml
- Docker build in PR uses event references
- Prod build pulls right branch name
=> Fix references in build

app/controllers/steps/work_item_controller.rb, app/views/steps/work_items/edit.html.erb, config/locales/en/steps.yml, config/routes.rb, db/schema.rb, gems/laa_multi_step_forms/.rubocop.yml, gems/laa_multi_step_forms/app/lib/route_helpers.rb, gems/laa_multi_step_forms/spec/dummy/app/controllers/steps/claim_type_controller.rb, gems/laa_multi_step_forms/spec/dummy/app/controllers/steps/defendant_controller.rb, gems/laa_multi_step_forms/spec/dummy/app/controllers/steps/start_page_controller.rb, gems/laa_multi_step_forms/spec/dummy/app/controllers/steps/work_item_controller.rb, gems/laa_multi_step_forms/spec/dummy/config/routes.rb, gems/laa_multi_step_forms/spec/lib/routes_helpers_spec.rb, spec/steps/work_items/add/controller_spec.rb, spec/steps/work_items/integration_spec.rb
Add duplicate functionality for work items
https://dsdmoj.atlassian.net/browse/CRM457-207
This also moves the RouteHelpers module into the gem
=> Enable duplicate button on work items

app/assets/stylesheets/application.scss, app/controllers/steps/claim_confirmation_controller.rb, app/presenters/tasks/claim_confirmation.rb, app/services/decisions/simple_decision_tree.rb, app/views/steps/claim_confirmation/show.html.erb, config/locales/en/claims.yml, config/locales/en/steps.yml, config/routes.rb, gems/laa_multi_step_forms/config/locales/en/helpers.yml, spec/decisions/simple_decision_tree_spec.rb, spec/steps/claim_confirmation/controller_spec.rb, spec/steps/claim_confirmation/integration_spec.rb, spec/steps/claim_confirmation/presenter_spec.rb
This is the page on the form that allows a user to be assured that they have submitted their claim.
[CLAIM COMPLETE: Build page](https://dsdmoj.atlassian.net/browse/CRM457-214)
=> [CRM457-214] Claim complete step

helm_deploy/values-dev.yaml, helm_deploy/values-prod.yaml, helm_deploy/values-uat.yaml
Up all envs to 500MB memory limit in helm chart
[Intermittent Gateway Issues
](https://dsdmoj.atlassian.net/browse/CRM457-238)
=> Up all envs to 500MB memory limit

app/forms/steps/letters_calls_form.rb, gems/laa_multi_step_forms/app/controllers/steps/base_step_controller.rb, gems/laa_multi_step_forms/spec/controllers/steps/base_step_controller_spec.rb, spec/steps/letters_calls/integration_spec.rb
So we have two ways to build the form object, either directly from the `new` method or using the `build` method.. when using the build method the record is set to the application if it is not passed in. This change replicates that when building the form in the update path of the controller
https://dsdmoj.atlassian.net/browse/CRM457-272
=> Build form in the same way as the .build method

app/views/steps/claim_details/edit.html.erb, config/locales/en/helpers.yml, spec/steps/claim_details/integration_spec.rb
This fixes the styling issues in Claim details step based on Figma file.
[Fix font size on the Claim details step](https://dsdmoj.atlassian.net/browse/CRM457-274)
**Before**
**Now**
=> [CRM457-274] Fix font size on the Claim details step

app/forms/steps/letters_calls_form.rb, app/lib/pricing.rb, app/presenters/cost_summary/letters_calls.rb, app/presenters/cost_summary/work_items.rb, app/views/steps/letters_calls/edit.html.erb, config/locales/en/helpers.yml, config/locales/en/steps.yml, config/pricing.yml, spec/lib/pricing_spec.rb, spec/presenters/cost_summary/work_items_spec.rb, spec/steps/cost_summary/integration_spec.rb, spec/steps/letters_calls/form_spec.rb
Make letters and calls options
Small UI fixes 
* align letters and calls page with design
* use `£0.00` instead of `£` in cost summary
https://dsdmoj.atlassian.net/browse/CRM457-268
=> Make letters and calls optional

app/assets/stylesheets/custom/task_list.scss
Add custom css to set padding-left to 0 for task-list__items
Align all lines to the left in "start a new claim" page
=> Align all lines to the left in "start a new claim" page

app/presenters/check_answers/claim_type_card.rb, app/presenters/check_answers/report.rb, config/locales/en/check_answers.yml, spec/factories/claims.rb, spec/presenters/check_answers/claim_type_card_spec.rb
Adds the high level details card for a claim
[CRM457-437](https://dsdmoj.atlassian.net/browse/CRM457-437)
[CRM457-437]: https://dsdmoj.atlassian.net/browse/CRM457-437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRM457-437 - Add details card

app/forms/steps/answer_equality_form.rb, db/migrate/20230920054312_add_equality_answer.rb, db/schema.rb, spec/services/notify_app_store/message_builder_spec.rb, spec/steps/equality/form_spec.rb
- Adds the answer_equality field to the database
[CRM457-403](https://dsdmoj.atlassian.net/browse/CRM457-403)
[CRM457-403]: https://dsdmoj.atlassian.net/browse/CRM457-403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRM457-403 Add answer_equality to DB

app/controllers/steps/start_page_controller.rb, app/controllers/steps/view_claim_controller.rb, app/presenters/check_answers/report.rb, app/views/claims/index.html.erb, app/views/steps/view_claim/show.html.erb, config/locales/en/steps.yml, config/routes.rb, spec/factories/claims.rb, spec/presenters/check_answers/report_spec.rb, spec/steps/start_page/controller_spec.rb, spec/steps/view_claim/controller_spec.rb
- Add readonly view logic into start page controller
- Adds readonly view step
- Utilise and update tests on existing report functions
- Remove ability to change the items
[CRM457-531](https://dsdmoj.atlassian.net/browse/CRM457-531)
[CRM457-531]: https://dsdmoj.atlassian.net/browse/CRM457-531?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRM457-531 - Adds readonly view for submitted claims

app/services/risk_assessment/risk_assessment_scorer.rb, spec/services/risk_assessment/risk_assessment_scorer_spec.rb
- Change risk levels to be string instead of dict
- Update tests
[CRM457-644](https://dsdmoj.atlassian.net/browse/CRM457-644)
[CRM457-644]: https://dsdmoj.atlassian.net/browse/CRM457-644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRM457-644 - Risk out to be string

app/services/notify_app_store/message_builder.rb, spec/factories/claims.rb, spec/factories/supporting_evidence.rb, spec/services/notify_app_store/message_builder_spec.rb
- Adds supporting evidence to the outputted message
- Updates the tests
Test should show output, otherwise JSON can be intercepted or viewed by sending to appstore locally
=> CRM457-645 - Add supporting evidence to outputted message

gems/laa_multi_step_forms/app/views/layouts/_header_navigation.html.erb, gems/laa_multi_step_forms/app/views/layouts/application.html.erb
- Update header to link to root if unauthenticated or claims if authenticated
- Remove your applications as per design
- Fix the sign out button
=> CRM457-645 - Update header to meet designs

.rubocop.yml, Gemfile, Gemfile.lock, app/controllers/about/cookies_controller.rb, app/controllers/application_controller.rb, app/controllers/concerns/cookie_concern.rb, app/javascript/application.js, app/models/cookie.rb, app/views/about/cookies/index.html.erb, app/views/shared/_flash_banner.html.erb, config/application.rb, config/locales/en/cookies.yml, config/routes.rb, gems/laa_multi_step_forms/app/views/layouts/_analytics.html.erb, gems/laa_multi_step_forms/app/views/layouts/_footer_links.html.erb, gems/laa_multi_step_forms/app/views/layouts/application.html.erb, gems/laa_multi_step_forms/app/views/layouts/cookie_banner/_hide.html.erb, gems/laa_multi_step_forms/app/views/layouts/cookie_banner/_main.html.erb, gems/laa_multi_step_forms/app/views/layouts/cookie_banner/_success.html.erb, gems/laa_multi_step_forms/app/views/layouts/govuk_template.html.erb, spec/controllers/about/cookie_controller_spec.rb, spec/controllers/concern/cookie_concern_spec.rb, spec/system/disbursement_type/suggestion_autocomplete_spec.rb, spec/system/hearing_details/suggestion_autocomplete_spec.rb
- Adds Turbo for inline cookie banner interactivity (This is opt-in to not break existing functionality
- Adds cookie banner with translation files
- Adds cookie concern to support
- Add partial for Google Analytics
- Adds and updates tests
First view of website will display cookie banner until accepted/rejected. To view again delete cookies
=> CRM457-645 - Add Cookie Banner

app/forms/steps/disbursement_cost_form.rb, app/services/notify_app_store/message_builder.rb, spec/factories/disbursements.rb, spec/services/notify_app_store/message_builder_spec.rb, spec/steps/cost_summary/integration_spec.rb
- Save apply_vat flag and return
- return float and not string for values
[CRM457-675](https://dsdmoj.atlassian.net/browse/CRM457-675)
[CRM457-675]: https://dsdmoj.atlassian.net/browse/CRM457-675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRM457-675 - Update disbursement types for output

app/views/steps/equality/edit.html.erb, config/locales/en/helpers.yml, config/locales/en/steps.yml, helm_deploy/templates/deployment-worker.yaml, helm_deploy/templates/deployment.yaml
- Fix disbursements page title that was missing
- Fix Equality page layout to match figma
- Add missing hint text
[Content change for Prior Authority](https://dsdmoj.atlassian.net/browse/CRM457-691)
[Complete following content changes (provider)](https://dsdmoj.atlassian.net/browse/CRM457-689)
=> CRM457-695 - update interface

Procfile.dev, app/models/claim.rb, app/presenters/check_answers/application_status_card.rb, app/presenters/check_answers/read_only_report.rb, config/locales/en/check_answers.yml, config/locales/en/claims.yml, spec/factories/claims.rb, spec/presenters/check_answers/application_status_card_spec.rb, spec/presenters/check_answers/read_only_report_spec.rb, spec/services/notify_app_store/message_builder_spec.rb
- Update status' to match list we have
- Add Status card to view only report
- Update claims page to use all status'
- Update tests
[Update statuses when a claim/answer is returned](https://dsdmoj.atlassian.net/browse/CRM457-687)
Testing was done against a local env as we may not have the data in the pre-production environments just yet. This has been signed off by PM/DM
=> CRM457-687 - Update and add Status card

app/models/matter_type.rb, app/models/outcome_code.rb
Referencing Memo can and will cause nil error. Referencing method is safer and works
=> CRM457-546 - Dont reference memo

app/controllers/steps/letters_calls_controller.rb, app/controllers/steps/work_item_controller.rb, app/views/steps/letters_calls/edit.html.erb, app/views/steps/work_item/edit.html.erb, config/locales/en/errors.yml, config/locales/en/steps.yml, spec/steps/claim_details/integration_spec.rb, spec/steps/letters_calls/integration_spec.rb, spec/steps/work_items/add/controller_spec.rb, spec/steps/work_items/integration_spec.rb, spec/support/steps/a_generic_step_controller.rb
- Updates error message for adding VAT registered
- Adds VAT message to Work items page
- Adds VAT message to Letters and Calls page
- Updates tests
[CRM457-784](https://dsdmoj.atlassian.net/browse/CRM457-784)
[CRM457-784]: https://dsdmoj.atlassian.net/browse/CRM457-784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRM457-784 - Add Vat message to work items and letters/calls

app/controllers/steps/cost_summary_controller.rb, app/forms/steps/disbursement_cost_form.rb, app/forms/steps/letters_calls_form.rb, app/presenters/check_answers/disbursement_costs_card.rb, app/presenters/check_answers/letters_calls_card.rb, app/presenters/check_answers/work_items_card.rb, app/presenters/cost_summary/base.rb, app/presenters/cost_summary/disbursements.rb, app/presenters/cost_summary/letters_calls.rb, app/presenters/cost_summary/report.rb, app/presenters/cost_summary/work_items.rb, app/views/steps/cost_summary/show.html.erb, config/locales/en/check_answers.yml, config/locales/en/steps.yml, config/locales/en/summary.yml, spec/presenters/check_answers/disbursement_cost_card_spec.rb, spec/presenters/cost_summary/disbursements_spec.rb, spec/presenters/cost_summary/letters_and_calls_spec.rb, spec/presenters/cost_summary/report_spec.rb, spec/presenters/cost_summary/work_items_spec.rb, spec/steps/cost_summary/controller_spec.rb, spec/steps/cost_summary/integration_spec.rb, spec/steps/disbursements/integration_spec.rb
- Refactor to put vat code in common location
- Add VAT rows to cost summary
- Update tests
[CRM457-783](https://dsdmoj.atlassian.net/browse/CRM457-783)
[CRM457-783]: https://dsdmoj.atlassian.net/browse/CRM457-783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRM457-783 - Add VAT values to Cost Summary

app/forms/steps/letters_calls_form.rb, app/presenters/check_answers/base.rb, app/presenters/check_answers/disbursement_costs_card.rb, app/presenters/check_answers/letters_calls_card.rb, app/presenters/check_answers/work_items_card.rb, app/presenters/cost_summary/base.rb, app/presenters/cost_summary/disbursements.rb, app/presenters/cost_summary/letters_calls.rb, app/presenters/cost_summary/report.rb, app/presenters/cost_summary/work_items.rb, app/views/steps/cost_summary/show.html.erb, config/locales/en/check_answers.yml, config/locales/en/summary.yml, spec/presenters/check_answers/disbursement_cost_card_spec.rb, spec/presenters/cost_summary/letters_and_calls_spec.rb, spec/presenters/cost_summary/report_spec.rb, spec/presenters/cost_summary/work_items_spec.rb, spec/steps/cost_summary/integration_spec.rb
- Fix cost summary page to not always show/work out VAT
- Format Disbursement total to be bold
- Refactor some code
[CRM457-783](https://dsdmoj.atlassian.net/browse/CRM457-783)
[CRM457-783]: https://dsdmoj.atlassian.net/browse/CRM457-783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRM783 - Fix Cost Summary page

app/mailers/claim_submission_mailer.rb, spec/factories/claims.rb, spec/mailers/claim_submission_mailer_spec.rb
- Adds conditional so send Maat or CNTP depending on the claim type
[CRM457-865](https://dsdmoj.atlassian.net/browse/CRM457-865)
Limitations within the notify service means that conditionals and optional content is not easy within the template and thus i have opted to do this within the code itself. 
[CRM457-865]: https://dsdmoj.atlassian.net/browse/CRM457-865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRM457-865 - Add CNTP number to submitted email

helm_deploy/templates/deployment.yaml
CRM457-774: Workaround for Puma/k8s dropped request problem
Possible cause of bug [CRM457-774](https://dsdmoj.atlassian.net/browse/CRM457-774) in assess app
but a good practice to avoid dropping requests anyway.
See: https://github.com/puma/puma/blob/master/docs/kubernetes.md#running-puma-in-kubernetes
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-774)
As long as config is parseable and we can deploy there is not much more we can test
[CRM457-774]: https://dsdmoj.atlassian.net/browse/CRM457-774?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRM457-774: Workaround for Puma/k8s dropped request problem

.circleci/config.yml, Gemfile, Gemfile.lock, spec/spec_helper.rb
Output rspec results on CI and store coverage artifact
So we can see rspec failures on CI and store
coverage results for our perusal.
Came out of work on [CRM457-869](https://dsdmoj.atlassian.net/browse/CRM457-869) when trying to check coverage
You can see the coverage in the artifact tab on Circle CI. Just click coverage/index.html
**Failing test now visible**
**Coverage artifact available**
[CRM457-869]: https://dsdmoj.atlassian.net/browse/CRM457-869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Output rspec results on CI and store coverage artifact

.circleci/config.yml, gems/laa_multi_step_forms/Gemfile, gems/laa_multi_step_forms/Gemfile.lock, gems/laa_multi_step_forms/spec/dummy/app/controllers/steps/downloadable_entity_controller.rb, gems/laa_multi_step_forms/spec/dummy/config/routes.rb, gems/laa_multi_step_forms/spec/helpers/application_helper_spec.rb, gems/laa_multi_step_forms/spec/lib/routes_helpers_spec.rb, gems/laa_multi_step_forms/spec/value_objects/value_object_spec.rb
* Fixed broken specs in multi-stage form gem
* Got branch coverage up to 100%
* Added multi-stage form gem specs to CI so we notice if they break again.
[JIRA](https://dsdmoj.atlassian.net/browse/CRM457-946)
* I had to add the 'pg' gem as a dependency to the Gemfile because the tests specify dummy models that inherit from ActiveRecord::Base, and RSpec throws a wobbly on CI without a database adapter
* The dummy router used in the tests has one of most types of custom routing steps; all it was missing was an upload step
N/A
N/A
=> CRM457-946: multi stage form specs

config/initializers/omniauth.rb
Add omniauth logging and silence test output
without this the omniauth logs will got to STDOUT
and, for testing, that means we pollute the test output.
Example test output without this
```sh
E, [2024-01-22T12:54:47.079992 #66377] ERROR -- omniauth: (saml) Authentication failure! StandardError: StandardError, StandardError
```
=> Add omniauth logging and silence test output

.overcommit.yml, Gemfile, Gemfile.lock
Add overcommit and have it run rubocop pre-commit
You can choose to activate it locally or not
```sh
bundle install
overcommit --install
```
Currently it will only run rubocop and commit message linting before any commit. You can prevent it doing so on a per commit basis even when activate using...
```sh
git commit -n ...
```
when changes are made to the `.overcommit.yml` by yourself
or another dev (which you then pull locally) you may be prompted
to "sign" the changes. This is expected behaviour.
```sh
overcommit --sign
```
=> Add overcommit with rubocop

config/locales/en.yml, gems/laa_multi_step_forms/app/helpers/laa_multi_step_forms/application_helper.rb, gems/laa_multi_step_forms/app/views/layouts/_phase_banner.html.erb, gems/laa_multi_step_forms/config/locales/en/layouts.yml, gems/laa_multi_step_forms/spec/helpers/application_helper_spec.rb
Use govuk_phase_banner component
Simplify the partial to use the govuk-component
libraries phase banner component. For brevity and to
delegate styling out to this well maintained gem.
=> Use govuk_phase_banner component

app/controllers/prior_authority/steps/authority_value_controller.rb, app/forms/prior_authority/steps/authority_value_form.rb, app/views/prior_authority/applications/offboard.html.erb, config/locales/en/errors.yml, config/locales/en/prior_authority.yml, spec/forms/prior_authority/steps/authority_value_form_spec.rb, spec/forms/prior_authority/steps/client_detail_form_spec.rb, spec/system/prior_authority/authority_value_spec.rb, spec/system/prior_authority/client_detail_spec.rb, spec/system/prior_authority/create_application_spec.rb
Amend error messages inline with designs
- Authority value: Conditional error message for authority value
based on the preceding prison law matter question.
- Client details: more customised date errors inline with designs
Also, 
- Amend conditional offboarding page content depending on prison law matter answer (see  [CRM457-973](https://dsdmoj.atlassian.net/browse/CRM457-973))
Error messages taken from [this spreadsheet](https://docs.google.com/spreadsheets/d/1p79PoMhECgMiCDB_qQGTvCALflGjiHMDnPNA8n7mtcc/edit#gid=1083653105) that is attached to this ticket [CRM457-975](https://dsdmoj.atlassian.net/browse/CRM457-975)
[CRM457-975]: https://dsdmoj.atlassian.net/browse/CRM457-975?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CRM457-973]: …
=> CRM457-975: Prior authority error message updates

config/locales/en/errors.yml
Tweak error messages as per the [spreadsheet](https://docs.google.com/spreadsheets/d/1p79PoMhECgMiCDB_qQGTvCALflGjiHMDnPNA8n7mtcc/edit#gid=1083653105)
https://dsdmoj.atlassian.net/browse/CRM457-981
The vast majority of the work for this ticket was already done.
The switch of database model from prior_authority_application fields to defendants fields is self-contained in #458
We can't do the 'check answers' flow specified on the ticket because we don't have a check answers screen yet, but that mechanism, when it exists, should automatically work for this screen.
So the only thing left to do on the ticket as far as I can see is these tiny tweaks to the error messages.
=> CRM457-981: Client details

app/javascript/file-upload.js
Only display the delete link once the file has fully uploaded to stop clicking prior to file being present
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1083)
This does not include testing
=> [CRM457-1083] Only display the Delete link after fully uploaded

app/forms/prior_authority/steps/primary_quote_form.rb, spec/forms/prior_authority/steps/primary_quote_form_spec.rb
The bug was that if you type a value into the service cost but don't click on a pre-selected option, the hidden field value doesn't update, and we were giving priority to the hidden field over the text field. Fixing this means that users aren't forced to click for a change to 'take'
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1015)
=> CRM457-1015: Give priority to text field rather than hidden select

app/mailers/claim_submission_mailer.rb, app/presenters/nsm/check_answers/application_status_card.rb, app/presenters/nsm/check_answers/case_details_card.rb, app/presenters/nsm/check_answers/case_disposal_card.rb, app/presenters/nsm/check_answers/claim_details_card.rb, app/presenters/nsm/check_answers/claim_justification_card.rb, app/presenters/nsm/check_answers/claim_type_card.rb, app/presenters/nsm/check_answers/hearing_details_card.rb, app/views/nsm/claims/index.html.erb, app/views/prior_authority/applications/frame_contents/_assessed.html.erb, app/views/prior_authority/applications/frame_contents/_draft.html.erb, app/views/prior_authority/applications/frame_contents/_submitted.html.erb, config/initializers/time_formats.rb, spec/mailers/claim_submission_mailer_spec.rb, spec/presenters/nsm/check_answers/claim_type_card_spec.rb
Add shared date and time formats and use
[came out of ](https://dsdmoj.atlassian.net/browse/CRM457-979)
There are multiple locations where the date format
`'%d %B %Y'` is used. Adding and using a shared format
date/time  stamp is something rails provides and can help to ensure
consistency, as well as the potential for simple amendment.
```rb
\# instead of
my_date.strftime('%d %B %Y')
\# use
my_date.to_fs(:stamp)
```
This has only be used to apply the format in the multiple
places that the `'%d %B %Y'` date/time format is already used. 
There are no performance benefits to my knowledge, just consistency.
=> Add shared date and time formats and use

app/presenters/nsm/start_page.rb, app/presenters/prior_authority/start_page.rb, config/locales/en/tasklist.yml
Namespace tasklist section headers
[Came out of ticket](https://dsdmoj.atlassian.net/browse/CRM457-979)
To provide consistency with prior authority and,specifically, namespaced translation lookup for NSM
and PA applications and allow use of the same header
sub-key if desired.
=> crm457-979: namespace tasklist section headers

app/controllers/prior_authority/steps/base_controller.rb, spec/system/prior_authority/task_list_spec.rb, spec/system/support/prior_authority/step_helpers.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1040)
Previously if you completed steps A and B then went back and edited step A, step B would be marked as 'not started'. Which would be extra problematic if step B came before step A in the task list.
As we have our own logic for determining where changes in A invalidate step B, the simplest thing is to simply remove the 'prune' mechanism that's causing the app to forget about previous interactions.
=> CRM457-1040: Fix bug in navigation stack logic

app/forms/prior_authority/steps/case_detail/defendant_form.rb, config/locales/en/errors.yml, spec/forms/prior_authority/steps/case_detail/defendant_form_spec.rb, spec/forms/prior_authority/steps/case_detail_form_spec.rb
Add MAAT number format validation
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-978)
Must only be digits.  Error message inline with
designs.
[errors spreadsheet](https://docs.google.com/spreadsheets/d/1p79PoMhECgMiCDB_qQGTvCALflGjiHMDnPNA8n7mtcc/edit#gid=1083653105)
=> CRM457-978: Add MAAT number format validation

app/presenters/prior_authority/check_answers/alternative_quotes_card.rb, config/locales/en/prior_authority/check_answers.yml, spec/presenters/prior_authority/check_answers/alternative_quotes_card_spec.rb, spec/system/prior_authority/check_your_answers/no_prison_law_spec.rb
Add index number (1 based) to quote row in alternative quotes summary card of CYA page
The prototype numbers the alternate quotes output on the CYA page.
=> CRM457-979: Add index to alt quote card

app/presenters/nsm/check_answers/report.rb, app/presenters/prior_authority/check_answers/base.rb, app/presenters/prior_authority/check_answers/primary_quote_card.rb, app/presenters/prior_authority/check_answers/report.rb, app/presenters/prior_authority/check_answers/ufn_card.rb, config/locales/en/generic.yml, spec/presenters/prior_authority/check_answers/ufn_card_spec.rb
Refactor CYA report and card objects and enable row actions
The Change action links in the card "header" are the responsibility
of the individual card objects rather than the report object.
One card, Application details, should not have this link on
the header but on the Ufn row instead, according to designs
and, by moving the responsibility to the card object, this
becomes easy.
In addition, the govuk_summary_list accepts an ` actions:` key
on the individual rows so we use this to add a link to a specifc
row (UFN).
=> CRM457-979: Move `actions` header resposibility to cards and add row actions capability

app/controllers/prior_authority/steps/base_controller.rb, app/controllers/prior_authority/steps/check_answers_controller.rb, app/controllers/prior_authority/steps/submission_confirmation_controller.rb, app/forms/prior_authority/steps/check_answers_form.rb, app/presenters/prior_authority/check_answers/primary_quote_card.rb, app/services/decisions/decision_tree.rb, app/services/submit_to_app_store/prior_authority_payload_builder.rb, app/views/prior_authority/steps/check_answers/edit.html.erb, app/views/prior_authority/steps/primary_quote_summary/_service_cost_card.html.erb, app/views/prior_authority/steps/submission_confirmation/show.html.erb, config/locales/en/errors.yml, config/locales/en/prior_authority/check_answers.yml, config/locales/en/prior_authority/steps.yml, config/routes.rb, db/migrate/20240216084333_add_confirmations_to_prior_authority_applications.rb, db/schema.rb, gems/laa_multi_step_forms/config/locales/en/helpers.yml, spec/factories/prior_authority_application.rb, spec/forms/prior_authority/steps/check_answers_form_spec.rb, spec/presenters/prior_authority/check_answers/primary_quote_card_spec.rb, spec/services/submit_to_app_store/prior_authority_payload_builder_spec.rb, spec/system/prior_authority/check_your_answers/no_prison_law_spec.rb, spec/system/prior_authority/check_your_answers/prison_law_spec.rb, spec/system/prior_authority/check_your_answers/submission_spec.rb, spec/system/prior_authority/primary_quote_spec.rb, spec/system/support/prior_authority/step_helpers.rb
Add confirmations to check your answers page
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1132)
This adds the confirmations that must be accepted by the provider before they submit the application. Once accepted and form submitted the application is updated to the submitted status and the check you answers page, and all other editable form pages, can no longer be reached, preventing double submission or post submission data updates.
=> CRM457-1132: Add confirmations to check your answers

app/presenters/prior_authority/check_answers/primary_quote_card.rb, spec/presenters/prior_authority/check_answers/primary_quote_card_spec.rb
Do not display travel cost reason on CYA for prison law matters
Prison law matters do not required the provider to answer
the question of whether the client is detained nor provide
a reason for travel if they are not detained.
=> CRM457-979: Do not display travel cost reason on CYA for prison law matters

.circleci/config.yml
[DEV - Setup New Kubernetes Namespaces for Provider App](https://dsdmoj.atlassian.net/browse/CRM457-940)
This allows a push to dev with the new repo name, other environments are pending
=> Update Circle CI Contexts to Correct Name

app/forms/prior_authority/steps/hearing_detail_form.rb, spec/forms/prior_authority/steps/hearing_detail_form_spec.rb, spec/system/prior_authority/hearing_details_spec.rb
Make date o fnext hearing optional
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-978)
For non-prison law matters the date of next hearing
does not need to be provided.
Raised during QA as missing.
=> CRM457-978: Make date of next hearing optional

app/forms/prior_authority/steps/hearing_detail_form.rb, app/views/prior_authority/steps/hearing_detail/edit.html.erb, config/locales/en/errors.yml, config/locales/en/prior_authority/steps.yml, spec/forms/prior_authority/steps/hearing_detail_form_spec.rb, spec/forms/prior_authority/steps/next_hearing_form_spec.rb, spec/system/prior_authority/hearing_details_spec.rb, spec/system/support/prior_authority/step_helpers.rb
Add question for optional next hearing date - non-prison law
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1156)
An additional question has been added to designs
for the user to answer whether they have a next hearing
date or not before entering the date, if Yes selected.
=> CRM457-1156: optional next hearing date - non-prison law

app/presenters/prior_authority/check_answers/base.rb, app/presenters/prior_authority/check_answers/primary_quote_card.rb, app/presenters/prior_authority/check_answers/reason_why_card.rb, spec/presenters/prior_authority/check_answers/primary_quote_card_spec.rb, spec/presenters/prior_authority/check_answers/reason_why_card_spec.rb, spec/system/prior_authority/check_your_answers/no_prison_law_spec.rb
Replace linebreaks in and sanitize text fields
Request from designer as helps readability.
Plus necessary to do anyway to sanitize
the content.
=> Replace linebreaks in, and sanitize, text fields

config/locales/en/errors.yml, spec/forms/prior_authority/steps/hearing_detail_form_spec.rb, spec/forms/prior_authority/steps/next_hearing_form_spec.rb, spec/system/prior_authority/hearing_details_spec.rb, spec/system/prior_authority/next_hearing_spec.rb
Add custom next_hearing_date error messages
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1156)
tweaks from QA
=> CRM457-1156: Add custom next_hearing_date error messages

app/services/submit_to_app_store/prior_authority_payload_builder.rb, spec/services/submit_to_app_store/prior_authority_payload_builder_spec.rb
A typo meant we weren't sending the optional 'rep_order_date' field to the app store
=> BUG: Fix field missing from payload

app/presenters/prior_authority/check_answers/hearing_detail_card.rb, spec/presenters/prior_authority/check_answers/hearing_detail_card_spec.rb
CRM457-1156: Add display logic for next hearing date
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1156)
Not considered in previous work in this ticket. This
prevents errors when trying to display non-existent
next_hearing_date values and duplicates the display
logic for this field in the prison law flow which, in turn, 
is inline with changes to the field itself.
=> CRM457-1156: Add display logic for next hearing date

helm_deploy/templates/deployment-worker.yaml, helm_deploy/templates/deployment.yaml
Add container `securityContext` to all containers
To handle deployment warnings:
```
W0226 09:28:18.411693     351 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "laa-claim-non-standard-magistrate-fee-backend-worker" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "laa-claim-non-standard-magistrate-fee-backend-worker" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "laa-claim-non-standard-magistrate-fee-backend-worker" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "laa-claim-non-standard-magistrate-fee-backend-worker" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
W0226 …
```
=> Add container `securityContext` to all containers

app/forms/prior_authority/steps/alternative_quotes/detail_form.rb, app/forms/prior_authority/steps/primary_quote_form.rb, app/forms/prior_authority/steps/quote_cost_form.rb, app/forms/prior_authority/steps/service_cost_form.rb, app/lib/prior_authority/service_type_rule.rb, app/value_objects/prior_authority/quote_services.rb, app/views/prior_authority/steps/primary_quote_summary/_travel_cost_card.html.erb, config/locales/en/helpers.yml, config/locales/en/prior_authority/steps.yml, spec/forms/prior_authority/steps/alternative_quotes/detail_form_spec.rb, spec/forms/prior_authority/steps/primary_quote_form_spec.rb, spec/system/prior_authority/service_cost_spec.rb
When the service type changes, we don't want irrelevant previously-entered values to stick around. So we do more resetting of attributes on quote cost forms and the primary quote form
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-977)
=> CRM457-977: Primary quote QA fixes

.github/dependabot.yml
- Updates come in weekly
- They're fully grouped (we're going to try this, and whenever there's a broken or high-risk update we'll manually pull that out separately. If we end up doing that more times than not, we'll default to _not_ grouping)
[CRM457-1147](https://dsdmoj.atlassian.net/browse/CRM457-1147)
[CRM457-1147]: https://dsdmoj.atlassian.net/browse/CRM457-1147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRM457-1147: Change dependabot cadence

gems/laa_multi_step_forms/Gemfile.lock, gems/laa_multi_step_forms/config/locales/en/helpers.yml, gems/laa_multi_step_forms/spec/helpers/application_helper_spec.rb, spec/presenters/nsm/check_answers/claim_details_card_spec.rb
Change format period inline with prototype/designs
[link to ticket](https://dsdmoj.atlassian.net/browse/CRM457-1204)
[came out of ticket](https://dsdmoj.atlassian.net/browse/CRM457-992)
[and ticket](https://dsdmoj.atlassian.net/browse/CRM457-1115)
Came out of conversation with content and design who decided
that a consistent approach across NSM and PA on both caseworker
and provider app is preferred and should be
- full word for hours and minutes, lower case
- no leading zeros
=> CRM457-992: Change format period inline with prototype designs

app/services/decisions/back_decision_tree.rb, app/views/prior_authority/steps/ufn/edit.html.erb, spec/system/prior_authority/authority_value_spec.rb, spec/system/prior_authority/check_your_answers/submission_spec.rb, spec/system/prior_authority/ufn_spec.rb
Fixes from QA feedback on CYA page
- Correct back button on CYA page, to go to taslklist/start_page
- Correct UFN page back button
> What is your unique file number? - we removed the back button from here as it went ‘Back’ to the initial questions that cannot be amended. However, I think we need it back in for consistency. If it is the CYA loop it would go to the CYA page. If it is from the Task List (My app progress) it would return to the Task List page. If it is the intial create app flow then back to the previous form...
=> CRM457-979: Correct back button on CYA/UFN pages

config/routes.rb
The app was set up so that in develop/test you got a lovely pretty error message when page was not found, but in production you got the ugly rails default. I'm assuming the intention was the opposite of that.
=> Fix error page config

app/presenters/nsm/check_answers/base.rb, app/presenters/nsm/check_answers/defendant_card.rb, config/locales/en/nsm/check_answers.yml, spec/presenters/nsm/check_answers/defendant_card_spec.rb
The 'check answers' screen for NSM was showing 'incomplete' for defendants because the card expected a "full_name" field and the model only had "first_name" and "last_name" (and the test strategy is so heavily dependent on unit tests that mock everything they interact with that this mismatch wasn't shown up). This fixes the card.
For bonus points, it adds a more thorough workaround and documentation for the bug where the check answers screen explodes in dev because things that are not translation keys are being passed round as translation keys.
=> Add workaround to missing translation issue and fix defendant card

.circleci/config.yml
Because the old ones use a deprecated image that is subject to brownouts
=> Bump AWS orbs

app/controllers/home_controller.rb, app/services/providers/gatekeeper.rb, app/views/home/index.en.html.erb, config/gatekeeper.yml, spec/factories/providers.rb, spec/system/access_spec.rb
Only show links on start page if a provider can access them.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1214)
=> CRM457-1214: Check gatekeeper when displaying start page links

app/services/submit_to_app_store/prior_authority_payload_builder.rb, spec/forms/prior_authority/steps/check_answers_form_spec.rb, spec/services/submit_to_app_store/prior_authority_payload_builder_spec.rb
Remove convenience attributes firm_name and client_name from PA payload
[Related to ticket](https://dsdmoj.atlassian.net/browse/CRM457-993)
The client name and firm_name are already available in the payload
nested under defendant and firm_office respecctively. The caseworker app
can locate and use them there. removing them from the payload creates
a single flexible source of truth for these details.
This came out of [PR for related applications in Assess](https://github.com/ministryofjustice/laa-assess-crime-forms/pull/341) and was
agreed on by patrick and joel as a way forward.
=> CRM457-993: Remove convenience attributes from PA payload

app/forms/prior_authority/quote_cost_validations.rb, app/validators/item_type_dependant_validator.rb, config/locales/en/errors.yml, config/locales/en/prior_authority/alternative_quotes.yml, spec/factories/prior_authority_application.rb, spec/factories/quote.rb, spec/system/prior_authority/alternative_quotes_spec.rb, spec/system/prior_authority/service_cost_spec.rb, spec/validators/item_type_dependant_validator_spec.rb
Add item cost error messages
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-992)
Inline designs/content for error messages and QA feedback. This can/ should also be applied to provider
Reference:
see [assess PR](https://github.com/ministryofjustice/laa-assess-crime-forms/pull/347)
=> CRM457-992: Add custom item type specific cost error messages

.circleci/config.yml
Move docker image scan to run in parallel to tests
To reduce the time overhead since the scan takes as long or longer
than the test suite run.
This is inline with [assess pipeline changes](https://github.com/ministryofjustice/laa-assess-crime-forms/pull/354)
=> Move docker image scan to run in parrallel to tests

.circleci/config.yml
Automate deployment to prod for main
Until we go to private beta, and perhaps even after that,
we might as well deploy to UAT and then production automatically.
This will:
- expose any deployment issues immediatley on a per merge basis
- not incur overhead of devs remebering to deploy
=> Automate deployment to prod for main

app/mailers/prior_authority/submission_mailer.rb, spec/mailers/prior_authority/submission_mailer_spec.rb
Correct recipient for submitted notification
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1102)
Although a provider will be associated with an application
they also specify a case contact per application. This contact
should be used for notification purposes related to the case.
=> CRM457-1102: Correct recipient for submitted notification

app/services/submit_to_app_store/nsm_payload_builder.rb, spec/services/submit_to_app_store/nsm_payload_builder_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1044)
We've decided to bite the bullet and _just_ send separate names rather than send separate and combined names.
=> CRM457-1044: Send NSM defendant names separately

app/mailers/nsm/submission_mailer.rb, app/mailers/prior_authority/submission_mailer.rb, spec/mailers/nsm/submission_mailer_spec.rb, spec/mailers/prior_authority/submission_mailer_spec.rb
Remove feedback URL from submission mailer
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1033)
Inline with UCD discussion it was decided to remove feedback
links from notification emails sent by the service.
The template has been edited on notify and no longer uses it.
=> CRM457-1033: Remove feedback URL from submission mailer

.env.development, Procfile.dev, config/initializers/sidekiq.rb
Do not inline sidekiq for bin/dev
So it behaves as a hosted environments sidekiq worker
as expected and stats are updated.
without this the job will be processed inline with the side
effect that stats on the webui are not updated.
=> Do not inline sidekiq for bin/dev

app/models/claim.rb, db/migrate/20240322122517_standardise_claim_statuses.rb, db/schema.rb, spec/controllers/nsm/steps/start_page_controller_spec.rb
Use more sensible name for submitted applications
Use the correct (caseworker-assigned) name for part_grant applications
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1270)
=> CRM457-1270: Use better status values

app/controllers/prior_authority/applications_controller.rb, app/helpers/application_helper.rb, app/helpers/tag_helper.rb, app/models/prior_authority_application.rb, app/services/prior_authority/assessment_syncer.rb, app/views/prior_authority/applications/assessed.html.erb, app/views/prior_authority/applications/frame_contents/_reviewed.html.erb, app/views/prior_authority/applications/index.html.erb, app/views/prior_authority/applications/response_summaries/_assessed.html.erb, app/views/prior_authority/applications/response_summaries/_expired.html.erb, app/views/prior_authority/applications/reviewed.html.erb, app/views/prior_authority/applications/show.html.erb, app/views/prior_authority/applications/state_summaries/_expired.html.erb, config/initializers/time_formats.rb, config/locales/en/prior_authority.yml, config/routes.rb, db/migrate/20240322141829_add_resubmission_dates_to_prior_authority_application.rb, db/schema.rb, spec/helpers/application_helper_spec.rb, spec/presenters/nsm/check_answers/application_status_card_spec.rb, spec/presenters/nsm/check_answers/case_details_card_spec.rb, spec/presenters/nsm/check_answers/case_disposal_card_spec.rb, spec/presenters/nsm/check_answers/claim_details_card_spec.rb, spec/presenters/nsm/check_answers/claim_justification_card_spec.rb, spec/presenters/nsm/check_answers/claim_type_card_spec.rb, spec/presenters/nsm/check_answers/hearing_details_card_spec.rb, spec/presenters/prior_authority/check_answers/client_detail_card_spec.rb, spec/services/prior_authority/assessment_syncer_spec.rb, spec/system/prior_authority/application_lists_spec.rb, spec/system/prior_authority/view_assessed_applications_spec.rb
Pull timings of resubmission window from payload
Sort out application show page for expired applications
Rename 'Assessed' to 'Reviewed' and include expired applications
Update date format to match designs (no leading zero on day)
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1239)
---
=> CRM457-1239: Show expired applications (and fix date format)

app/forms/prior_authority/steps/check_answers_form.rb, app/models/prior_authority_application.rb, app/presenters/tasks/generic.rb, app/services/prior_authority/last_update_finder.rb, app/views/prior_authority/steps/check_answers/edit.html.erb, config/locales/en/errors.yml, config/locales/en/prior_authority/check_answers.yml, db/migrate/20240326074226_drop_confirmations_from_prior_authority_application.rb, db/schema.rb, spec/factories/prior_authority_application.rb, spec/factories/supporting_documents.rb, spec/forms/prior_authority/steps/check_answers_form_spec.rb, spec/services/prior_authority/last_update_finder_spec.rb, spec/services/submit_to_app_store/nsm_payload_builder_spec.rb, spec/system/prior_authority/check_your_answers/sent_back_spec.rb
Add incorrect info text and error to check your answers
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1193)
Display the incorrect info comments for sent back statuses and error if no
changes made to the application before submission.
This also removes the persisted confirmations table columns in favour of virtual attributes
because they would otherwise need resetting as part of the assessment sync for sent back
events. Their removal makes this redundant and handles similar possible situations for
other status changes requiring resubmission.
**Text**
**Error**
=> CRM457-1193: Add incorrect info review summary

app/services/providers/gatekeeper.rb, spec/services/providers/gatekeeper_spec.rb
We weren't handling unrecognised office codes when a particular service was specified.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1277)
=> CRM457-1277: Handle unrecognised office codes

app/services/prior_authority/assessment_syncer.rb, spec/jobs/pull_updates_spec.rb
Ensure PAA assessment sync errors do not block pull updates
I noticed when working on other tickets when erroneous data
on one application was causing the pull updates to fail
and not update unbroken applications.
To safe gaurd against this scenario once live some error
handling and an "integration" spec has been added.
=> Ensure PAA assessment sync errors do not block pull updates

config/environments/development.rb
So that e2e tests, which specify a hostname, can use development mode easily.
=> Stop restricting hosts in development mode

app/views/prior_authority/steps/alternative_quotes/_with_alternative_quotes.html.erb
Error summaries typically go above the header, so this makes the alternative quotes screen do that.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1188)
=> CRM457-1188: Move error summary

config/locales/en/errors.yml, spec/forms/prior_authority/steps/hearing_detail_form_spec.rb
Added generic error message fallbacks for all date-specific error fields
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1200)
=> CRM457-1200: Add fallback translation for all date validation errors

Gemfile, Gemfile.lock, app/models/application_record.rb, spec/factories/claims.rb, spec/factories/defendants.rb, spec/factories/disbursements.rb, spec/factories/work_items.rb, spec/mailers/nsm/submission_mailer_spec.rb, spec/mailers/prior_authority/submission_mailer_spec.rb, spec/presenters/nsm/check_answers/case_details_card_spec.rb, spec/presenters/nsm/check_answers/claim_type_card_spec.rb, spec/presenters/nsm/check_answers/hearing_details_card_spec.rb, spec/services/submit_to_app_store/nsm_payload_builder_spec.rb, spec/services/submit_to_app_store/prior_authority_payload_builder_spec.rb, spec/support/json_checker.rb
Split this to a separate PR to merge quicker
Randomise the data that is produced for the tests, this will allow reuse of the Factories to create the performance testing data
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1281)
=> Crm457 1281/randomise test data

app/services/app_store_token_provider.rb, docs/development-e2e-setup.md, helm_deploy/templates/deployment-worker.yaml, helm_deploy/templates/deployment.yaml
##
[CRM457-1287](https://dsdmoj.atlassian.net/browse/CRM457-1287)
Previously the provider application was using credentials and secrets from the app store azure registration to verify it's identity with the app store.
It _should_ have been using it's own client registration. As can be seen in the [example documentation](https://intility.github.io/fastapi-azure-auth/usage-and-faq/calling_your_apis_from_python#single--and-multi-tenant), the scope uses a different client_id. 
Doing it this way will also allow us to use different roles for provider and caseworker once they have been implemented by Azure.
https://portal.azure.com/#view/Microsoft_AAD_RegisteredApps/ApplicationsListBlade
Two new azure registrations has been created for the provider application. …
=> Crm457 1287 update azure authentication

app/views/nsm/steps/case_details/edit.html.erb, app/views/nsm/steps/case_disposal/edit.html.erb, app/views/nsm/steps/claim_details/edit.html.erb, app/views/nsm/steps/claim_type/edit.html.erb, app/views/nsm/steps/disbursement_type/edit.html.erb, app/views/nsm/steps/hearing_details/edit.html.erb, app/views/nsm/steps/reason_for_claim/edit.html.erb, app/views/nsm/steps/work_item/edit.html.erb, app/views/prior_authority/steps/case_detail/edit.html.erb, app/views/prior_authority/steps/client_detail/edit.html.erb, app/views/prior_authority/steps/hearing_detail/edit.html.erb, app/views/prior_authority/steps/next_hearing/edit.html.erb, gems/laa_multi_step_forms/.rubocop.yml, gems/laa_multi_step_forms/app/attributes/type/multiparam_date.rb, gems/laa_multi_step_forms/app/helpers/laa_multi_step_forms/form_builder_helper.rb, gems/laa_multi_step_forms/app/lib/govuk_design_system_formbuilder/elements/fully_validatable_date.rb, gems/laa_multi_step_forms/docs/Validations.md, gems/laa_multi_step_forms/spec/attributes/type/multiparam_date_spec.rb, gems/laa_multi_step_forms/spec/lib/govuk_design_system_formbuilder/builder/fully_validatable_date_spec.rb, spec/system/prior_authority/client_detail_spec.rb
If someone puts 'banana' into the month part of a date field, we shouldn't pre-populate the field with `0` when we re-render the form - we should pre-populate it with 'banana'. Same as we do with `gbp` and `fully_validatable_integer` fields.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1173)
=> CRM457-1173: Stop casting date inputs to integers automatically

app/forms/nsm/steps/solicitor_declaration_form.rb
In production, SubmitToAppStore happens async, so the user is never notified of any errors. And there is no UI to notify users of any errors. But in any mode where sidekiq is run inline, any errors in SubmitToAppStore cause it to return a `nil`, meaning the SolicitorDeclarationForm acts as though `persist` has failed, so you can never get _past_ the solicitor declaration form. This is neither helpful not true to production. So this PR makes sure that, since we don't have a sensible user journey if `persist` fails, we don't send users down that journey. (It also means that for E2E tests we can actually _reach_ the final screen despite not having a valid GovUK Notify API key).
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1303)
=> CRM457-1303: Mark persist as having succeeded

app/services/app_store_client.rb, app/services/app_store_token_authenticator.rb, config/environments/development.rb, config/puma.rb, spec/requests/sync_spec.rb, spec/services/app_store_client_spec.rb
- It's ok if we're in a non-auth environment if the app store webhook URL doesn't have a bearer token
- If we don't provide a bearer token, use a fallback header to tell the app store our role
- Allow launching the app in puma cluster mode so that if needed we can have multiple workers to avoid logjams where a request triggers a synchronous webhook callback that can't be processed.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1327)
=> CRM457-1327: Allow bypassing sync authentication to enable e2e tests

app/lib/cost_calculator.rb, spec/lib/cost_calculator_spec.rb
Change VAT calculation logic to match clarified requirements
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1229)
I've followed the changes as listed in the ticket - removing a `round` and a `floor` in individual work item pricing calculations, changing a `floor` to a `round` in disbursement VAT calculations, and finally removing a redundant `round` in disbursement total summing.
=> CRM457-1229: VAT calculations

helm_deploy/values-uat.yaml
[Update network policies so that Provider application talks to datastore via Cloud Platform rather than via an external url](https://dsdmoj.atlassian.net/browse/CRM457-1288)
This is just for the UAT env to use the local domain so ingress can be disabled in UAT also for an environment matching production more
=> Use Local App Store URL - UAT

app/forms/prior_authority/steps/check_answers_form.rb, app/services/submit_to_app_store/prior_authority_payload_builder.rb, spec/services/submit_to_app_store/prior_authority_payload_builder_spec.rb
- Ensure we don't mark `provider_updated` submissions as `submitted`
- Remove a rogue `s` from a payload key
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1012)
=> CRM457-1012: Fix payload structure

.env.development, Procfile.dev
Add envars needed for local integration
This is one way of replicating a production like
integration of assess with app store inline with pub/sub
change.
=> Add envars needed for local integration

app/controllers/sync_controller.rb, app/services/app_store_update_processor.rb, app/services/prior_authority/assessment_syncer.rb, spec/jobs/pull_updates_spec.rb, spec/requests/sync_spec.rb, spec/services/app_store_client_spec.rb, spec/services/app_store_update_processor_spec.rb, spec/services/prior_authority/assessment_syncer_spec.rb
- When doing a batch sync, use the full payload that's available from the get-go
- When doing an individual sync, use the data posted by the app store
=> Make fewer requests to the app store

app/controllers/concerns/add_another_methods.rb, app/controllers/prior_authority/steps/travel_detail_controller.rb, app/forms/nsm/steps/letters_calls_form.rb, app/forms/nsm/steps/work_item_form.rb, app/views/nsm/steps/letters_calls/edit.html.erb, app/views/nsm/steps/work_item/edit.html.erb, config/locales/en/errors.yml, gems/laa_multi_step_forms/Gemfile.lock, gems/laa_multi_step_forms/app/controllers/steps/base_step_controller.rb, gems/laa_multi_step_forms/spec/controllers/steps/base_step_controller_spec.rb, gems/laa_multi_step_forms/spec/dummy/app/controllers/dummy_step_controller.rb, spec/forms/nsm/steps/letters_calls_form_spec.rb, spec/forms/nsm/steps/work_items_add_form_spec.rb, spec/system/nsm/letters_calls_spec.rb, spec/system/nsm/work_items_spec.rb
- Switch from a 'save_and_refresh' to a 'reload' on click on 'Update calculation' for pages with uplift values
- Change the 'reload' behaviour to validate the form so that when the page is re-rendered it displays any validation errors (but will still update the calculation if it can)
- Add the missing error messaging
- Adjust the minimum uplift threshold from 0 to 1 to match the error messaging
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-750)
=> CRM457-750: Add validation to uplift 'Update calculation' buttons

app/forms/nsm/steps/work_item_form.rb, spec/forms/nsm/steps/work_items_add_form_spec.rb
If you save a work item that is eligible for uplift, but don't apply an uplift, it gets saved to the database with a zero uplift. But then the dodgy form logic decides to say that that uplift _has_ been applied - an uplift of zero. And that's now invalid.
This PR changes the form logic so that if a work item is eligible for uplift and what has been saved is zero, it now correctly interprets that as uplift _not_ having been applied, which is a valid state.
=> Stop treating work items as invalid if uplift allowed but not applied

helm_deploy/templates/ingress.yaml
Internal testers routinely hit anomaly scores of 5, whatever that means. Let's set the anomaly score threshold to 6, which is what the caseworker app has.
=> 6 is the magic number

helm_deploy/templates/hpa-worker.yaml, helm_deploy/templates/hpa.yaml, helm_deploy/values-dev.yaml, helm_deploy/values-prod.yaml, helm_deploy/values-uat.yaml
Add horizontal pod autoscaler (HPA) config
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1455)
To handle scaling up./down based on CPU and
memory usage.
Needs to go in after the following cloud platform PRs, which add the necessary serviceaccount permissions
https://github.com/ministryofjustice/cloud-platform-environments/pull/22941
https://github.com/ministryofjustice/cloud-platform-environments/pull/22942
https://github.com/ministryofjustice/cloud-platform-environments/pull/22943
=> CRM457-1455: Add horizontal pod autoscaler (HPA) config

app/value_objects/prior_authority/quote_services.rb, config/locales/en/helpers.yml
Remove planning expert from list of services
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1404)
Request from BA inline with updated services list
=> CRM457-1404: Remove planning expert from list of services

app/views/nsm/steps/office_code/edit.html.erb, app/views/prior_authority/steps/additional_costs/edit.html.erb, app/views/prior_authority/steps/alternative_quotes/_no_alternative_quotes.html.erb, app/views/prior_authority/steps/alternative_quotes/_with_alternative_quotes.html.erb, app/views/prior_authority/steps/office_code/edit.html.erb, app/views/prior_authority/steps/service_cost/edit.html.erb
All radios vertical, with yes before no (and redundant 'inline' config removed)
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1437)
=> CRM457-1437: All radios vertical, with yes before no

app/forms/prior_authority/steps/alternative_quotes/detail_form.rb, spec/forms/prior_authority/steps/alternative_quotes/detail_form_spec.rb, spec/presenters/prior_authority/check_answers/alternative_quotes_card_spec.rb, spec/system/prior_authority/alternative_quotes_spec.rb, spec/system/support/prior_authority/step_helpers.rb
When service has variable cost type, alternative quotes always take the user-chosen cost type from the primary quote.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1387)
=> CRM457-1387: Cost type is never variable for alternative quotes

app/forms/nsm/steps/firm_details/solicitor_form.rb, config/locales/en/errors.yml, spec/forms/nsm/steps/firm_details/solicitor_form_spec.rb
We infer the alternate contact details value from the presence of conditionally revealed details when the page is first loaded. But when the page has not previously been saved, the absence of contact details should cause the radio to be unselected. This PR does that.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1401)
=> CRM457-1401: Stop preselecting radio button

.circleci/config.yml, .snyk
Add .snyk file for vulnerability ignores
The webui ignore mechanism does not appear to be working
plus this mechanism makes it simpler to manage in any event.
You can install the snyk cli locally following this
https://docs.snyk.io/snyk-cli/install-or-update-the-snyk-cli
or just `brew install snyk-cli`
See [how to create a snyk file locally](https://docs.snyk.io/manage-risk/prioritize-your-issues/the-.snyk-file)
TL;DR:
This command was run to generate a .snyk file to ignore this problematic vulnerability
```sh
snyk ignore --id=SNYK-JS-BRACES-6838727 --reason="no fix; no-impact" --expiry=2099-01-01
````
=> Add snyk ignores to codebase

app/forms/prior_authority/steps/hearing_detail_form.rb, app/forms/prior_authority/steps/next_hearing_form.rb, config/locales/en/errors.yml, gems/laa_multi_step_forms/app/forms/steps/base_form_object.rb, gems/laa_multi_step_forms/spec/forms/steps/base_form_object_spec.rb, spec/factories/prior_authority_application.rb, spec/forms/prior_authority/steps/hearing_detail_form_spec.rb, spec/forms/prior_authority/steps/next_hearing_form_spec.rb
Ensure next hearing is in the future the first time entered, but not unless changed thereafter
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1432)
Bug raised by manual testing. Prior authority must be sought for hearings
that are yet to occur.
=> CRM457-1432: Validate next hearing date to NOT be in past

app/presenters/nsm/supporting_evidence/check_list.rb, app/views/nsm/steps/claim_details/edit.html.erb, app/views/nsm/steps/supporting_evidence/_content.html.erb, config/locales/en/helpers.yml, config/locales/en/nsm/steps.yml, spec/presenters/nsm/supporting_evidence/check_list_spec.rb, spec/system/nsm/supporting_evidence_spec.rb
Add conditional supporting evidence upload help text
[Relates to bug ticket](https://dsdmoj.atlassian.net/browse/CRM457-1232)
[Link to feature ticket](https://dsdmoj.atlassian.net/browse/CRM457-1429)
To apply conditional logic to the individual checklist items
and the upload instructions it has been separated it out to a
presenter like object.
=> CRM457-1429: Add presenter for supporting evidence checkList

config/inactive_offices.yml
Mark test user's office as inactive/dead
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1414)
=> Mark test user's office as inactive/dead

app/services/risk_assessment/high_risk_assessment.rb, app/services/risk_assessment/low_risk_assessment.rb, spec/services/risk_assessment/high_risk_assessment_spec.rb, spec/services/risk_assessment/low_risk_assessment_spec.rb, spec/services/risk_assessment/risk_assessment_scorer_spec.rb
The `uplift_applied?` method checks if any work item has a positive uplift.
currently it uses `filter_map` to extract the `uplift` of each work item, and checks if any of them are positive. 
Issue is if uplift is 0, `any?` returns true and all of our application was being assessed as High Risk.
Added `positive?` method to check if a number is greater than 0. So, method is only returns true if uplift is more than 0.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-752)
Tested with Paper form PP2 that had initial assessment of Low risk from Caseworker.
**Current Dev env - Wrong assessment**
Current fixed env - Correct assessment
=> CRM457-1450: RBBA Bug Fix

app/forms/nsm/steps/claim_details_form.rb, app/presenters/nsm/check_answers/claim_details_card.rb, app/presenters/nsm/supporting_evidence/check_list.rb, config/locales/en/errors.yml, config/locales/en/helpers.yml, config/locales/en/nsm/check_answers.yml, config/locales/en/nsm/steps.yml, db/migrate/20240517122619_add_wasted_costs_to_claims.rb, db/schema.rb, spec/factories/claims.rb, spec/forms/nsm/steps/claim_details_form_spec.rb, spec/presenters/nsm/check_answers/claim_details_card_spec.rb, spec/presenters/nsm/supporting_evidence/check_list_spec.rb, spec/services/submit_to_app_store/nsm_payload_builder_spec.rb, spec/system/nsm/claim_details_spec.rb, spec/system/nsm/supporting_evidence_spec.rb
Add wasted costs to NSM claims
[Link to claim details form wasted costs ticket](https://dsdmoj.atlassian.net/browse/CRM457-1464)
[Link to supporting evidence wasted costs ticket](https://dsdmoj.atlassian.net/browse/CRM457-1501)
https://github.com/ministryofjustice/nsm-e2e-test/pull/83
=> CRM457-1464: Add wasted costs to NSM

app/forms/nsm/steps/disbursement_cost_form.rb, app/forms/nsm/steps/letters_calls_form.rb, app/forms/nsm/steps/work_item_form.rb, app/lib/pricing.rb, app/models/claim.rb, app/services/submit_to_app_store/nsm_payload_builder.rb, spec/presenters/nsm/cost_summary/summary_spec.rb
Stop using floats to represent money in as many places as possible
When we need to hold onto a value that could be an infinite-digit fraction of a penny (e.g. 0.33333333333), represent it as a Rational rather than a BigDecimal to avoid imprecision errors
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1067)
=> CRM457-1067: Reduce rounding error issues

app/views/nsm/steps/view_claim/work_items.html.erb, spec/system/nsm/view_claim_spec.rb
When we started paginating work items, the work item summary started only summarising the current page of work items. 
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1522)
=> CRM457-1522: Fix pagination breaking aggregation

app/controllers/nsm/claims_controller.rb, app/views/nsm/claims/index.html.erb, config/locales/en/nsm/claims.yml, spec/factories/claims.rb, spec/factories/defendants.rb, spec/system/nsm/claims_list_spec.rb
Add sorting to your claims page
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1424)
This follows the basic pattern from prior
authority.
=> CRM457-1424: Add sorting to your claims page

.snyk, package.json, yarn.lock
Bump braces 3.0.3
- Bump braces 3.0.2 to 3.0.3
- Remove snyk ignore
This should fix the CVE we currently ignore
If Snyk scan passes when the specific CVE is unignored then it is good to go
=> bump braces 3.0.3

config/feature_flags.yml
Disable mock portal auth on UAT
For parity with production and to enable debugging
of any portal login issues on a pre-prod environment.
=> Disable mock portal auth in UAT

app/controllers/prior_authority/steps/office_code_controller.rb, spec/system/prior_authority/case_contact_spec.rb
Fix account number select page "Save and come back later"
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1550)
PA controllers need to specify an after_commit_redirect_path
to overide redirect in shared base controller.
=> CMR457-1550: Fix account number select page "Save and come back later"

app/models/supported_file_types.rb
Allow text/rtf mime types for upload
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1535)
`application/rtf` and `text/rtf` are both valid mime types
for RTF so allow both so RTF files can be uploaded as
supporting evidence.
There is a sample RTF file on the ticket which can be used to test on primary quote page for CRM4
=> CRM457-1535: Allow text/rtf mime types for upload

app/forms/prior_authority/steps/case_detail_form.rb, app/forms/prior_authority/steps/travel_detail_form.rb, app/presenters/prior_authority/tasks/primary_quote.rb, spec/factories/quote.rb, spec/presenters/prior_authority/tasks/primary_quote_spec.rb, spec/services/submit_to_app_store/prior_authority_payload_builder_spec.rb
Fix flow when changing from detained to not detained requiring a travel_cost_reason
* Primary quote marked as in process in task list
* click primary quote link will direct user to travel cost screen when it is invalid
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1541)
=> Crm457 1541/missing travel reason

app/views/prior_authority/steps/check_answers/edit.html.erb
Ensure paragraphs maintained for incorrect info
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1564)
so when page renders errors the incorrect info
is displayed using the same formatting when there
are no errors.
Picked up by designer.
=> CRM457-1564: Ensure paragraphs maintained for incorrect info

config/gatekeeper.yml
Add second "extension of Upper Limit" (CRM5) onboarding
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1589)
PM decided to onboard early to get more EoUL applications
=> CMR457-1589: Add second "extension of Upper Limit" (CRM5) onboarding tranche

app/forms/prior_authority/steps/alternative_quotes/detail_form.rb, app/services/submit_to_app_store/prior_authority/quote_payload_builder.rb, spec/factories/prior_authority_application.rb
[CRM4 Caseworker: Application cannot be opened potentially due to number of uploads](https://dsdmoj.atlassian.net/browse/CRM457-1567)
*Misleading bug, the real issue is that there are issues with the quotes data and the way that data is consumed by caseworker app 
This PR uses the primary quote item type and cost type for alternative quotes when constructing the payload because these are defined as such in the business process
This PR is to address[ this error ](https://ministryofjustice.sentry.io/issues/5453466200/?alert_rule_id=14899609&alert_type=issue&notification_uuid=56ce2154-7606-407b-91c5-e19f3f0e3438&project=4506020469473280&referrer=slack) which seems to be happening because the cost type isn't being set on alternative quotes
=> Fix Alternative Quotes Incorrect Data

app/services/providers/gatekeeper.rb, spec/services/providers/gatekeeper_spec.rb, spec/system/access_spec.rb, spec/system/sign_in_spec.rb
Enable simple onboarding of ALL providers per service
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1590)
Current onboarding approach requires adding all office codes to the provider app and specifying which service(s) they can use. This will become onerous as we onboard more and pointless when we go to public
beta and ALL crime providers (in LAA portal) will be allowed access.
This enables us to switch on a specific form type/service for all providers with the portal link, sa below (for crm5)
```
production:
office_codes:
ALL: ['crm5']
```
You can test locally by adding below config and try to access with a test user mock login that normally would have no access.
```
localhost:
office_codes:
ALL: ['crm5']
```
=> CRM457-1590: Enable simple onboarding of ALL providers per service

app/views/nsm/steps/case_details/edit.html.erb
Fix GDS error handling on nested remittal date field
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1594)
Just needed to be a symbol to pick up the
default behaviour.
=> CMR457-1594: Fix GDS error handling on remittal date field

config/gatekeeper_crm4.yml
Add second CRM4 onboarding tranche - 11/06/2024
**NOT BEFORE 11/06/2024**
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1515)
Early adopters part 2
=> CRM457-1515: Add second CRM4 onboarding tranche - 11/06/2024

config/locales/en/errors.yml
Add custom date errors for main offence and remittal
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1594)
At designer request the main offence date
and remittal date have been given custom
error messages.
=> crm457-1594: Add custom date errors for main offence and remittal

config/locales/en/helpers.yml
Remove NSM solicitor reference hint text
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1604)
Was wrong, as using office code example, plus
is not needed, as requested by content design.
=> CMR457-1604: Remove NSM solicitor reference hint text

helm_deploy/templates/service-monitor.yaml, helm_deploy/values-prod.yaml, helm_deploy/values-uat.yaml
[[MVP] - MONITORING - Exporting metrics for Redis Queues and Sidekiq](https://dsdmoj.atlassian.net/browse/CRM457-1360)
Adds the sidekiq port to the service monitor - this is to test whether the service monitor can access the worker port
=> CRM457-1360: Add sidekiq port to service monitor

app/forms/nsm/steps/disbursement_cost_form.rb, app/forms/nsm/steps/disbursement_type_form.rb, app/models/disbursement.rb, app/views/nsm/steps/disbursement_cost/edit.html.erb, app/views/nsm/steps/disbursements/edit.html.erb, spec/forms/nsm/steps/disbursements_cost_form_spec.rb, spec/forms/nsm/steps/disbursements_type_form_spec.rb, spec/system/nsm/disbursement_type/disbursement_costs_spec.rb, spec/system/nsm/disbursements_spec.rb
Make CRM7's prior authority question conditional
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1599)
Inline with bug raised by BA, the prior authority question
should only be asked if the disbursement of an "other" type
and NOT for mileage disbursements.
=> CRM457-1599: Make CRM7's prior authority question conditional

helm_deploy/templates/service.yaml, helm_deploy/values-dev.yaml
Remove `-` from if statement
leeads to erroneous yaml
```sh
helm upgrade laa-submit-crime-forms ./helm_deploy/. \
--install \
--dry-run \
--namespace=laa-submit-crime-forms-dev \
--values ./helm_deploy/values-dev.yaml \
--set image.repository="754256621582.dkr.ecr.eu-west-2.amazonaws.com/laa-crime-forms-team/laa-submit-crime-forms-dev-ecr" \
--set image.tag="some-commit-sha"
```
=> Fix service.yml file

app/controllers/prior_authority/steps/further_information_controller.rb, app/controllers/prior_authority/steps/reason_why_controller.rb, app/javascript/file-upload.js, app/views/nsm/steps/supporting_evidence/edit.html.erb, app/views/prior_authority/steps/further_information/edit.html.erb, app/views/shared/_multifile_upload.html.erb, spec/factories/further_informations.rb, spec/presenters/prior_authority/check_answers/further_information_card_spec.rb, spec/services/submit_to_app_store/prior_authority_payload_builder_spec.rb, spec/system/nsm/supporting_evidence_spec.rb, spec/system/prior_authority/further_information_request_spec.rb, spec/system/prior_authority/reason_why_spec.rb, spec/system/support/screenshot_helper.rb
Supporting evidence delete button fix
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1600)
Fix delete link  functionality on NSM supporting evidence page.
=> CRM457-1600: Supporting evidence delete button fix

app/forms/prior_authority/quote_cost_validations.rb, app/forms/prior_authority/steps/quote_cost_form.rb, app/lib/prior_authority/service_type_rule.rb, app/services/submit_to_app_store/prior_authority/quote_payload_builder.rb, app/validators/cost_item_type_dependant_validator.rb, app/views/prior_authority/steps/primary_quote_summary/_service_cost_subtable.html.erb, app/views/prior_authority/steps/service_cost/_items.html.erb, config/locales/en/prior_authority/steps.yml, spec/services/submit_to_app_store/prior_authority_payload_builder_spec.rb, spec/system/prior_authority/alternative_quotes_spec.rb, spec/system/prior_authority/service_cost_spec.rb, spec/validators/cost_item_type_dependant_validator_spec.rb
[CRM4 - Content Change - Service Type - Translation (documents)](https://dsdmoj.atlassian.net/browse/CRM457-1612)
-  Add Cost Multiplier To Service Type Rules
-  Default Cost Multiplier To 1 If Not Provided In Initiailization
-  Set Cost Multiplier To 0.001 For Translation (documents)
-  Use Cost Multiplier In Service Cost Form
-  Add Cost Item to Service Type Rule For Alternate Qualifiers (such as thousand words instead of words)
- Update Tests
=> Crm457 1612 fix translation

app/javascript/file-upload.js, app/views/shared/_multifile_upload.html.erb, spec/system/nsm/supporting_evidence_spec.rb, spec/system/prior_authority/further_information_request_spec.rb, spec/system/prior_authority/reason_why_spec.rb
Add progress bar and check mark to denote successful upload
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1617)
This mechanism overides the MOJFrontend uploadFiles (not the plural)
method and leverages promises and async functions to wait for ALL
uploads to complete before re-enabling.
It also changes the behaviour to NOT hide/remove failed uploads but rather
display them with a warning icon. This is because in such instances
the top level feedback warning may be overwritten by successful uploads
in the same drag and drop batch, leaving the user unaware their upload for
one or more of their files failed.
https://www.loom.com/share/b1f93a88a43b4f49849718f1d5e2878a?sid=e996c454-f8f5-4ddd-83d7-7c662a95dc63
=> CRM457-1617: Add progress bar and check mark to denote successful upload

.circleci/config.yml
[End to End tests block deployment to production](https://dsdmoj.atlassian.net/browse/CRM457-1578)
Ticket only explicitly says to block deployment to production but decided to also block deployment to dev and uat because otherwise we have to manually rollback afterwards and we shouldn't have faulty code in UAT
=> End to End Test Required to Pass Before any Deployment

helm_deploy/templates/ingress.yaml
We have been experiencing some ModSec false positives, and we are aware of other teams experiencing them. This PR disables some of the more unreliable rules:
Civil Apply [found](https://dsdmoj.atlassian.net/wiki/spaces/ATPPB/pages/3686039762/ModSecurity) that this was triggering if "a user ends a sentence with get and a single word, followed by a new line"
We [found](https://mojdt.slack.com/archives/C06UR7V28RZ/p1718890420747279) that this was triggering if a string in a JSON payload contained two consecutive pairs of parentheses, such as "...The preparation hourly rate has been reduced as per Schedule 1 of The Criminal Legal Aid (Remuneration)(Amendment) Regulations 2022..."
Crime Apply [found](https://github.com/ministryofjustice/cla_public/pull/1238) that this was triggering on a …
=> CRM457-1657: Remove some modsec false positives

helm_deploy/templates/ingress.yaml
Modsec is currently rejecting any file upload larger than 13MB. If the file is the PA primary quote attachment, the user sees a named nginx "403 forbidden" page. Not only is this a horrible UX, it is more horrible even than modsec's normal UX - in most cases when modsec false positives we can show a custom, descriptive error screen. But modsec treats files differently. Worst of all, when it intervenes like this, no logs are generated - neither ingress nor modsec logs, meaning we have no visibility of when it occurs.
We already have a user-friendly unhappy path for larger than 10MB file uploads. On top of that, we already have protections at ingress level for files larger than 50MB that kick in without waiting for the file to be uploaded and showing an error message screen that at least …
=> CRM457-1349: Stop modsec rejecting large files

app/views/nsm/steps/view_claim/allowed_work_items.html.erb, config/locales/en/nsm/view_claim.yml
Amend content for when no adjustments of type exist
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1696)
Have brought the allowed work items partial inline with letters and calls, and disbursements equivalents. Prior to this it was rendering the pagy link, which had none to display so show "No work items" based on it's rendering logic. Now it explicitly checks for adjusted work items and displays specific text and no pagy links when there are none.
=> CRM457-1696: Amend content for when no adjustments of type exist

app/controllers/prior_authority/applications_controller.rb, app/presenters/prior_authority/check_answers/compact_further_information_card.rb, app/presenters/prior_authority/check_answers/primary_quote_card.rb, app/presenters/prior_authority/check_answers/reason_why_card.rb, app/presenters/prior_authority/check_answers/report.rb, app/views/prior_authority/applications/_application_details.html.erb, app/views/prior_authority/applications/pdf.html.erb, app/views/prior_authority/applications/response_summaries/_sent_back.html.erb, app/views/prior_authority/steps/alternative_quote_details/confirm_delete.html.erb, app/views/prior_authority/steps/alternative_quotes/_quote_summary.html.erb, app/views/prior_authority/steps/alternative_quotes/_with_alternative_quotes.html.erb, app/views/prior_authority/steps/check_answers/_alternative_quotes.html.erb, spec/system/prior_authority/view_applications_spec.rb
- PDF download was breaking because link generation to uploaded documents was failing
- It shouldn't have been failing, but also the PDFs shouldn't have links inside them anyway (because those links look ugly and will not work as they link to authenticated URLs)
- So this removes links to documents from PDFs
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1705)
=> CRM457-1705: Do not show links to documents on PDFs

.circleci/config.yml, app/controllers/nsm/steps/view_claim_controller.rb
Change snyk docker scanning approach
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1529)
This implements all but the IaC scan. The reason for not implementing IaC scanning now is:
- IaC needs rendered terraform or k8s manifests to scan, not helm templates
- attempts to render the manifests and pass them to the `snyk IaC test` hit various problems to do with helm install on test-executor (overcome), requiring k8s login for rendering the manifest (requiring cloud-platform-executor) or snyk install on cloud-platform-executor, and it has not been possible to test whether a helm upgrade --dry-run output would work. Certainly a `helm template blah` command as suggested by snyk docs is insufficient in our case. Ideally the cloud-platform-executor would have snyk installed …
=> CRM457-1529: Change snyk docker scanning approach

lib/tasks/db.rake, run.sh
Sometimes 2 pods run migrations at the same time, one loses the race, and we get error messages on Slack even though nothing bad has happened. This should prevent those false positives.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1672)
=> CRM457-1672: Try to avoid migration races

.env.development, app/services/app_store_subscriber.rb, config/environments/production.rb, helm_deploy/templates/_helpers.tpl, helm_deploy/templates/deployment.yaml, spec/services/app_store_subscriber_spec.rb
By using the service URL instead of the host name associated with the ingress to construct our webhook url, we allow our app store -> provider HTTP requests to bypass modsec, which is good because modsec is notorious for false positives, and these requests should never be treated as a modsec positive.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1660)
I have adjusted our Cloud Platform permissions to allow internal network requests from the app store namespaces to the provider namespaces.
=> CRM457-1660: Use internal hostname to bypass modsec

app/jobs/submit_to_app_store.rb, app/services/fixes/multiple_primary_quote_fixer.rb, app/services/submit_to_app_store/payload_builder.rb, app/services/submit_to_app_store/prior_authority_payload_builder.rb, lib/tasks/fixes.rake, spec/jobs/submit_to_app_store_spec.rb, spec/lib/tasks/fixes_spec.rb, spec/services/fixes/multiple_primary_quote_fixer_spec.rb, spec/services/submit_to_app_store/payload_builder_spec.rb
Intended usage:
- First run `identify` to find applications that need fixing
- Run the new app store task to temporarily set those to `sent_back`
- Then run `fix` to correct the data and send a new version to the app store
- Run the new app store task to set the applications back to their correct state and notify caseworker so it syncs everything correctly.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1747)
=> CRM457-1747: Add task to fix applications with multiple primary quotes

app/services/submit_to_app_store/prior_authority_payload_builder.rb, spec/services/submit_to_app_store/prior_authority_payload_builder_spec.rb
CRM457-1715: Add timestamps to PA payload on submission
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1715)
So we can use for setting appstore application.last_updated_at
for submitted applications with no events. This prevents delays
in creation of the record due to sidekiq processing from impacting
search results that look for applications based on when the
applications was "last_updated_at" - which for new applications is 
should be set to be when the "application" blob was sent (i.e. pa record's updated_at 
at point of submission).
=> CRM457-1715: Add timestamps to PA payload on submission

helm_deploy/templates/ingress.yaml
Redundant because we don't use mssql. False positives happening in the wild (so far only on the app store metabase)
Redundant because we don't use Java. False positives happening on our javascript sourcemaps
=> CRM457-1721: Remove modsec false positives

app/services/prior_authority/assessment_syncer.rb, spec/controllers/nsm/steps/defendants_delete_controller_spec.rb, spec/controllers/nsm/steps/disbursements_delete_controller_spec.rb, spec/controllers/nsm/steps/work_items_delete_controller_spec.rb
Currently transient errors etc can lead to FIs being duplicated. This ensures that each FI is only created once in the DB.
Also removes some warnings from the tests by stopping `allow`ing on nil.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1783)
=> CRM457-1783: Multiple FIs

.circleci/config.yml, .yamllint, package.json, yarn.lock
[Last outcome for this ticket](https://dsdmoj.atlassian.net/browse/CRM457-1547)
Note: this runs helm lint AND helm template (debug) because from my experience helm lint won't always necessarily catch issues that can break a chart (I tested helm lint on some misconfigurations and it didn't catch some of them) where helm template will AND helm template doesn't give us warning level suggestions like helm lint does - so both in tandem covers all bases for breaking changes and suggestions
Also including yamllint to check for things like duplicate keys upon suggestion from @elken[ in this PR](https://github.com/ministryofjustice/laa-submit-crime-forms/pull/1013)
=> Add additional helm chart and yaml linting/verifying

app/controllers/nsm/steps/disbursement_type_controller.rb, app/controllers/nsm/steps/disbursements_controller.rb, app/controllers/nsm/steps/work_item_controller.rb, app/helpers/application_helper.rb, app/models/claim.rb, app/models/disbursement.rb, app/services/sorters/array_sorter.rb, app/services/sorters/disbursements_sorter.rb, app/services/sorters/work_items_sorter.rb, app/views/nsm/steps/disbursements/edit.html.erb, app/views/nsm/steps/view_claim/allowed_disbursements.html.erb, app/views/nsm/steps/view_claim/disbursements.html.erb, config/locales/en/nsm/steps.yml, config/routes.rb, db/migrate/20240801134244_add_position_to_disbursements.rb, db/schema.rb, spec/controllers/nsm/steps/disbursements_type_controller_spec.rb, spec/helpers/application_helper_spec.rb, spec/models/claim_spec.rb, spec/services/submit_to_app_store/nsm_payload_builder_spec.rb, spec/system/nsm/disbursements_spec.rb, spec/system/nsm/office_code_spec.rb, spec/system/nsm/view_claim_spec.rb
Implement new designs for viewing and adding disbursements
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1758)
**Disbursement Summary Table**
**Duplicate Functionality**
**Adding a New Disbursement**
**Accessibility Criteria**
=> CRM457-1758: CRM7 Provider add a disbursement 

.circleci/config.yml, .github/dependabot.yml
Per a discussion in [slack](https://mojdt.slack.com/archives/C05212WRK5J/p1723021539555329), ensure that the version of puppeteer doesn't change.
Looks like the issue wasn't the fact we bumped a minor version, the circleci step was installing a whole different version to the one used in the app. Whatever the change to major version 23 is, it looks like it breaks quite a lot so I've proposed we freeze the version that we have
=> Freeze puppeteer

app/helpers/sortable_table_helper.rb, app/views/nsm/steps/disbursements/edit.html.erb
Fix table links aria label Ids
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1758)
Handles accessibility failings for links in table rows.
Alternative link text is contructed by the browser for any links
in a table row. For example, "Item 1 Car mileage", "Duplicate Item 1 Car mileage"
or "Delete Item 1 Car mileage". Previously the "Item"
text was not being found as the id `itemTitle` was on the header cell `th`
containg the form with a button with the text 'Item'. This may be a bug
with the accessibility tooling or browser itself (firefox), but nonetheless
we can fix this by moving the id to the button of the form.
=> CRM457-1758: Fix table links aria label Ids

app/forms/nsm/steps/solicitor_declaration_form.rb, app/models/claim.rb, db/migrate/20240806082652_backfill_disbursement_position.rb, db/schema.rb, spec/models/claim_spec.rb
Persist disbursement positions on submission
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1812)
Storing the position of disbursements so that case workers and providers can communicate
using a the position number to indicate item under discussion.
=> CRM457-1812: Store nsm disbursement position on submission 

config/locales/en/errors.yml, config/locales/en/nsm/check_answers.yml, config/locales/en/nsm/steps.yml, config/locales/en/prior_authority/steps.yml, spec/system/nsm/office_code_spec.rb, spec/system/prior_authority/case_contact_spec.rb
Change "firm account" to "firm office account"
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1840)
Content changes inline with content designers because:
- Each account number is for a specific office but ‘office’ is not included in this question or on this page.
- This team has always talked interchangeably about ‘office account number’ and ‘firm account number’
- After this question, we’ll be asking about whether the office is in an undesignated area and keeping ‘office’ in both questions should make the flow more smooth.
Second commit changes crm4 too and needs confirming with content design
=> CRM457-1840: firm office account content changes

app/controllers/nsm/claims_controller.rb, app/controllers/prior_authority/applications_controller.rb, app/views/nsm/claims/confirm_delete.html.erb, app/views/nsm/claims/index.html.erb, config/locales/en/nsm/claims.yml, config/routes.rb, spec/system/nsm/delete_claim_spec.rb
Allows deletion of CRM7 claims.
Could potentially improve this by using the same view for both and passing in the URLs as a local.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1025)
=> CRM457-1025: Allow deleting draft CRM7 claims

app/controllers/nsm/claims_controller.rb, app/controllers/prior_authority/applications_controller.rb, app/models/claim.rb, app/views/nsm/claims/confirm_delete.html.erb, app/views/nsm/claims/index.html.erb, config/locales/en/nsm/claims.yml, config/routes.rb, spec/system/nsm/claims_list_spec.rb, spec/system/nsm/delete_claim_spec.rb
Add [sub-navigation](https://design-patterns.service.justice.gov.uk/components/sub-navigation/) to CRM7 as per the requirements listed on the ticket.
The delete action on the page just links to `#` as that work is meant to be part of [this ticket](https://dsdmoj.atlassian.net/browse/CRM457-1025).
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1021)
=> CRM457-1021: Add sub-navigation to CRM7

app/forms/nsm/steps/hearing_details_form.rb, app/forms/nsm/steps/work_item_form.rb, app/models/concerns/stage_reached_calculatable.rb, app/models/work_item.rb, app/presenters/nsm/check_answers/hearing_details_card.rb, app/value_objects/work_types.rb, app/views/nsm/steps/hearing_details/edit.html.erb, app/views/nsm/steps/work_items/edit.html.erb, config/locales/en/errors.yml, config/locales/en/helpers.yml, config/locales/en/nsm/check_answers.yml, db/migrate/20240808140456_remove_in_area_from_claims.rb, db/schema.rb, gems/laa_multi_step_forms/app/views/laa_multi_step_forms/task_list/show.html.erb, spec/factories/claims.rb, spec/factories/work_items.rb, spec/forms/nsm/steps/hearing_details_form_spec.rb, spec/forms/nsm/steps/work_items_add_form_spec.rb, spec/presenters/nsm/check_answers/hearing_details_card_spec.rb, spec/presenters/nsm/check_answers/work_items_card_spec.rb, spec/presenters/nsm/cost_summary/disbursements_spec.rb, spec/presenters/nsm/cost_summary/work_items_spec.rb, spec/services/submit_to_app_store/nsm_payload_builder_spec.rb, spec/system/nsm/hearing_details_spec.rb, spec/system/nsm/work_items_spec.rb
'in_area' has now been replaced by the prog/prom questions.
Also, add a check so that if prog-prom changes, invalid work item types will be flagged as invalid and the user will be forced to change to a valid type.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1841)
=> CRM457-1841: Use calculated stage instead of explicit 'in area' question

app/services/nsm/assessment_syncer.rb, app/services/prior_authority/assessment_syncer.rb, spec/jobs/pull_updates_spec.rb, spec/services/nsm/assessment_syncer_spec.rb, spec/services/prior_authority/assessment_syncer_spec.rb
Stop looking at events in payloads and instead get assessment comments from the blob
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1785)
=> CRM457-1785: Stop looking at events in payload

app/jobs/submit_to_app_store.rb
`retry_on` is part of the ActiveJob DSL that causes errors to be swallowed until a certain number of retries, after which the error is allowed to bubble up to the underlying mechanism (in our case Sidekiq, which will report the error to Sentry) This isn't actually the behaviour we want - if a job is failing we want Sentry to be informed immediately the first time it fails, on the grounds that _normally_ this is going to be the indication of a problem, not some harmless transient error, so we want as much heads up as possible.
=> CRM457-1847: Remove 'retry_on'

app/javascript/single-file-upload-validator.js, app/views/prior_authority/steps/alternative_quote_details/edit.html.erb, app/views/prior_authority/steps/primary_quote/edit.html.erb, spec/system/prior_authority/primary_quote_spec.rb
Add client side validation of single file uploads
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1838)
To provide early feedback to providers when
uploading single files over the limit and
to avoid "413 entity too big errors" for really
large files.
Multifile upload pages already do this, per file.
=> CRM457-1838: Add client side validation of single file uploads

app/forms/nsm/steps/solicitor_declaration_form.rb, app/forms/prior_authority/steps/check_answers_form.rb, app/services/app_store_client.rb
Calling `perform_later` inside a transaction (including a lock) risks a race condition where the job might run before the transaction has been committed so uses stale DB data. This could cause incorrect data to be sent to the app store.  We've previously just lived with this, which is a high-risk strategy, as it relies on the app store always spotting and rejecting incorrect data. This PR moves the perform_laters until after the transactions have been committed.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1858)
=> CRM457-1858: Move perform_laters out of transactions

app/forms/prior_authority/quote_cost_validations.rb, app/validators/cost_item_type_dependant_validator.rb, app/validators/item_type_dependant_validator.rb, config/locales/en/errors.yml, spec/validators/cost_item_type_dependant_validator_spec.rb, spec/validators/item_type_dependant_validator_spec.rb
Add specific messaging for not-whole-numbers
Remove unused options (item_type_dependant is always pluralized, cost_item_type_dependant is never pluralized)
Remove redundant values in specs
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1828)
=> CRM457-1828: Validation message when decimal entered into items field

app/forms/nsm/steps/letters_calls_form.rb, config/locales/en/errors.yml, config/locales/en/helpers.yml, spec/forms/nsm/steps/letters_calls_form_spec.rb, spec/system/nsm/letters_calls_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-789)
adds validation to catch 0 or blank uplifts on letter and calls form in CRM7 
Provider could enter 0 or leave blank and apply an uplift percentage to that
Validation catches uplift applied to 0 or blank and feebacks warning message to provider on save
- create a CRM7 and on letters and calls form enter a blank or 0 for either/both letter or calls and apply and uplift
- save for will respond with expected validation errors
=> [CRM457-789] letters calls validation if uplift apply true

app/models/concerns/work_item_costs.rb, app/models/work_item.rb, app/services/nsm/assessment_syncer.rb, app/services/submit_to_app_store/nsm_payload_builder.rb, app/views/nsm/steps/view_claim/_allowed_work_items.html.erb, app/views/nsm/steps/view_claim/work_item.html.erb, config/locales/en/nsm/view_claim.yml, db/migrate/20240628134832_add_allowed_work_type_to_work_items.rb, db/schema.rb, spec/services/nsm/assessment_syncer_spec.rb, spec/services/submit_to_app_store/nsm_payload_builder_spec.rb, spec/system/nsm/view_claim_spec.rb
- Put relevant pricing data into the payload
- Sync back changes to work type post assessment
- Display adjusted work items in correct places with correct pricing
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1689)
We've agreed that in future pricing data may be held centrally so that caseworker can access what it needs without help like this, but for now adding relevant pricing to the payload is the least painful way of being ready for private beta.
=> CRM457-1689: Changeable work types

app/assets/stylesheets/custom/govuk-table.scss
`max-width` value was chosen arbitrarily, so can change if it's too small/large.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1808)
=> CRM457-1808: Constrain long lines without whitespace in tables

app/forms/prior_authority/steps/check_answers_form.rb, app/jobs/submit_to_app_store.rb, spec/jobs/submit_to_app_store_spec.rb
- Remove lock from CheckAnswersForm because there's now a lock higher up the call stack so putting another one in doesn't add value and just confuses us
- Add a lock to SubmitToAppStore so that the job can't run until the other lock has been released and its transaction has been committed, ensuring that the data the job is working with is up to date
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1905)
=> CRM457-1905: Fix locking issues

app/forms/prior_authority/steps/check_answers_form.rb, app/models/prior_authority_application.rb, app/services/submit_to_app_store/prior_authority_payload_builder.rb, gems/laa_multi_step_forms/Gemfile.lock, gems/laa_multi_step_forms/app/forms/steps/base_form_object.rb, gems/laa_multi_step_forms/spec/forms/steps/base_form_object_spec.rb, gems/laa_multi_step_forms/spec/forms/steps/has_one_association_spec.rb, spec/factories/prior_authority_application.rb, spec/services/submit_to_app_store/prior_authority/event_builder_spec.rb, spec/services/submit_to_app_store/prior_authority_payload_builder_spec.rb
We don't save confirmation fields to the DB, so in production we never actually send them to the app store. But the tests act like we do. Since we don't, and we don't need to, we can clear out a bunch of redundant code that misleadingly makes it look like we persist this stuff and send it to the app store.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1905)
=> CRM457-1905b: Remove redundant code

lib/tasks/fixes.rake, spec/lib/tasks/fixes_spec.rb
Add rake task for correcting contact emails
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1909)
For situations where a provider has entered a valid
format of email but which is nonetheless undeliverable.
=> cCRM457-1909: Add rake task for correcting contact emails

app/presenters/nsm/check_answers/claim_type_card.rb, app/presenters/nsm/check_answers/your_details_card.rb, app/presenters/nsm/tasks/claim_type.rb, app/presenters/nsm/tasks/firm_details.rb, app/services/decisions/back_decision_tree.rb, app/services/decisions/decision_tree.rb, app/views/nsm/steps/office_code/edit.html.erb, config/locales/en/nsm/check_answers.yml, spec/presenter/nsm/steps/claim_type_presenter_spec.rb, spec/presenter/nsm/steps/firm_details_presenter_spec.rb, spec/presenters/nsm/check_answers/claim_type_card_spec.rb, spec/presenters/nsm/check_answers/your_details_card_spec.rb, spec/system/nsm/office_code_spec.rb
- Move the office code question to a different point in the flow
- And the answer to a different check answers card
- The office code question now doesn't have 'save and come back later' because it's in the initial flow of questions before you reach the task list
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1861)
=> CRM457-1861: Move office code question

app/services/prior_authority/assessment_syncer.rb
Make sync_incorrect_info_request behave like sync_further_info_request
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1936)
=> CRM457-1936: Use find or create within the lock

app/controllers/healthcheck_controller.rb, spec/controllers/healthcheck_controller_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1864)
This does seem to be doing something - in the screenshot below, the readiness probe is briefly failing with a 503, which I'm not seeing happen on other branches, suggesting that the change is extending the period of unreadiness while Clamby is unavailable.
=> CRM457-1864: Wait for Clamby.safe? to actually succeed

config/gatekeeper_crm7.yml
Give dummy prod user access to crm7/NSM
[came out of](https://dsdmoj.atlassian.net/browse/CRM457-1907)
For sanity testing. Inline we what we had/have for crm4
and crm5 already.
=> Give dummy prod user access to crm7/NSM

lib/test_data/nsm_builder.rb, lib/test_data/pa_builder.rb, spec/lib/test_data/nsm_builder_spec.rb, spec/lib/test_data/pa_builder_spec.rb
Add logic so if year is current year, dates should be in the past
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1885)
=> CRM457-1885: Make rake tasks work with current year

spec/lib/tasks/submit_dummy_data_spec.rb, spec/rails_helper.rb
Silence output to console from testing of rake tasks
Rake tasks often having stdout output but this comes
out when running rspec and clutters the console.
=> Swallow output to stdout during tests for rake tasks

app/services/risk_assessment/low_risk_assessment.rb, spec/services/risk_assessment/low_risk_assessment_spec.rb
This PR brings our low/medium risk calculation in line with:
* [The spreadsheet the caseworkers actually use](https://docs.google.com/spreadsheets/d/1P1E9JPcmAgxDcy7NWIq4IckQPzL-bPg1/edit?gid=1493704751#gid=1493704751)
* [The Miro board that describes the logic](https://miro.com/app/board/uXjVO21KiPg=/?moveToWidget=3458764529879393901&cot=14)
* [The flowchart from the confluence board Emma wrote up 2 years ago](https://dsdmoj.atlassian.net/wiki/spaces/CRM457/pages/4108943555/Risk+Based+Billing+Assessment)
The logic is also consistent with [this Google doc](https://docs.google.com/document/d/1SDzpK5ApQU-zTjpygmeCgiErJhDdFYbR/edit) describing the risk logic and [this walk-through of the logic](https://mojdt.slack.com/archives/C034YPREUSF/p1724776493722329?thread_ts=1724760197.910909&cid=C034 …
=> CRM457-1947: More fixes to risk calculation

app/forms/prior_authority/steps/ufn_form.rb, spec/system/prior_authority/ufn_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1964)
=> CRM457-1964: Stop changing LAA reference on every form submission

app/presenters/nsm/check_answers/application_status_card.rb, config/application.rb, spec/presenters/nsm/check_answers/application_status_card_spec.rb
NSM RFI email is [CRM7fi.request@justice.gov.uk](mailto:CRM7fi.request@justice.gov.uk) but we have it listed as [crm7fi@justice.gov.uk](mailto:crm7fi@justice.gov.uk). Also we arguably defined it in the wrong place.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1965)
=> CRM457-1965: Fix email address

config/feature_flags.yml
Enable maintance mode for PROD appstore DB upgrade 4/09/2024
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1907)
=> CRM457-1907: Enable maintenance mode on prod

lib/tasks/fixes.rake, spec/lib/tasks/find_mismatched_references_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1966)
Finds sent_back CRM4 applications that have mismatched laa references with their current version in the App Store
=> Crm457 1966 find incorrect refs

app/presenters/prior_authority/check_answers/incorrect_information_card.rb
Fix guard clause
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1982)
=> CRM457-1982: Handle situations where "old" incorrect information record has no 'sections changed'

app/models/claim.rb, app/presenters/nsm/check_answers/application_status_card.rb, app/presenters/nsm/check_answers/cost_summary_card.rb, app/services/nsm/assessment_syncer.rb, app/views/nsm/steps/view_claim/show.html.erb, spec/jobs/pull_updates_spec.rb, spec/presenters/nsm/check_answers/application_status_card_spec.rb, spec/services/nsm/assessment_syncer_spec.rb, spec/system/nsm/view_claim_spec.rb
Show adjustments and allowed total for granted applications with adjustments
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1950)
Claims can be adjusted upward and still granted. In such instances the
provider needs to be made aware of the adjustments nonetheless.
It has been agreed with PM and designer that if granted applications are adjusted downwards (which is currently possible) we would show the adjustments regardless for transparency. Going forward CRM457-1679 is intended to prevent caseworkers granting claims with downward adjustments.
=> CRM457-1950: show granted adjustments

app/views/nsm/steps/view_claim/_allowed_disbursements.html.erb
Handle nil  `allowed_total_cost_without_vat`
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1981)
If only VAT is changed by the caseworker this value
`allowed_total_cost_without_vat` was being sync'd
as `nil`, resulting in an empty net cost allowed
field.
=> CRM457-1981: handle nil `allowed_total_cost_without_vat`

lib/tasks/fixes.rake, spec/lib/tasks/find_mismatched_references_spec.rb
[Part 1: Find Mismatched Records in Provider App](https://dsdmoj.atlassian.net/browse/CRM457-1966)
=> CRM457-1966: Find Mismatched LAA References 

helm_deploy/templates/deployment.yaml
Pin clamav to older version
Latest version `sha-dfa1db2` erroring on our app
see https://github.com/ministryofjustice/hmpps-utility-container-images/pkgs/container/hmpps-clamav
=> Pin clamav version

app/forms/prior_authority/steps/check_answers_form.rb, app/services/prior_authority/assessment_syncer.rb, app/views/prior_authority/steps/check_answers/edit.html.erb, db/migrate/20240603125345_create_incorrect_informations.rb, db/migrate/20240918093306_remove_incorrect_information_explanation_from_application.rb, db/schema.rb, lib/test_data/pa_resubmitter.rb, spec/factories/prior_authority_application.rb, spec/services/prior_authority/assessment_syncer_spec.rb, spec/services/submit_to_app_store/prior_authority_payload_builder_spec.rb, spec/system/prior_authority/check_your_answers/sent_back_for_correct_info_spec.rb, spec/system/prior_authority/view_applications_spec.rb
Replace use of incorrect_information_explanation with incorrect_informations.information_requested
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1583)
Should be using the latest has_many relation incorrect_informations record value instead.
=> CRM457-1583: Replace incorrect_information_explanation

app/controllers/providers/omniauth_callbacks_controller.rb
This will be reverted after we do the check 
Only will apply to UAT so we don't put PII in logs
=> log auth_hash info when checking provider is enrolled

app/presenters/nsm/check_answers/application_status_card.rb
When a claim has expired, the most recent `further_information` stops being "pending", so we can't access it with `.pending_further_information`.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1988)
=> CRM457-1988 (BUG): Fix expired claim logic

bin/deploy, config/clamd/clamd.cloud-platform.conf, config/clamd/clamd.dev.conf, config/clamd/clamd.prod.conf, config/clamd/clamd.uat.conf, helm_deploy/templates/custom-error-pages.yaml, helm_deploy/templates/deployment-clamav.yaml, helm_deploy/templates/deployment-custom-errors.yaml, helm_deploy/templates/deployment-worker.yaml, helm_deploy/templates/deployment.yaml, helm_deploy/templates/service.yaml, helm_deploy/values-dev.yaml, helm_deploy/values-prod.yaml, helm_deploy/values-uat.yaml
- Instead of having clamav in a container on every app pod, have it running as its own pod in its own deployment accessed via its own service
- This allows clamav to have its own liveness probe, and not have to be restarted every time new app pods are rolled out
- Switch to using the latest image
- Only have one clam service on dev, not one per branch, reusing the same mechanism employed for the custom error service
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2101)
When this is merged, dev main will be responsible for the dev clam service, and branches will simply use the service. However, for the purposes of this getting clamby working for this PR we need the branch to run the service. Hence in the second commit I've hacked the config to have the branch deploy …
=> CRM457-2101: Move clam to separate deployment/pods

app/controllers/providers/omniauth_callbacks_controller.rb, app/models/provider.rb, app/services/active_office_code_service.rb, app/services/office_code_service.rb, app/services/provider_data_api_client.rb, spec/controllers/providers/omniauth_callbacks_controller_spec.rb, spec/models/provider_spec.rb, spec/services/active_office_code_service_spec.rb, spec/services/office_code_service_spec.rb, spec/support/authentication_helpers.rb
- Stop trusting portal to tell us correct office codes on each login
- Instead use the provider data API (which we also query about which office codes are active, so that it becomes the single point of truth about office codes)
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2064)
=> CRM457-2064: Get office codes from provider data API

app/jobs/send_notification_email.rb, app/jobs/submit_to_app_store.rb, app/services/submit_to_app_store/nsm_payload_builder.rb, db/migrate/20241015084055_add_synced_to_app_store_to_submissions.rb, db/schema.rb, spec/jobs/send_notification_email_spec.rb, spec/jobs/submit_to_app_store_spec.rb, spec/rails_helper.rb
Set a flag before running an async job, change the flag after running it, that way if we lose access to Redis (both the job queue and the logs of dead jobs), we know what needs to be re-synced.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2095)
=> CRM457-2095: Add flags indicating sync job status

app/forms/prior_authority/steps/case_contact/solicitor_form.rb, app/forms/prior_authority/steps/case_contact_form.rb, app/models/claim.rb, app/models/firm_office.rb, app/models/prior_authority_application.rb, app/models/solicitor.rb, db/migrate/20241015133053_delete_orphans.rb, db/schema.rb
- The original devs used to have a mechanism where for NSM firm offices and solicitors we'd try to share matching records across claims, and if the details changed we'd create a new version of the same record and link them. But it was never fully implemented and most of it was removed, except part of it got copy-pasted across to PA without really understanding it.
- The upshot is that there has been some code to "orphan" solicitor and firm office records every time they change, so that we have records no longer associated with a particular claim or application.
- This PR gets rid of the last vestiges of the orphaning mechanism, destroys all current orphans, and clears out some associated logic linking older and newer versions of records that never gets used
[Link to relevant …
=> CRM457-2013: Stop orphaning solicitor records

app/helpers/decision_step_header_helper.rb, app/presenters/prior_authority/check_answers/base.rb, app/presenters/prior_authority/check_answers/further_information_card.rb, app/presenters/prior_authority/check_answers/ufn_card.rb, app/services/decisions/back_decision_tree.rb, app/services/decisions/decision_tree.rb, spec/system/prior_authority/further_information_request_spec.rb
- Make sure back buttons don't lead to the task list in an RFI loop
- Hide 'change' links on check answers page in PA RFI if corrections are not allowed
This ticket simply fixes/hides links to prevent users accidentally going to places they shouldn't go. There is a separate ticket ([CRM457-2174](https://dsdmoj.atlassian.net/browse/CRM457-2174)) to make those places entirely inaccessible.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2173)
[CRM457-2174]: https://dsdmoj.atlassian.net/browse/CRM457-2174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRM457-2173: Fix "back" and "change" buttons in PA RFI

app/presenters/nsm/tasks/base.rb, app/presenters/nsm/tasks/cost_summary.rb, app/presenters/nsm/tasks/defendants.rb, app/presenters/nsm/tasks/disbursements.rb, app/presenters/nsm/tasks/work_items.rb, app/views/nsm/claims/search.html.erb, config/initializers/time_formats.rb, spec/presenter/nsm/steps/cost_summary_presenter_spec.rb, spec/presenter/nsm/steps/solicitor_declaration_presenter_spec.rb, spec/system/nsm/task_list_spec.rb
Override NSM task list to change labelling behaviour. Previously, if you'd completed a sectionB  but then amended a previous section A, removing B from the navigation stack, B would be marked as 'Not started' even though we still had all of the previously entered data for B. This made it look like we had thrown data away. Now we mark 'B' as in progress (by detecting that, despite not being in the stack, it is complete).
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2162)
=> CRM457-2162: Tweak task list behaviour

app/javascript/file-upload.js
Put delete params in payload, rather than badly trying to put them in the query string. (When there already is a query string in the URL, appending `?` just breaks stuff)
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2187)
=> CRM457-2187: Fix file deletion via check answers screen

app/controllers/prior_authority/steps/primary_quote_controller.rb, app/javascript/application.js, app/javascript/autocomplete.js, app/views/prior_authority/steps/primary_quote/edit.html.erb, package.json, yarn.lock
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2122)
This PR aims to improve the autocomplete in a number of ways:
Sometimes users put a space at the start or the end by mistake, as such leading and trailing spaces should be trimmed.
Case here is only useful to display grammatically correct strings to the user. A&E and a&e are identical so should be treated as such
The way this is handled should probably change, the hardcoded list is somewhat inflexible _but_ I also don't imagine the list will be changed much once it's committed.
Candidates should also be matched regardless of word order and regardless of if all the words are present. The following cases are now considered
- User types "Child Psychologist" and both that and "Psychiatrist (including child)" are …
=> CRM457-2122: Improve autocomplete effectiveness

app/services/search_service.rb, app/views/nsm/claims/search.html.erb, app/views/prior_authority/applications/search.html.erb, spec/system/search_spec.rb
Include the same change from https://github.com/ministryofjustice/laa-crime-application-store/pull/312 to ensure that we protect against incorrect syntax error exceptions.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2248)
=> CRM457-2248: Escape the query to prevent syntax errors

.circleci/config.yml, bin/snyk-formatted
Use Ruby to generate a nicely formatted output.
[Sample step](https://app.circleci.com/pipelines/github/ministryofjustice/laa-submit-crime-forms/6318/workflows/fb3968a1-a7a4-4565-8239-541edc44c41e/jobs/44093)
It'll likely break randomly over time, which is why I've also made the script save the full output as a JSON artifact. Even if the script fails, we can still check and see what broke.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2252)
=> Nicely format Snyk output

.snyk, bin/snyk-formatted
Add an issue without a fix to the list of ignored issues & add some colourisation to the output.
Running the Snyk monitor without this issue ignored looks like the below:
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2269)
=> CRM457-2269: Add CVE to Synk ignore list

.env.test, app/controllers/prior_authority/steps/submission_confirmation_controller.rb, app/forms/nsm/steps/solicitor_declaration_form.rb, app/forms/prior_authority/steps/check_answers_form.rb, app/jobs/submit_to_app_store.rb, app/services/app_store_client.rb, app/services/app_store_update_processor.rb, spec/forms/nsm/steps/solicitor_declaration_form_spec.rb, spec/forms/prior_authority/steps/check_answers_form_spec.rb, spec/jobs/submit_to_app_store_spec.rb, spec/services/app_store_client_spec.rb, spec/system/nsm/solicitor_declaration_spec.rb, spec/system/prior_authority/check_your_answers/sent_back_for_correct_info_spec.rb, spec/system/prior_authority/check_your_answers/submission_spec.rb
- Submit to app store synchronously
- Check the app store response to see if there's been an immediate state change (i.e. autogrant)
- Now the only thing that uses Sidekiq is the submission confirmation email
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2276)
=> CRM457-2276: Do things synchronously

app/presenters/nsm/check_answers/case_category_card.rb, app/presenters/nsm/check_answers/read_only_report.rb, app/presenters/nsm/check_answers/report.rb, config/locales/en/nsm/check_answers.yml, spec/presenters/nsm/check_answers/case_category_card_spec.rb, spec/presenters/nsm/check_answers/read_only_report_spec.rb, spec/presenters/nsm/check_answers/report_spec.rb, spec/system/nsm/check_answers_spec.rb, spec/system/nsm/view_claim_spec.rb
[CRM457-2291](https://dsdmoj.atlassian.net/browse/CRM457-2291)
[CRM457-2293](https://dsdmoj.atlassian.net/browse/CRM457-2293)
In place of `youth court fee feature flags` we are swapping `old` for `new` views of `case disposal` summaries in the CYA and view claims page via a check on `claim.include_youth_court_fee`. 
[CRM457-2291]: https://dsdmoj.atlassian.net/browse/CRM457-2291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CRM457-2293]: https://dsdmoj.atlassian.net/browse/CRM457-2293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRM457-2291][CRM457-2293] add YCF case disposal summary views to CYA and view_claim reports

app/presenters/nsm/check_answers/case_category_card.rb, app/presenters/nsm/cost_summary/additional_fees.rb, config/locales/en/nsm/check_answers.yml, spec/presenters/nsm/check_answers/case_category_card_spec.rb, spec/system/nsm/check_answers_spec.rb, spec/system/nsm/view_claim_spec.rb
fixes 
- capitalised sub-category display
- `change` on cost summary links to youth court fee confirmation page
- youth court fee confirmation listed as last element
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2271)
=> [CRM457-2271] Youth court additional fee changes to display of information

app/services/decisions/back_decision_tree.rb, app/views/nsm/steps/case_outcome/edit.html.erb, config/locales/en/nsm/steps.yml, spec/system/nsm/case_outcome_spec.rb
- Case outcome errors weren't including the radio buttons
- Adjusted how we set the outcomes list to match Case Category
- Remove extra margin from legend
- Add back "Save and come back later"
- Resolve incorrect back button logic with Post 6th NON-YC claims
=> CRM457-2263: Resolve QA issues

app/presenters/nsm/tasks/case_disposal.rb
We shouldn't consider whether or not the provider has selected to
claim the fee or not since they shouldn't be able to.
=> CRM457-2263: Only NSMs can claim the youth court fee

app/forms/nsm/steps/claim_type_form.rb, spec/forms/nsm/steps/claim_type_form_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2313)
- Add validation to not allow future dates for rep order date and CNTP date
=> CRM457-2313: Add future date validation back in

app/forms/prior_authority/steps/check_answers_form.rb, app/jobs/submit_to_app_store.rb, app/services/fixes/multiple_primary_quote_fixer.rb, app/services/submit_to_app_store/payload_builder.rb, app/services/submit_to_app_store/prior_authority/event_builder.rb, app/services/submit_to_app_store/prior_authority_payload_builder.rb, spec/jobs/submit_to_app_store_spec.rb, spec/services/prior_authority/change_lister_spec.rb, spec/services/submit_to_app_store/payload_builder_spec.rb, spec/services/submit_to_app_store/prior_authority/event_builder_spec.rb, spec/system/prior_authority/view_applications_spec.rb
"Events" are getting simpler. We don't need them to list what sections have changed. All we need is for `corrected_info` to be truthy if the provider responded to a request for corrections, and falsey if it was just a request for further info. This allows us to simplify the code somewhat. 
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2217)
=> CRM457-2217: Simplify event builder

app/models/concerns/letters_and_calls_costs.rb, spec/forms/nsm/steps/letters_calls_form_spec.rb
If the form fails validation, invalid number attributes may be held as strings (so we can accurately pre-populate the relevant field with the exact wrong input the user provided). But we will still be calling the calculator with the form values we have. To avoid it exploding, we `to_i` the values, so that if they are strings they will be treated as zeroes for the purposes of the calculation.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2273)
=> CRM457-2273: If validation fails, calculation should not explode

app/forms/nsm/steps/defendant_delete_form.rb, spec/forms/nsm/steps/defendants_delete_form_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2352)
I know we have a more complicated system for work items and disbursement line item numbers, but thinking about it, it really doesn't need to be complicated for defendants, given there will almost always be a very small number of them - this all takes place in a lock and it's quick and easy to renumber as needed.
=> CRM457-2352: Renumber defendants on deletion

config/routes.rb
Urgent change to stop using the old, now non-existent controller when
we hit an error.
[No ticket - conversation here](https://mojdt.slack.com/archives/C034YPREUSF/p1734608944347489)
=> Stop using the old errors controller

.rubocop.yml, .sonarcloud.properties, app/javascript/application.js, app/presenters/nsm/tasks/base.rb, spec/spec_helper.rb
Results of investigation on code after gem was removed to ensure no other issues are still present
Addresses some of [Clean up Rubocop setup](https://dsdmoj.atlassian.net/browse/CRM457-2353)
=> Remove multi form gem: Remove dead references to /gem folder and adjust some comments (CRM457-2353)

app/controllers/concerns/claim_creatable.rb, app/controllers/concerns/cloneable.rb, app/controllers/concerns/generates_laa_reference.rb, app/controllers/nsm/claims_controller.rb, app/controllers/nsm/imports_controller.rb, app/controllers/prior_authority/applications_controller.rb, app/models/claim.rb, app/models/firm_office.rb, app/models/prior_authority_application.rb, app/models/quote.rb, app/models/solicitor.rb, app/views/nsm/claims/index.html.erb, app/views/prior_authority/applications/_drafts.html.erb, config/locales/en/nsm/claims.yml, config/locales/en/prior_authority.yml, config/routes.rb, spec/controllers/nsm/claims_controller_spec.rb, spec/factories/claims.rb, spec/factories/prior_authority_application.rb, spec/models/quote_spec.rb, spec/system/prior_authority/create_application_spec.rb
Allows draft claims and draft applications to be cloned when not in
production (since it's mostly for testing) and also resolve some
incorrect `dependent` calls for `belongs_to` models that shouldn't
have it.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2338)
=> CRM457-2338: Add functionality to clone claims & applications

app/services/office_code_service.rb, app/services/provider_data_api_client.rb, config/feature_flags.yml, spec/services/office_code_service_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2262)
I want to do a test run in UAT before enabling this in production, so production feature flag is off for now 
[Old endpoint
](https://laa-provider-details-api-prod.apps.live.cloud-platform.service.justice.gov.uk/swagger-ui/index.html#/Provider%20Users%20Endpoints/getProviderUsersOffices)
[New endpoint](https://laa-provider-details-api-prod.apps.live.cloud-platform.service.justice.gov.uk/swagger-ui/index.html?urls.primaryName=V1#/Provider%20Users%20Endpoints/getProviderUsersOfficesV1)
=> CRM457-2262: Use v1 endpoint for provider user office codes

spec/system/production_spec.rb
Add additional specs to verify  which routes are routeable and confirm
specific behaviours when in and out of the production environment.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2358)
=> CRM457-2358: Add spec to test all the defined routes

app/models/claim.rb, app/models/concerns/disbursement_details.rb, spec/models/disbursement_spec.rb, spec/system/nsm/disbursements_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2430)
- Protect translated_disbursement_type method from returning nil
- Add additional testing to cover previously broken scenario
=> CRM457-2430: Provider: Disbursement Sorting on Type Breaks

app/services/nsm/import_service.rb, config/leap_schema.xml, spec/fixtures/files/import_sample.xml, spec/fixtures/files/unreadable_import.xml, spec/system/nsm/import_spec.rb
Introduce our own XML schema to be distributed out to software vendors. Due to the nature of how this process will work, it is quite imperative that we minimize the amount of changes we have to make.
Therefore, for this to pass review I think we should all as devs be happy that it captures everything we need for a claim. If we don't want to distribute it out just yet, we can iterate on it later as part of https://dsdmoj.atlassian.net/browse/CRM457-2373.
In either case, we should definitely aim to reduce the amount of iterations the schema recieves after we aim to distribute it.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2424)
A sample file have been included, as part of the work to implement the full claim journey we should also aim to include a myriad of other …
=> Introduce an XML schema

app/views/prior_authority/steps/service_cost/_cost_fields.html.erb, config/locales/en/prior_authority/steps.yml
Include extra hint text to clarify how multiple rates should be submitted as per the [prototype](https://crmfour-proto-main.apps.live.cloud-platform.service.justice.gov.uk/latest-pa/provider/form/question3-quote-prep?serviceType=Transcription).
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2390)
=> Add hint text to clarify how multiple rates should be submitted

app/services/nsm/importers/xml/import_service.rb
A component (determined by the error key) can only have a single error
associated to it currently.
Each iteration of the loop replaces the existing error with the next
and you just end up with a single error.
An alternative here is to put all the errors into a single
newline-separated array, but that means the errors show up next to the
component.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2445)
=> Return all XML validation errors

lib/tasks/simplecov/process_coverage.rake, spec/spec_helper.rb, spec/system/nsm/case_details/suggestion_autocomplete_spec.rb, spec/system/nsm/disbursement_type/suggestion_autocomplete_spec.rb, spec/system/nsm/further_information_spec.rb, spec/system/nsm/hearing_details/suggestion_autocomplete_spec.rb, spec/system/nsm/rfi_solicitor_declaration_spec.rb, spec/system/prior_authority/case_detail_spec.rb, spec/system/prior_authority/further_information_request_spec.rb, spec/system/prior_authority/primary_quote_spec.rb, spec/system/prior_authority/reason_why_spec.rb
A recent Chrome update has caused our system tests to fail for some unknown reason. We have tried looking at pinning to a specific version locally but nothing seems to resolve it so we're for now skipping these tests to review at a later date.
=> Skip tests impacted by recent Chrome update

app/services/search/app_store_service.rb
Prevents a data breach incident that was letting any providers search
for anyone else's claims if they didn't specify an account number
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2488)
=> Ensure that we default to scoping searches to just the office codes

app/services/nsm/importers/xml/v1/crm7_claim.xsd, app/services/nsm/importers/xml/v1/importer.rb, spec/fixtures/files/import_sample.xml, spec/fixtures/files/import_sample_with_missing_fields.xml, spec/services/nsm/importers/xml/v1/importer_spec.rb
Add documentation to the XML schema and make sensible assumptions
about some of the redundant fields (e.g. fields rely on a yes/no
answer we can autofill based on the presence)
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2485)
=> Document XML schema

config/feature_flags.yml
Enabling the feature flag to allow provider access to the new 'Import a Claim' flow.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2501)
=> Enable new Import a Claim flow in UAT/Production

spec/fixtures/files/unmatched_fields.xml, spec/system/nsm/import_spec.rb
Adds a test case to cover broken XML and tidy up the import test
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2450)
=> Add a test case to handle broken XML

app/services/nsm/importers/xml/v1/crm7_claim.xsd
Update the otherDisbursementType field to be free-text instead as the form component accepts it anyway
[Link to relevant discussion](https://mojdt.slack.com/archives/C034YPREUSF/p1742900835037949)
=> Make otherDisbursementType a free-text field

app/javascript/autocomplete.js, app/views/prior_authority/steps/primary_quote/edit.html.erb
Allow the service type combo box in PA function more like a drop-down
box and hopefully reduce the amount of free-text entries.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2478)
=> Show all service types when the box is focused even when empty

app/controllers/nsm/imports_controller.rb, app/services/nsm/importers/xml/v1/importer.rb
Rather than shadowing all errors that can occur, instead just handle
the case we care about.
As well as this, update the XML import to handle `reasons_for_claim`
missing and removing any possible attributes that can be part of a
`<claim>` node.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2534)
=> Correctly handle no file uploaded error for imports

app/models/prior_authority_application.rb, spec/models/prior_authority_application_spec.rb
When deleting Prior Authority applications, skip quotes that don't have a document uploaded
[Link to issue](https://mojdt.slack.com/archives/C06UR7V28RZ/p1743523826360149)
=> When deleting PA applications, skip quotes without a document

app/views/nsm/steps/disbursement_delete/edit.html.erb
When displaying the confirmation screen for disbursement deletion, fallback to the "Other disbursement type" branch unless we have a type present.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2550)
=> Only translate the other_type when present when deleting disbursements

.circleci/config.yml
More details here: https://mojdt.slack.com/archives/C57UPMZLY/p1746017554921989
=> Set cloud-platform-tools image to 2.9.9 to circumvent kubectl issue

app/services/pdf_service.rb
The IP whitelist interferes with this, so just inline the file when we
create PDFs
=> Pull in the CSS locally when creating PDFs

.github/actions/delete-dev-release/action.yml, .github/workflows/delete-dev-release.yml
No Ticket
The workflow that deletes old dev branches is called Delete UAT release, when it should be Delete Dev release - the corresponding action references UAT also. Updating as it's confusing to people inspecting config
=> Use correct env name for Dev Release Actions/Workflows

bin/deploy, helm_deploy/templates/_helpers.tpl, helm_deploy/templates/public-ingress.yaml, helm_deploy/values-prod.yaml
Remove the need to add Pingdom IPs to the whitelist by allowing the healthcheck endpoints to be public for `GET` requests only
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2628)
=> Add public ingress to allow Pingdom to use without whitelist

app/models/provider.rb, spec/models/provider_spec.rb
When attempting to migrate a user from the old system, compare the
list of office codes as well
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2673)
=> Update from_omniauth to handle office codes as well

.circleci/config.yml
The tests run as part of the regular PR process, any failures after
that are attributed to the brittleness of the suite and should
therefore be ignored.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2477)
=> Remove E2E tests from "merge to main" pipeline

db/migrate/20250805120900_remove_laa_reference.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2704)
This did not initially work locally because of syncing issues with the schema field and the migrations, was able to run a clean setup to test that this should work locally and remote
=> Crm457-2704: Remove Core Search Fields alongside LAA Reference

config/office_code_overrides.yml
Add office code: 0Z981E to active office code override list so that we can use it for testing what happens when PDA is down
=> Add office code for UAT Test Scenario 8

app/controllers/downloads_controller.rb, app/presenters/app_store/v1/supporting_document.rb, app/presenters/nsm/check_answers/base.rb, app/presenters/nsm/check_answers/evidence_uploads_card.rb, spec/factories/supporting_documents.rb, spec/presenters/nsm/check_answers/evidence_upload_card_spec.rb, spec/system/nsm/view_claim_spec.rb, spec/system/prior_authority/view_applications_spec.rb
Applies to both NSM & PA, impacts a few tests as well and we also now
make evidence links on NSM "view claim" screen actual clickable links.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2660)
=> Restrict access for downloads to providers that should have access to the submission
